function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(AgencySearch);
    convertContentToLanguage(AgencyDetails);
    convertContentToLanguage(AgencyBatchUpload);
}

TopMenu = [
 
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

AgencySearch = [
     ["pageTitleAgencyList", "Agency List"],
     ["pageSpanHeadingAgency", "Agency List"],
     ["pageSpanSubHeadingAgency", "You can check the agency information in a list"],
     ["buttonSpanAgencyReg", "Agency Registration"],
     ["buttonSpanImportAgencyData", "Import Existing Agency Data"],
     ["buttonSpanAgencyListCSV", "Output Agency List CSV"],
     ["pageSpanSearch", "Search"],
     ["pageLabelAgencyName", "Agency Name"],
     ["pageLabelAgencyNameKatakana", "Agency Name Katakana"],
     ["pageLabelBelonging", "Belonging"],
     ["pageLabelAgencyCode", "Agency Code"],
     ["pageLabelMobilePhone", "Mobile Phone"],
     ["pageLabelMailAddress", "Email Address"],
     ["pageLabelAddress", "Address"],
     ["pageLabelPostalcode", "Postal code"],
     ["pageLabelPrefectures", "Prefectures"],
     ["pageLabelDispatchClassification", "Dispatch Classification"],
     ["pageLabelAgencyRepresentativeName", "Agency Representative Name"],
     ["pageLabelAgencyRepresentativeNameKatakana", "Agency Representative Name Katakana"],
     ["pageOrganizationName", "Organization Name"],
     ["pageLabelManager", "Manager"],
     ["pageLabelCustomerRank", "Rank"],
     ["clearAllBtn", "Clear All"],
     ["searchBtn", "Search"],
     ["pageSpanSearchAgencyDetails", " Search Agency Details"],
     ["tableSearchStaffTHNo", "Record No"],
     ["tableSearchStaffTHChoice", "Choice"],
     ["tableSearchTHAgencyName", "Agency Name"],
     ["tableSearchCustomerTHTel", "Tel/Email"],
     ["tableSearchCustomerTHDispatchClassification", "Dispatch Classification"],
     ["tableSearchCustomerTHAddress", "Address"],
     ["tableSearchTHAgencyCode", "Agency Code"],
     ["tableSearchTHAgencyRepresentative", "Agency Representative Name"],
     ["tableSearchCustomerTHRank", "Rank"],
     ["agencyName", "Enter Agency Name"],
     ["agencyNameKatakana", "Enter Agency Name Katakana"],
     ["agencyBelonging", "Enter Belonging"],
     ["agencyCode", "Enter Agency Code"],
     ["mobilePhone", "Enter Mobile Number"],
     ["mailAddress", "Enter Email Address"],
     ["companyAddress", "Enter Agency Address"],
     ["postalCode", "Enter Postal code"],
     ["selectOptionSelectPrefectures", "Select Prefecture"],
     ["pageOption1Prefecture", "Hokkaido"],
     ["pageOption2Prefecture", "Aomori"],
     ["pageOption3Prefecture", "Iwate"],
     ["pageOption4Prefecture", "Miyagi"],
     ["pageOption5Prefecture", "Akita"],
     ["pageOption6Prefecture", "Yamagata"],
     ["pageOption7Prefecture", "Fukushima"],
     ["pageOption8Prefecture", "Ibaraki"],
     ["pageOption9Prefecture", "Tochigi"],
     ["pageOption10Prefecture", "Gunma"],
     ["pageOption11Prefecture", "Saitama"],
     ["pageOption12Prefecture", "Chiba"],
     ["pageOption13Prefecture", "Tokyo"],
     ["pageOption14Prefecture", "Kanagawa"],
     ["pageOption15Prefecture", "Niigata"],
     ["pageOption16Prefecture", "Toyama"],
     ["pageOption17Prefecture", "Ishikawa"],
     ["pageOption18Prefecture", "Fukui"],
     ["pageOption19Prefecture", "Yamanashi"],
     ["pageOption20Prefecture", "Nagano"], // changed
     ["pageOption21Prefecture", "Gifu"], // changed
     ["pageOption22Prefecture", "Shizuoka"],
     ["pageOption23Prefecture", "Aichi"],
     ["pageOption24Prefecture", "Mie"],
     ["pageOption25Prefecture", "Shiga"],
     ["pageOption26Prefecture", "Kyoto"],
     ["pageOption27Prefecture", "Osaka"],
     ["pageOption28Prefecture", "Hyogo"],
     ["pageOption29Prefecture", "Nara"],
     ["pageOption30Prefecture", "Wakayama"],
     ["pageOption31Prefecture", "Tottori"],
     ["pageOption32Prefecture", "Shimane"],
     ["pageOption33Prefecture", "Okayama"],
     ["pageOption34Prefecture", "Hiroshima"],
     ["pageOption35Prefecture", "Yamaguchi"],
     ["pageOption36Prefecture", "Tokushima"],
     ["pageOption37Prefecture", "Kagawa"],
     ["pageOption38Prefecture", "Ehime"],
     ["pageOption39Prefecture", "Kochi"],
     ["pageOption40Prefecture", "Fukuoka"],
     ["pageOption41Prefecture", "Saga"],
     ["pageOption42Prefecture", "Nagasaki"],//changed
     ["pageOption43Prefecture", "Kumamoto"],
     ["pageOption44Prefecture", "Oita"], // changed
     ["pageOption45Prefecture", "Miyazaki"],
     ["pageOption46Prefecture", "Kagoshima"],
     ["pageOption47Prefecture", "Okinawa"],
     ["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
     ["agencyRepresentativeName", "Enter Agency Representative Name"],
     ["AgencyRepresentativeNameKatakana", "Enter Agency Representative Name Katakana"],
     ["companyOrganizationName", "Enter Organization Name"],
     ["selectOptionSelectCompanyManager", "Select Manager"],
     ["selectOptionSelectRank", "Select Rank"],
     ["buttonSpanCheckAll", "Check All"],
     ["buttonSpanUncheckAll", "Uncheck All"],
     ["buttonSpanBatchDeletion", "Batch Deletion"],
     ["exampleModalCenterTitle", "Batch Deletion"],
     ["modalAreYouSure", "Are You Sure?"],
     ["modalDoYouWantDelete", "Do You Really Want to Delete this Records ?"],
     ["modalProcesCannotBeUndone", "This Process Cannot be Undone."],
     ["tableSearchAgencyNo", "Record No"],
     ["tableSearchAgencyCode", "Agency Code"],
     ["tableSearchAgencyName", "Agency Name"],
     ["tableSearchAgencyRepresentativeName", "Agency Representative Name"],
     ["batchDeleteConfirm", "Confirm"],
     ["batchDeleteClose", "Close"], 
     ["pageSpanbusinessContract", " Out Sourcing"],
     ["pageSpanintroductionDispatching", " Temp -to-Perm"],
     ["pageSpanrecruitment", " Talent Introduction/Recruiting/Placement"],
     ["tableSearchAgencyRepresentativeName", "Agency Representative Name"],
     ["batchDeleteConfirm", "Confirm"],
     ["batchDeleteClose", "Close"], 
                 
 ];

AgencyDetails = [
    ["pageTitleAgencyDetails", "Agency Details"],
    ["pageSpanHeadingAgencyDetails", "Agency Details"],
    ["pageSpanSubHeadingAgencyDetails", "You can view and update an agency details"],
    ["buttonSpanReturn", "Return"],
    ["accordionDivAgencyInformation", "Agency Information"],
    ["pageSpanAgencyName", " Agency Name"],
    ["pageSpanAgencyNameKatakana", "Agency Name Katakana"],
    ["pageSpanRepresentativePosition", "Representative Position"],
    ["pageSpanRepresentativeName", "Representative Name"],
    ["pageLabelContactNumber", "Contact Number"],
    ["pageSpanFaxNumber", "Fax Number"],
    ["pageLabelMailAddress", "Email Address"],
    ["pageSpanAgencyCode", "Agency Code"],
    ["pageSpanDisClassification", "Dispatch Classification"],
    ["pageSpanGeneralDispatch", "General Dispatch"],
    ["pageSpanBusinessContract", "Business Contract"],
    ["pageSpanIntroductionDispatching", "Introduction Dispatching"],
    ["pageSpanRecruitment", "Recruitment"],
	["pageSpanPartTime", "Part Time"],
    ["pageLabelPostalcode", "Postal code"],
    ["btnAddressSearch", "Address Search"],
    ["pageSpanHelpZipCode", "Please enter without hyphens"],
    ["pageSpanPrefecture", "Prefecture"],
    ["pageSpanAddress", "Address"],
    ["pageSpanOrganizationName", "Organization Name"],
    ["pageSpanBillingDeadline", "Billing Deadline"],
    ["pageSpanAgencyContact", "Agency Contact"],
    ["pageSpanAgencyRepresentativeNameKatakana", "Agency Representative Name"],
    ["pageSpanAgencyContactKana", "Agency Representative Name Katakana"],
    ["pageSpanRank", "Rank"],
    ["pageSpanManager", "Manager"],
    ["SelectCompanyManager", "Select Manager"],
    ["pageSpanWebsiteURL", "URL (own website)"],
	["pageSpanBelongned", "Belongned"],
	["pageSpanConflictDate", "Conflict Date"],
    ["pageSpanRemarks", "Remarks"],
    ["buttonUpdateAgencyInformation", "Update Agency Information"],
    ["pageSpanHeadingAgencyRegistration", "Agency Registration"],
    ["pageSpanSubHeadingAgencyRegistration", "You can register as an agency"],
    ["buttonRegisterAgencyInformation", "Register"],
    ["pageTitleAgencyRegistration", "Agency Registration"]
];

AgencyBatchUpload = [
    ["pageSpanHeadingAgencyBatchRegistration", "Agency Batch Registration"],
    ["spanDownloadLink", "Click Here To Download File Upload Template Link"],
    ["buttonUploadFile", "Upload File"],
    ["buttonSpanReturn", "Return"]
	];
	
	
agencyErrorArray = {"E2000":"Cannot be empty",
					"E2001":"Invalid Representative Name",
					"E2002":"Invalid Contact Number",
					"E2003":"Invalid Fax Number",
					"E2004":"Invalid Postal Code",
					"E2005":"Invalid Agency Representative Name",
					"E2006":"Invalid Agency Representative Name Katakana",
					"E2007":"Invalid Agency Contact Number",
					"E2008":"Invalid URL",
					"E2009":"Invalid Email",
					"E2010":"Invalid Agency Code"}