function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(AssignmentManagement);
	convertContentToLanguage(AssignmentDetails);
	convertContentToLanguage(AssignmentForCase);
	convertContentToLanguageByName(nameList);
}

TopMenu = [
	["menuButtonProfile", "Profile"],
	["menuButtonManual", "Manual"],
	["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

nameList = [
	["tableHelptextCustomerName", "Customer Name :"],
	["tableHelptextProjectName", "Project  Name :"],
	["tableHelptextWorkLocation", "Work Location :"],
	["tableHelptextNearestStation", "Nearest Station :"],
	["tableHelptextDispatchClassification", "Dispatch Classification :"],
	["tableHelptextOccupationClassification", "Occupation Classification :"],
	["tableHelptextProjectManager", "Project Manager :"],
	["tableHelptextImplementationDate", "Implementation Date :"],
	["tableHelptextBasicSalary", "Basic Salary :"],
	["tableHelptextStaffPersons", "Staff Persons :"],
	["tableHelptextInHouse", "In-house :"],
	["tableHelptextOutsourcing", "Outsourcing :"],
	["rowTransportationexpenses", "Transportation expenses"],
	["rowPurchaseMoney", "Purchase Money"],
	["rowExpenses", "Expenses"],
	["rowAccommodationFee", "Accommodation Fee"],
];


AssignmentManagement = [
    ["pageTitleAssignmentManagement", "Assignment Management"],
    ["pageTitleAssignmentForImplementationCase", "Assignment For Implementation Case"],
    ["pageTitleAssignmentDetails", "Staff Assignment Details"],
	["pageSpanHeadingAssignmentManagement", "Assignment	Management"],
	["pageSpanAssignmentManagementNote", "You can assign the staff of the staff list to the case selected in the case list."],
	["optionSelectAssignmentClassification", "Select Assignment Classification"],
	["optionSelectAssignmentClassificationAssignByDate", "Assign By Date"],
	["optionSelectAssignmentClassificationAssignByPeriod", "Assign By Period"],
	["pageSpanDataTableNote", "After confirming the assigned staff, select the staff name in the assigned staff column and send the 'Case assignment email '."],
	["tableHelptextCustomerName", "Customer Name :"],
	["tableHelptextProjectName", "Project  Name :"],
	["tableHelptextWorkLocation", "Work Location :"],
	["tableHelptextNearestStation", "Nearest Station :"],
	["tableHelptextDispatchClassification", "Dispatch Classification :"],
	["tableHelptextOccupationClassification", "Occupation Classification :"],
	["tableHelptextProjectManager", "Project Manager :"],
	["tableHelptextImplementationDate", "Implementation Date :"],
	["tableHelptextBasicSalary", "Basic Salary :"],
	["tableHelptextStaffPersons", "Staff Persons :"],
	["tableHelptextInHouse", "In-house :"],
	["tableHelptextOutsourcing", "Outsourcing :"],
	["optionPersonInCharge", "Select Person In Charge"],
	["optionPersonInCharge1", "Person In Charge 1"],
	["optionPersonInCharge2", "Person In Charge 2"],
	["pageSpanSearchCaseList", "Case List"],
	["buttonSpanSwitchToNormalMode", "Switch to Normal Mode"],
	["pageSpanSearch", "Search"],
	["pageLabelAssignmentClassification", "Assignment Classification"],
	["pageLabelProposalNumber", "Case Number"],
	["caseNumber", "Enter Case Number"],
	["pageLabelCustomerName", "Customer Name"],
	["customerName", "Enter Customer Name"],
	["pageLabelImplementationPeriodStart", "Implementation Period (Start)"],
	["pageLabelImplementationPeriodEnd", "Implementation Period End"],
	["pageLabelWorkLocation", "Work Location"],
	["workLocation", "Enter Work Location"],
	["pageLabelDispatchClassification", "Dispatch Classification"],
	["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
	["pageSpanGeneralDispatch", "General dispatch"],
	["pageSpanBusinessContract", "Out Sourcing"],
	["pageSpanIntroductionDispatching", "Temp -to- Perm"],
	["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
	["pageLabelOccupationClassification", "Occupation Classification"],
	["selectOptionSelectOccupationClassification", "Select Occupation Classification"],
	["pageSpanOfficeSystem", "Office system"],
	["pageSpanSalesSystem", "Slaes/sales system"],
	["pageSpanITCreative", "IT / Creative"],
	["pageSpanMedicalWelfareSystem", "Medical / Welfare system"],
	["pageSpanManufacturingBusiness", "Manufacturing business"],
	["pageSpanProfessional", "Professional"],
	["pageSpanOthers", "Others"],
	["pageLabelThePersonInCharge", "The person in charge of the case"],
	["clearAllBtn", "Clear All"],
	["searchBtn", "Search"],
	["pageCardDivTotalAssignments", "Total Number of Assignments"],
	["pageCardDivStaffAssignedAssignments", "Number of Assignments By Date"],
	["pageCardDivOngoingAssignments", "Number of Assignments By Period"],
	["tableSearchTHNo", "No"],
	["tableSearchTHChoice", "Choice"],
	["tableSearchTHCase", "Case"],
	["tableSearchTHWorkInformation", "Work Information"],
	["tableSearchTHAssignStaff", "Assign Staff"],
	["optionAssignmentClassificationSelectAssignment", "Select Assignment Classification"],
	["optionAssignmentClassificationAssignByDate", "Assign By Date"],
	["optionAssignmentClassificationAssignByPeriod", "Assign By Period"],
	["optionPersonInChargeSelectPersonInCharge", "Select Person In Charge of the case"],
	["search_table_info", "No records available"]          
];

AssignmentDetails = [
	["pageSpanHeadingStaffAssignmentDetails", "Staff Assignment Details "],
	["buttonAssignmentManagement", " Assignment	Management"],
	["buttonSpanImplementationInformation", "Implementation Information Details"],
	["pageSpanSubHeadingCaseRegistration", "You can set various notification reports and transportation expenses for the assigned staff."],
	["accordionMatterInformation", "Case information"],
	["pageSpanProjectTitle", "Project Title"],
	["pageSpanAssignmentClassification", "Assignment Classification"],
	["pageSpanDispatchClassification", "Dispatch Classification"],
	["pageSpanOccuClassification", "Occupation Classification"],
	["pageSpanUnitPriceSetting", " Unit Price Setting "],
	["pageSpanBusinessContent", " Business Content"],
	["pageSpanPersonInCharge", " The person in charge of the case"],
	["pageSpanCustomerCompanyName", "Customer Company Name"],
	["accordionImplementationInformation", "Implementation Information"],
	["pageSpanImplementationPeriodStart", "Implementation Date"],
	["pageSpanWorklocation", "Work location"],
	["pageSpanInternalCommunication", "Internal Communication Information (private)"],
	["pageSpanDetailsofImplementation", "Details of Implementation Information (for publication)"],
	["pageSpanRemarks2", "Remarks"],
	["accordionWorkLocationInfo", "Work Location Information"],
	["pageSpanNearestStationTo", " Nearest station to the venue "],
	["pageSpanMeetingPlace", " Meeting place "],
	["pageSpanWorkLocation", " Work Location"],
	["pageSpanWorkAddress", " Work Address(including contact information)"],
	["pageSpanStationArrivalTime", "Station Arrival Time "],
	["pageSpanMeetingTime", "(S) Meeting Time"],
	["pageSpanStartTime", "(S) Start Time"],
	["pageSpanStationEndTime", "(S) End Time"],
	["pageSpanWorkLocationTransportation", "Work Location Transportation "],
	["pageSpanWorkRemarks", "Work remarks"],
	["accordionStaffInformation", "Staff Information"],
	["pageSpanStaffName", "Staff Name"],
	["pageSpanAttributeClassification", "Attribute Classification"],
	["pageSpanSalaryPaymentForm", " Salary Payment Form "],
	["pageSpanStaffMobile", "Staff Mobile"],
	["pageSpanStaffNearestStation", " Staff Nearest Station"],
	["pageSpanScheduled DepartureTime", " (S)Scheduled Departure Time "],
	["btnTransit", "Transit"],
	["pageSpanstaffArraivalText", "Search by arrival at"],
	["pageSpanBasicSalary", "(S) Basic Salary(Daily Salary)"],
	["btnCopyfromDailySalary", "Copy from Daily Salary"],
	["btnCopyfromDailySalaryHelp", "Reference basic salary: ¥"],
	["pageSpanAdvancePayment", "(S) Advance Payment"],
	["pageSpanReasonforPrepayment", "Reason for Prepayment"],
	["pageSpanPrepaidDeliveryDate", "Prepaid Delivery Date"],
	["pageSpanDeductionAmount1", "Deduction Amount 1"],
	["pageSpanResonforDeduction1", "Reason for Deduction"],
	["pageSpanDeductionAmount2", "Deduction Amount 2"],
	["pageSpanResonforDeduction2", "Reason for Deduction"],
	["pageSpanAssignOtherProjects", " Assign other projects"],
	["pageSpanNotificationDate", "Notification Date and Time"],
	["btnSendInterviewRequest", "Send Interview request email"],
	["btnSendMatterAssignment", "Send Matter assignment email"],
	["pageSpanConfirmedTheDayBefore", "Confirmed the day before:"],
	["btnConfirmedTheDayBeforey", "Confirmation Report the Day Before"],
	["pageSpanConfirmedTheDayBeforeConfirmer", "Confirmer:"],
	["btnConfirmedTheDayBeforeConfirmer", "Confirmation of Report the Day Before"],
	["pageSpanDepartureReport", "Departure Report:"],
	["btnDepartureReport", "Departure Report"],
	["pageSpanDepartureReportConfirmer", "Confirmer:"],
	["btnDepartureReportConfirmer", "Departure Report Confirmation"],
	["pageSpanArrivalReport", " Arrival Report:"],
	["btnArrivalReport", "Arrival Report"],
	["pageSpanArrivalReportConfirmer", "Confirmer:"],
	["btnArrivalReportConfirmation", "Arrival Report Confirmation"],
	["pageSpanClosingReport", "Closing Report"],
	["pageSpanClosingReportConfirmer", "Confirmer:"],
	["btnArrivalClosingReportConfirmer", "Closing Report Confirmation"],
	["pageSpanExpenseReport", "Expense Report "],
	["btnExpenseReport", "Expense Report"],
	["pageSpanExpenseReportConfirmer", "Confirmer:"],
	["btnExpenseReportConfirmation", "Expense Report Confirmation"],
	["pageSpanReminderEmail", " Send closing report reminder email: "],
	["btnReminderEmail", "Sending a Reminder Email"],
	["pageSpanWorkingHours", " (S) Working hours"],
	["pageSpanActualWorkingHours", "(S) Actual working hours "],
	["pageSpanActualBreakTime", " (S) Actual break time "],
	["pageSpanMidnightBreakTime", "(S)(Inside) Midnight Break Time "],
	["pageSpanOvertimeHours", " (S) Overtime hours "],
	["pageSpanOvertimeCosts", " Overtime costs"],
	["pageSpanMidnightWorkingHours", "Midnight Working hours"],
	["pageSpanMidnightLaborCosts", " Midnight labor costs "],
	["pageSpanHolidayWorkingHours", " Holiday Working Hours "],
	["pageSpanHolidayLaborCosts", " Holiday	labor costs"],
	["pageSpanOvertimeBillingFee", " Overtime Billing Fee "],
	["pageSpanMidnightLaborBilling", " Midnight labor billing fee "],
	["pageSpanHolidayLaborBilling", " Holiday Labor Billing fee "],
	["pageSpanAdvancePaymentfortable", "Advance Payment "],
	["tableAdvancePaymentNo", "No"],
	["tableAdvancePaymentNominal", "Nominal"],
	["tableAdvancePaymentDetail", "Detail"],
	["tableAdvancePaymentAmountOfMoney", "Amount of money"],
	["tableQuotationDetailsSubtotalTaxable", "Total Advance Payment"],
	["pageSpanAllowance", "Allowance"],
	["tableAdvancePaymentNominalAllowance", "Nominal"],
	["tableAdvancePaymentDetailAllowance", "Detail"],
	["tableAdvancePaymentAmountOfMoneyAllowance", "Amount of money"],
	["tableAllowanceTaxationAllowance", "Taxation"],
	["tableQuotationDetailsSubtotalTaxableAllowance", "Total Allowance"],
	["tableClosingReportPhoto", "Closing Report Photo"],
	["tablePreview", "Preview"],
	["addEducationalRow", "Add New Photo"],
	["pageSpanFinalPreparation", "(S) Final Preparation"],
	["pageSpanRemarks3", "Remarks"],
	["pageSpanInterviewRequest","Interview request email sent:"],
	["pageSpanMatterAssignment","Matter assignment email transmission:"],
	["buttonUpdateAssignStaff", "Update Assign Staff"],
	["pageSpanEnterWorkTimeStart", "Please enter the work start time and end time correctly as they will be referred to in the hourly wage calculation. The input format is '00:00'."],
	["pageSpanBreaketimeSchedule", "If the break time includes the midnight time zone (22: 00-05: 00) , enter it in the midnight break time. Example: If you take a break from 1:00 to 2:00,enter the break time 1:00 and midnight break time 1:00.Example: If you take a break from 21:00 to 22:00, enteronly the break time 1:00"],
	["tableReportFortheStaff", "Report from the staff"],
	["tableConfirmationofthePerson", "Confirmation of the Person in charge"],
	["addRow1", "Add Row"],
	["addRow2", "Add Row"],
	["accordionDailysalaryInformation", "Daily salary Information"],
	["pageSpanIncomeTaxAmount", "Income Tax Amount "],
	["pageSpanPaymentAmount", "Daily salary Information"],
	["btnCalculateSalary", "Calculate Salary information"],
	["pageSpanApprovalStatus", "Approval Status"],
	["optionSelectApprovalStatus", "Select Approval Status"],
	["optionSelectUnapproved", "Unapproved"],
	["optionSelectApproved", "Approved"],
	["assignmentClassificationHelpnote", "If you change to approval and save, the salary will be fixed. Please note that you will not be able to change it."],
	["inputRowTransportationexpenses", "Transportation expenses"],
	["rowPurchaseMoney", "Purchase Money"],
	["rowExpenses", "Expenses"],
	["rowAccommodationFee", "Accommodation Fee"],
];

AssignmentForCase = [
     ["pageSpanHeadingAssignmentForImplementationCase", "Assignment For Implementation Case"],
     ["buttonSpanReturn", "Return"],
     ["accordionMatterInformation", "Case information"],
     ["pageSpanProjectTitle", "Case Name"],
     ["pageSpanMatterNumber", "Case number"],
     ["pageSpanQuotationNumber", "Quotation number"],
     ["pageSpanAssignmentClassification", "Assignment Classification"],
     ["assignmentClassificationHelp", "Assign by period is recommended for long-term projects of 1 month or more"],
     ["pageSpanDispatchClassification", "Dispatch Classification"],
     ["pageSpanDivisionByBusiness", "Division by Business"],
     ["pageSpanOccuClassification", "Occupation Classification"],
     ["pageSpanBusinessContent", " Business content and degree of responsibility "],
     ["pageSpanRequiredNumberPeople", "Required number of people"],
     ["pageSpanPersonInCharge", " The person in charge of the case"],
     ["pageSpanSalesRepresentative", " Sales Representative"],
     ["pageSpanCustomerCompanyName", "Customer company name"],
     ["pageSpanCustomerRepresentativeName", "Customer Representative Name"],
     ["pageSpanNameofDispatcher", " Name of dispatcher "],
     ["pageSpanContacInformationOfDispatcher", "Contact information of dispatcher"],
     ["pageSpanNameOfDispatcherGrievance", "Name of dispatcher grievance handler"],
     ["pageSpanContactInfoDispatcherGrievance", "Contact information for the dispatcher's grievance handler "],
     ["pageSpanCommanderName", "Commander Name"],
     ["pageSpanCommanderContact", "Commander Contact "],
     ["pageSpanOfficerName", "Officer name"],
     ["pageSpanResponsibleContact", "Responsible contact"],
     ["pageSpanComplaintContactName", "Complaint contact name "],
     ["pageSpanComplaintContactInformation", "Complaint contact information"],
     ["pageSpanEmploymentStatus", "Whether it is permanent employment or fixed-term employment and whether or not it is a dispatched worker subject to the agreement"],
     ["optionEmploymentStatusFixedTermEmploymentWorker", "Fixed-Term Employment Worker"],
     ["optionEmploymentStatusFixedTermEmploymentWorkerDispatched", "Fixed-Term Employment Workers(Dispatched workers subject to the agreement)"],
     ["optionEmploymentStatusPermanentWorker", "Permanent Worker"],
     ["optionEmploymentStatusPermanentWorkerDispatched", "Permanent Employment Workers(Dispatched workers subject to the agreement)"],
     ["pageSpanAgeStatus", " Whether or not you are over 60 years old "],
     ["optionAgeStatusLimitedOver60", "Limited to over 60 years old"],
     ["optionAgeStatusNotLimitedOver60", "Not Limited to over 60 years old"],
     ["pageSpanPeriodStart", "Implementation Period (Start)"],
     ["pageSpanPeriodEnd", "Implementation Period (End)"],
     ["accordionImplementationInformation", "Implementation Information"],
     ["pageSpanImplementationPeriodStart", "(S)Implementation Period (Start)"],
     ["pageSpanImplementationPeriodEnd", "(S)Implementation Period (End)"],
     ["pageSpanImplementationDate", " (S)Implementation date"],
     ["pageSpanWorkingDays", "Working days"],
     ["pageSpanWorkingDaysSunday", "Sunday"],
     ["pageSpanWorkingDaysMonday", "Monday"],
     ["pageSpanWorkingDaysTuesday", "Tuesday"],
     ["pageSpanWorkingDaysWednesday", "Wednesday"],
     ["pageSpanWorkingDaysThursday", "Thursday"],
     ["pageSpanWorkingDaysFriday", "Friday"],
     ["pageSpanWorkingDaysSaturday", "Saturday"],
     ["pageSpanHolidays", "Holidays"],
     ["pageSpanHolidaySunday", "Sunday"],
     ["pageSpanHolidayMonday", "Monday"],
     ["pageSpanHolidayTuesday", "Tuesday"],
     ["pageSpanHolidayWednesday", "Wednesday"],
     ["pageSpanHolidayThursday", "Thursday"],
     ["pageSpanHolidayFriday", "Friday"],
     ["pageSpanHolidaySaturday", "Saturday"],
     ["pageSpanInternalCommunication", "Internal communication information (private)"],
     ["pageSpanDetailsOfImplementation", " (S)Details of implementation information (for publication) "],
     ["buttonAssignStaff", "Assign Staff"],
	 ["tableSearchTHOperation", "Operation"],
     ["accordionWorkLocationInfo", "Work Location Information"],
     ["pageSpanNearestStationTo", " (S) Nearest station to the venue "],
     ["pageSpanMeetingPlace", " (S) Meeting place "],
     ["pageSpanOfficeName", "Office Name"],
     ["pageSpanOrganizationName", "Organization name"],
     ["pageSpanWorkLocation", " (S) Work Location "],
     ["pageSpanWorkAddress", "(S) Work Address (including contact information)"],
     ["pageSpanSalaryUnitPrice", "Salary unit price"],
     ["pageSpanProjectUnitPrice", "Project unit price"],
     ["pageSpanStaffUnitPrice", "Staff unit price"],
     ["pageSpanBasicSalary", "Basic Salary (hourly wage)"],
     ["pageSpanBilledAmount", "Billed Amount(for 1 person, hourly wage)"],
     ["pageSpanBillingUnitPriceSetting", "Billing Unit Price Setting"],
     ["billingUnitPriceSettingDailySalary", "Daily Salary"],
     ["billingUnitPriceSettingHourlyWage", "Hourly Wage"],
     ["billingUnitPriceSettingFullMonthlySalary", "Full Monthly Salary"],
     ["billingUnitPriceSettingDailySalaryMonthly", "Daily Salary Monthly Salary"],
     ["pageSpanWorkLocationTransportation", "Work Location Transportation "],
     ["pageSpanStationArrivalTime", "Station Arrival Time "],
     ["pageSpanStationMeetingTime", "Meeting Time "],
     ["pageSpanStationScheduledStartTime", "Scheduled Start Time "],
     ["pageSpanStationScheduledEndTime", "Scheduled End Time "],
     ["pageSpanStationScheduledActualWorkTime", "Scheduled actual work time "],
     ["pageSpanScheduleBreaktimeTime", "Scheduled break time "],
     ["pageSpanDepartureTime", "Scheduled departure time "],
     ["pageSpanMidnightBreakingTime", "(Inside) Scheduled midnight break time "],
     ["pageSpanStationDescriptionTime", "Scheduled start and end times are references for hourly wage calculation. Input correctly. If the scheduled break time includes the midnight time zone (22: 00-05: 00), enter it in the (inside) midnight break scheduled time. If the scheduled actual work time is not entered, the overtime, midnight work, and holiday work hours will not be calculated correctly and will not be calculated automatically. "],
     ["pageSpanWorkRemarks", "(S) Work remarks(break time, etc.) "],
     ["pageSpanOvertimePaymentUnit", "Overtime payment unit"],
     ["accordionNotificationOfWorkingConditions", "Notification of working conditions and explicit information on working conditions"],
     ["pageSpanWorkRemarksNote", "It is applied to the notification of working conditions and the statement of working conditions. Please fill in within the range stipulated by law. "],
     ["pageSpanmidnightOvertimeHolidayAllowance", "Midnight / overtime / holiday allowance "],
     ["pageSpanPaymentTerms", "Payment terms"],
     ["pageSpanAnnualPaidLeave", " Annual paid leave"],
     ["pageSpanOvertimeHolidayWork", " Overtime / holiday work "],
     ["pageSpanSafetyAndHygiene", " Safety and hygiene "],
     ["pageSpanEmploymentStabilizationMeasures", "Employment stabilization measures for dispatched workers taken by canceling the dispatch contract "],
     ["pageSpanGrievanceRelatedMatters", "Grievance related matters "],
     ["pageSpanReasonForNotSubmittingEmployment", "Reason for not submitting employment / social insurance insured qualification notification"],
     ["pageSpanUseOfWelfareFacilities", " Use of welfare facilities, etc."],
     ["pageSpanRetirementRelatedMatters", "Retirement related matters"],
     ["pageSpanContractRenewalRelated", "Contract renewal related matters"],
     ["pageSpanConflictPreventionMeasures", "Conflict prevention measures for direct employment of dispatched workers"],
     ["pageSpanRemarks1", " Remarks"],
     ["accordionDivAssignmentInformation", "Assignment Information"],
     ["pageSpanRequiredNumberOfStaff", "Required number of staff "],
     ["buttonAssignmentManagement", "Assignment Management"],
     ["#tableAssignmentInformationTHNo", "No"],
     ["#tableAssignmentInformationTHAssignStaff", "Assign Staff"],
     ["#tableAssignmentInformationTHConflictDate", "Conflict date (individual unit)"],
     ["#tableAssignmentInformationTHNotification", "Notification date and time"],
     ["#tableAssignmentInformationTHAssignOtherProjects", "Assign other projects"],
     ["addSkillSheetRow", "Add Row"],
     ["pageSpanInvoiceCreation", "Invoice creation"],
     ["pageSpanAssignmentRemarks", "Remarks"],
	 ["pageSpanAfterConfirmationNote", "After confirming the assigned staff, select the staff name in the assigned staff column and send the 'Case assignment email'."],
     ["buttonUpdateAssignmentInfo", "Update Implementation Information"] , 
     ["optionOvertimePaymentUnitDaily", "Daily"] , 
     ["loadPageSpanApprovalStatus", "Approval Status"] , 
     ["loadPageSpanApprovalStatusApprovedValue", "Approved"] ,
     ["spanSalaryPaymentCheckboxPaidText", "Paid"] , 
     ["btnCancelSalaryApproval", "Cancel Salary Approval"] , 
     ["exampleModalLabel", "Search Staff and Assign"] , 
     ["pageSpanStaffList", "Staff List"] , 
     ["pageLabelBelongs", "Belongs"] , 
     ["belongs", "Enter Belongs"] , 
     ["pageLabelStaffName", "Staff Name"] , 
     ["staffName", "Enter Staff Name"] , 
     ["staffGender", "Gender"] , 
     ["optionSelectGender", "Select Gender"] , 
     ["optionMale", "Male"] , 
     ["optionFemale", "Female"], 
     ["pageOption0Prefecture", "Select Prefecture"],
     ["pageOption1Prefecture", "Hokkaido"],
     ["pageOption2Prefecture", "Aomori"],
     ["pageOption3Prefecture", "Iwate"],
     ["pageOption4Prefecture", "Miyagi"],
     ["pageOption5Prefecture", "Akita"],
     ["pageOption6Prefecture", "Yamagata"],
     ["pageOption7Prefecture", "Fukushima"],
     ["pageOption8Prefecture", "Ibaraki"],
     ["pageOption9Prefecture", "Tochigi"],
     ["pageOption10Prefecture", "Gunma"],
     ["pageOption11Prefecture", "Saitama"],
     ["pageOption12Prefecture", "Chiba"],
     ["pageOption13Prefecture", "Tokyo"],
     ["pageOption14Prefecture", "Kanagawa"],
     ["pageOption15Prefecture", "Niigata"],
     ["pageOption16Prefecture", "Toyama"],
     ["pageOption17Prefecture", "Ishikawa"],
     ["pageOption18Prefecture", "Fukui"],
     ["pageOption19Prefecture", "Yamanashi"],
     ["pageOption20Prefecture", "Nagano"], // changed
     ["pageOption21Prefecture", "Gifu"], // changed
     ["pageOption22Prefecture", "Shizuoka"],
     ["pageOption23Prefecture", "Aichi"],
     ["pageOption24Prefecture", "Mie"],
     ["pageOption25Prefecture", "Shiga"],
     ["pageOption26Prefecture", "Kyoto"],
     ["pageOption27Prefecture", "Osaka"],
     ["pageOption28Prefecture", "Hyogo"],
     ["pageOption29Prefecture", "Nara"],
     ["pageOption30Prefecture", "Wakayama"],
     ["pageOption31Prefecture", "Tottori"],
     ["pageOption32Prefecture", "Shimane"],
     ["pageOption33Prefecture", "Okayama"],
     ["pageOption34Prefecture", "Hiroshima"],
     ["pageOption35Prefecture", "Yamaguchi"],
     ["pageOption36Prefecture", "Tokushima"],
     ["pageOption37Prefecture", "Kagawa"],
     ["pageOption38Prefecture", "Ehime"],
     ["pageOption39Prefecture", "Kochi"],
     ["pageOption40Prefecture", "Fukuoka"],
     ["pageOption41Prefecture", "Saga"],
     ["pageOption42Prefecture", "Nagasaki"],//changed
     ["pageOption43Prefecture", "Kumamoto"],
     ["pageOption44Prefecture", "Oita"], // changed
     ["pageOption45Prefecture", "Miyazaki"],
     ["pageOption46Prefecture", "Kagoshima"],
     ["pageOption47Prefecture", "Okinawa"],
     ["pageLabelPrefectures", " Prefectures"] , 
     ["pageLabelExperience", "Experience"] , 
     ["experience", "Enter Experience"] , 
     ["pageLabelStaffStaff", "In Charge Staff"] , 
     ["selectInchargeStaff", "Select In Charge Staff"] , 
     ["pageLabelAddress", "Address"] , 
     ["address", "Enter Address"] , 
     ["pageSpanAttributeclassification1", "Attribute Classification"] , 
     ["pageOption0AttributeClassification1", "Select Attribute classification"] , 
     ["pageOption1AttributeClassification1", "Inhouse"] , 
     ["pageOption2AttributeClassification1", "Out Sourcing"] , 
     ["pageLabelAttribute", "Attribute"] , 
     ["pageOption0Attribute", "Select Attribute"] , 
     ["pageOption1Attribute", "Elderly"] , 
     ["pageOption2Attribute", "Foreign Student"] , 
     ["pageOption3Attribute", "Foreign worker"] , 
     ["pageOption4Attribute", "Highschooler"] ,
     ["pageLabelDateofbirthFrom", "Date of birth From"] , 
     ["ImplementationPeriodEnd", "Date of birth To"] ,
     ["pageLabelSalaryPaymentForm", "Salary payment form"] , 
     ["selectSalaryPaymentForm", "Select Salary Payment Form"] ,
     ["selectDaily", "Daily/Weekly Payment"] ,
     ["selectMonthly", "Monthly Payment"] ,
     ["pageLabelQualification", "Qualification"] , 
     ["qualification", "Enter Qualification"] ,
     ["pageLabelRegistrationDivision", "Registration Division"] , 
     ["selectOptionSelectRegistrationDevision", "Select Registration Division"] ,
     ["selectOptionSelectRegistrationDevision1", " Temporary registration"] , 
     ["selectOptionSelectRegistrationDevision2", "Main registration"] ,
     ["pageSpanSearchTargetStaff", "Target Staff"] , 
     ["tableSearchTHStaff", "Staff"] ,
     ["tableSearchTHDispatchClassification", "Dispatch /occupation/ affiliation"] , 
     ["tableSearchTHExperience", "Experience / Shift remarks"] ,
     ["tableSearchTHPrefecture", "Prefecture / Address / Nearest station"] , 
     ["tableSearchTHAssignOther", "Assign other projects"] ,
     ["btnTemporarilyAddSelectedStaff", "Temporarily add selected staff"] , 
    
        
];

assignmentErrorArray ={ 
	"E2050":"Cannot be empty!",
	"E2051":"Invalid Case Number",
	"E2052":"Invalid Customer Name",
	"E2053":"Implementation Periods do not match",
	"E2054":"Dates Of Birth do not match",
	"E2055":"Invalid Basic Salary (Daily Salary)",
	"E2056":"Invalid Advance Payment",
	"E2057":"Invalid Deduction Amount 1",
	"E2058":"Invalid Deduction Amount 2",
	"E2059":"Working Hours do not match",
	"E2060":"Invalid Overtime Cost",
	"E2061":"Invalid Midnight labor costs",
	"E2062":"Invalid Holiday labor costs",
	"E2063":"Invalid Overtime Billing Fee",
	"E2064":"Invalid Midnight Labor Billing Fee",
	"E2065":"Invalid Holiday Labor Billing Fee",
	"E2066":"Allowance info is Not Valid.  All the columns of a row should be filled",
	"E2067":"Amount of money is not valid",
	"E2068":"Only jpg/jpeg and png files are allowed",
	"E2069":"Please enter time duration in hh:mm format",
	"E2070":"(Inside) Midnight Break Time can't be greater than Actual Break Time",
}

