function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(attendenceManagement);
    convertTitleToLanguageByName(nameList);
}

TopMenu = [
	["menuButtonProfile", "Profile"],
	["menuButtonManual", "Manual"],
	["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

attendenceManagement =[
		["pageTitle","Staff Assignment List"],
		["pageSpanHeading","Staff Assignment List"],
		["buttonSpanStaffListCSV","Assignment List CSV Output"],
		["TitleHelpStaffAssignmentList","You can check the staff status on the specified implementation date and check various notifications. In the case of recruitment, please enter the recruitment period for the implementation period."],
		["pageSpanSearch","Search"],
		["pageLabelAssignmentClassification","Assignment Classification"],
		["selectOptionAssignmentClassification","Select Assignment Classification"],
		["pageOptionAssignbyDate","Assign by date"],
		["pageOptionAssignbyPeriod","Assign by period"],
		["pageLabelProjectTitle","Project Title"],
		["pageLabelStaffCode","Staff Code"],
		//["pageLabelImplementationDateFrom","Implementation Date From"],
		["pageLabelDispatchClassification","Dispatch Classification"],
		["selectOptionSelectdispatchClassification","Select Dispatch Classification"],
		["pageOption1Generaldispatch","General dispatch"],
		["pageOption2Businesscontract","Business contract"],
		["pageOption3IntroductionDispatching","Introduction Dispatching"],
		["pageOption4Recruitment","Recruitment"],
		["pageLabelWorkLocation","Work Location"],
		["pageLabelStaffName","Staff Name"],
		["pageLabelImplementationDateTo","Implementation Date To"],
		["pageLabelAffiliation","Affiliation"],
		["pageLabelCustomerName","Customer Name"],
		["pageLabelStaffstaff","Staff staff"],
		["option0staffStaff","Select Staff"],
		//["option1staffStaffAbraham","Abraham"],
		//["option1staffStaffSales","Sales A"],
		//["option2staffStaffAccounting","Accounting 1"],
		["pageLabelScheduleddeparturetime","Scheduled departure time"],
		["spanNoDepartureReport","No Departure Report"],
		["spanDepartureReportDelay","Departure Report Delay"],
		["pageLabelStatus","Status"],
		["spanOpportunityAllocation","Opportunity allocation"],
		["spanInterviewRequestEmail","Interview request email"],
		["spanMatterAssignmentEmail","Matter assignment email"],
		["spanReporttheDayBefore","Report the day before"],
		["spanDepartureReport","Departure report"],
		["spanArrivalReport","Arrival report"],
		["spanClosingReport","Closing report"],
		["spanExpenseReport","Expense report"],
		["spanAbsenceReport","Absence report"],
		["clearAllBtn","Clear All"],
		["searchBtn","Search"],
		["selectOptionReportDayBefore","Report the day before"],
		["selectOptionDepartureReport","Departure report"],
		["selectOptionArrivalReport","Arrival report"],
		["selectOptionClosingReport","Closing report"],
		["selectOptionExpenseReport","Expense report"],
		["selectOptionAbsenceReport","Absence report"],
		//["batchChangeofStatusBtn","Batch change of status"],
		["pageSpanSearchStaffDetails","Search Staff Assignment Details"],
		["tableSearchStaffTHNo","No"],
		["tableSearchStaffTHChoice","Choice"],
		["tableSearchStaffTHWorkLocation","Item / Work location"],
		["tableSearchStaffTHCustomerName","Customer Name"],
		["tableSearchStaffTHDispatchClassification","Dispatch classification"],
		["tableSearchStaffTHImplementationDate","Implementation date"],
		["tableSearchStaffTHScheduledDepartureTime","Scheduled departure time"],
		["tableSearchStaffTHAssignStaff","Assign staff"],
		["tableSearchStaffTHStaffStaff","Staff staff"],
		["tableSearchStaffTHUpdatedRegularly","State"],
		["tableCheck","Updated regularly"],
		["buttonSpanCheckAll","Check All"],
		["buttonSpanUncheckAll","Uncheck All"],
		["exampleModalCenterTitle","Batch Deletion"],
		["modalH4AreYouSure","Are You Sure?"],
		["modalH4ReallyWantToDelete","Do You Really Want to Delete this Records ?"],
		["modalH4CannotBeUndone","This Process Cannot be Undone."],
		["tableModalSearchStaffTHNo","Record No"],
		["tableModalSearchStaffTHName","Name"],
		["tableModalSearchStaffTHNameKatakana","Name Katakana"],
		["tableModalSearchStaffTHStaffCode","Staff Code"],
		["batchDeleteConfirm","Confirm"],
		["batchDeleteClose","Close"],
		["pageLabelPrefectures","Implementation Date From"],
		["projectTitle","Enter Project Title"],
		["workLocation","Enter Work Location"],
		["affiliation","Enter Affiliation"],
		["customerName","Enter Customer Name"],
		["staffCode","Enter Staff Code"],
		["staffName","Enter Staff Name"],
		["buttonChangeStatus","Batch change of status"],
		["selectInchargeofStaff","Select InCharge Staff"],
];

nameList = [
		["tableHelptextProjectName", "Project Name :"],
		["tableHelptextWorkLocation", "Work Location :"],
		["tableHelptextScheduleDate", "Schedule Date :"],
		["tableHelptextScheduleTime", "Schedule Time :"],
		["tableHelptextMeetingTime", "(Meeting "],
		["HelptextExpenseReport", " Expense report "],
		["tableHelptextconfirmedText", "confirmed"],
		["tableHelptextOvertimeHours", "Schedule Time :"],
		["HelptextOpportunityAllocation", "Opportunity allocation"],
		["HelptextInterviewRequestEmail", "Interview request email"],
		["HelptextMatterAssignmentEmail", "Matter assignment email"],
		["HelptextReportDayBefore", "Report the day before"],
		["HelptextDepartureReport", "Departure report"],
		["HelptextArrivalReport", "Arrival report"],
		["HelptextClosingReport", "Closing report"],
		["HelptextAbsenceReport", "Absence report"],
];


attendanceErrorArray ={"E2120":"Invalid Customer Name",
					   "E2121":"Invalid Staff Code",
					   "E2122":"Invalid Staff Name",
					   "E2123":"Implementation Dates do not match",	
					   "E2124":"Cannot be empty",	
					   "E2125":"Please select a Attendance Status",
 				  		}




