function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(CaseManagement);
    convertContentToLanguage(CaseRegistation);
    convertContentToLanguage(CaseImplementation);
    convertTitleToLanguageByName(TitleList);

}

TopMenu = [
 
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

TitleList = [
["viewDetails", "View Details"],
];

CaseManagement = [
    ["pageTitleCaseList", "Case List"],
	["pageSpanHeadingCaseList", "Case List"],
	["buttonSpanCreateACase", "Create a Case"],
	["fromACustomer", "Create a Case from a Customer"],
	["fromAQuote", " Create a Case from a Quote"],
	["buttonSpanImportExistingProject", "Import Existing Project Data"],
	["buttonSpanOutputMatterList", "Output Case List CSV"],
	["pageSpanSearch", "Search"],
	["pageLabelProposalNumber", "Case Number"],
	["pageLabelQuotationNumber", "Quotation Number"],
	["pageLabelProjectTitle", "Project Title"],
	["pageLabelCustomerCompanyName", "Customer Company Name"],
	["pageLabelCustomerRepresentativeName", "Customer Representative Name"],
	["pageLabelThePersonInCharge", "The person in charge of the case"],
	["pageLabelAssignmentClassification", "Assignment Classification"],
	["pageLabelDispatchClassification", "Dispatch Classification"],
	["pageLabelOccupationClassification", "Occupation Classification"],
	["pageLabelImplementationPeriodStart", "Implementation Period (Start)"],
	["pageLabelImplementationPeriodEnd", "Implementation Period (End)"],
	["pageLabelProposalDisclosure", "Proposal Disclosure"],
	["pageLabelConflictDateFrom", "Conflict Date From"],
	["pageLabelConflictDateTo", " Conflict Date To"],
	["pageLabelAffiliation", "Belonging"],
	["clearAllBtn", "Clear All"],
	["searchBtn", "Search"],
	["pageCardDivTotalCases", "Total Number of Cases"],
	["pageCardDivTotalOngoingCases", "Total Ongoing Cases"],
	["pageCardDivTotalUpcomingCases", "Total Upcoming Cases"],
	["pageCardDivTotalCompleteCases", "Total Complete Cases"],
	["pageSpanSearchCaseDetails", "Search Case Details"],
	["tableSearchTHNo", "No"],
	["tableSearchTHChoice", "Choice"],
	["tableSearchTHProposalNumber", "Proposal Number"],
	["tableSearchTHQuotationNumber", "Quotation Number"],
	["tableSearchTHCase", "Case"],
	["tableSearchTHDispatchClassification", "Dispatch Classification"],
	["tableSearchTHOccupationClassification", "Occupation Classification"],
	["tableSearchTHImplementationPeriod", "Implementation period"],
	["tableSearchTHCustomerCompanyName", "Customer Company Name"],
	["tableSearchTHCustomerRepresentativeName", "Customer Representative Name"],
	["tableSearchTHCaseManager", "Person in charge of the Case"],
	["tableSearchTHProposalDisclosure", "Proposal Disclosure"],
	["search_table_info", "No records available"],
	["buttonSpanCheckAll", "Check All"],
	["buttonSpanBatchDeletion", "Batch Deletion"],
	["buttonSpanCheckAll", "Check All"],
	["buttonSpanCheckAll", "Check All"],
	["buttonSpanUncheckAll", "Uncheck All"],
	["caseNumber", "Enter Case Number"],
	["quotationNumber", "Enter Quotation Number"],
	["projectTitle", "Enter Project Title"],
	["customerCompanyName", "Enter Customer Company Name"],
	["customerRepresentativeName", "Enter Customer Representative Name"],
	["pageLabelCustomerRepresentativeName", "Customer Representative Name"],
	["affiliation", "Enter Belonging"],
	["pelectPersonInChargeCase", "Select Person In Charge of the case"],
	["personInCharge1", "Person In Charge 1"],
	["personInCharge2", "Person In Charge 2"],
	["selectAssignment", "Select Assignment Classification"],
	["assignByDate", "Assign By Date"],
	["assignByPeriod", "Assign By Period"],
	["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
	["pageSpanGeneralDispatch", "General dispatch"],
	["pageSpanBusinessContract", "Out Sourcing"],
	["pageSpanIntroductionDispatching", "Temp-to- Perm"],
	["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
	["selectOptionSelectOccupationClassification", "Select Occupation Classification"],
	["pageSpanOfficeSystem", "Office system"],
	["pageSpanSalesSystem", "Slaes/sales system"],
	["pageSpanITCreative", "IT/ Creative"],
	["pageSpanMedicalWelfareSystem", "Medical / Welfare system"],
	["pageSpanManufacturingBusiness", "Manufacturing business"],
	["pageSpanProfessional", "Professional"],
	["pageSpanOthers", "Others"],
	["optionSelectProposalDisclosure", "Select Proposal Disclosure"],
	["optionRelease", "Release"],
	["optionPrivate", "Private"]
	          
];

CaseRegistation = [
	["pageTitleCaseDetails", "Case Details"],
	["pageTitleCaseRegistration", "Case Registration"],
    ["pageSpanHeadingCaseDetails", "Case Details"],
	["pageSpanHeadingCaseRegistration", "Case Registration"],
	["buttonSpanCreateMatter", "Create from this Case"],
	["dropdownCreateAnotherCase", "Copy and Create Another Case"],
	["dropdownInvoiceCreation", "Invoice Creation"],
	["buttonSpanCreateFromThisCustomer", "Reports"],
	["workerDispatchIndividual", "Worker Dispatch Individual Contract Output"],
	["dispatchSourceManagement", "Dispatch source management ledger output"],
	["dispatchdestinationManagement", "Dispatch destination management ledger output"],
	["dispatchOutputofworking", "Output of working condition notification and working condition "],
	["creationofdispatch", "Creation of dispatch notice "],
	["buttonSpanCaseDelete", "Delete"],
	["buttonValueSpanCaseDelete", "Delete Case"],
	["buttonSpanReturn", "Return"],
	["pageSpanSubHeadingCaseRegistration", "You can modify the case and create an invoice related to this case. Information for each implementation date will be provided on the implementation information details screen."],
	["accordionCaseIntelligence", "Case Information"],
	["pageSpanCaseName", "(S) Case name"],
	["pageSpanMatterNumber", "Case number"],
	["pageSpanQuotationNumber", " Quotation number"],
	["pageSpanAssignmentClassification", "Assignment Classification"],
	["optionSelectAssignmentClassification", "Select Assignment Classification"],
	["optionSelectAssignmentClassificationAssignByDate", "Assign By Date"],
	["optionSelectAssignmentClassificationAssignByPeriod", "Assign By Period"],
	["pageSpanDispatchClassification", "Dispatch Classification"],
	["optionDispatchClassification", "Select Dispatch Classification"],
	["optionDispatchClassificationGeneralDispatch", "General Dispatch"],
	["optionDispatchClassificationBusinessContract", "Out Sourcing"],
	["optionDispatchClassificationIntroductionDispatching", "Introduction Dispatching"],
	["optionDispatchClassificationRecruitment", "Recruitment"],
	["optionDispatchClassificationPartTime", "Part Time"],
	["pageSpanDivisionByBusiness", "Division by Business"],
	["pageSpanOccuClassification", "Occupation Classification"],
	["pageSpanOfficeSystem", "Office System"],
	["pageSpanSalesSystem", "Sales / Sales System"],
	["pageSpanITCreative", "IT / Creative"],
	["pageSpanMedicalWelfareSystem", "Medical / welfare system"],
	["pageSpanManufacturingBusiness", "Manufacturing Business"],
	["pageSpanProfessional", "Professional"],
	["pageSpanOthers", "Others"],
	["pageSpanItemUnitPrice", "Case unit price setting "],
	["optionSelectCaseUnitPriceSetting", "Select Case unit price setting"],
	["optionSelectCaseUnitPriceSettingDailySalary", "Daily Salary"],
	["optionSelectCaseUnitPriceSettingHourlyWage", "Hourly Wage"],
	["optionSelectCaseUnitPriceSettingFullMonthlySalary", "Full Monthly Salary"],
	["optionSelectCaseUnitPriceSettingDaytoMonth", "Day to month"],
	["pageSpanWorklocation", " Work location"],
	["pageSpanRequiredQualifications", "Required qualifications"],
	["pageSpanRequiredNumberPeople", "Required number of people"],
	["pageSpanImplementationPeriodStart", "(S)Implementation Period (Start)"],
	["pageSpanImplementationPeriodEnd", "(S)Implementation Period (End)"],
	["pageSpanBusinessContent", "Business Content"],
	["pageSpanWorkLocation", " Work Location"],
	["pageSpanApplicationQualifications", "Application qualifications"],
	["pageSpanRecruitmentPeriodStart", "Recruitment period (start)"],
	["pageSpanRecruitmentPeriodEnd", "Recruitment period (end)"],
	["pageSpanWorkingHoursStartRecruitment", "Working Hours (Start)"],
	["pageSpanWorkingHoursEndRecruitment", "Working Hours (End)"],
	["pageSpanSalary", "Salary"],
	["pageSpanTreatment", "Treatment"],
	["pageSpanHoliday", "Holiday"],
	["pageSpanNumberOfHires", "Number of Hires"],
	["pageSpanRecruitmentProcess", "Recruitment Process"],
	["pageSpanRecruiterComments", "Recruiter Comments"],
	["pageSpanConflictDateBUnit", " Conflict date (business unit)"],
	["pageSpanPersonInCharge", " The person in charge of the case"],
	["pageSpanSalesRepresentative", " Sales Representative"],
	["selectSalesRepresentative", "Select Sales Representative"],
	["selectSalesRepresentative1", "Sales Representative 1"],
	["selectSalesRepresentative2", "Sales Representative 2"],
	["pageSpanCustomerCompanyName", "Customer company name"],
	["pageSpanCustomerRepresentativeName", "Customer Representative Name"],
	["pageSpanAssignmentDeadline", "Assignment deadline"],
	["pageSpanBusinessrelatedMaterials", "Business-Related materials"],
	["buttonAssNew", "Add New File"],
	["pageSpanCaseOpen", "Case open"],
	["pageSpanCaseOpenHelp", " Publish the project and recruit staff"],
	["pageSpanRemarks", "Remarks"],
	["pageSpanDetailedInformationPractice", "(S) Detailed information about the practice (for public use) "],
	["buttonUpdateCase", "Update Case Information"],
	["buttonSaveCase", "Save Case Information"],
	["accordionDivListofImplementationDates", "List of implementation dates"],
	["tableAssignmentInformationTHNo", "No"],
	["tableAssignmentInformationTHAssignStaff", "Duplicate selection"],
	["tableAssignmentInformationTHNo1", "Implementation period Invoice creation"],
	["tableAssignmentInformationTHNo2", "Work location"],
	["tableAssignmentInformationTHNo3", "Assembly time"],
	["tableAssignmentInformationTHNo4", "Starting time"],
	["tableAssignmentInformationTHNo5", "Ending time"],
	["tableAssignmentInformationTHNo6", "Required number of people"],
	["buttonImplementationInformationDuplicate", "Duplicate the selected implementation date"],
	["buttonImplementationInformationBatchUpdate", "Implementation information batch update"],
	["buttonImplementationInformation", "Add Implementation Information"],
	["buttonSaveAssignmentInfo", "Save Assignment Information"],
	["buttonUpdateAssignmentInfo", "Update Assignment Information"],

["pageTitleCaseImplementInfo", "Case Implementation Information"],
["pageSpanHeadingDetailsofImplementation", "Details	of Implementation Information"],
["buttonSpanDelete", "Delete"],
["buttonSpanReturn", "Return"],
["pageSpanSubHeadingCaseRegistration", "You can set the shift for each implementation date. Staff assignments are made on the assignment management screen, and settings for each staff are made on the assignment staff details screen."],
["accordionMatterInformation", "Case information"],
["pageSpanProjectTitle", "Case Name"],
["pageSpanMatterNumber", "Case number"],
["pageSpanQuotationNumber", " Quotation number"],
["pageSpanAssignmentClassification", "Assignment Classification"],
["assignmentClassificationHelp", "Assign by period is recommended for long-term projects of 1 month or more"],
["pageSpanDispatchClassification", "Dispatch Classification"],
["pageSpanDivisionByBusiness", "Division by Business"],
["pageSpanOccuClassification", "Occupation Classification"],
["pageSpanBusinessContentDegree", " Business content and degree of responsibility "],
["pageSpanRequiredNumberPeople", "Required number of people"],
["pageSpanPersonInCharge", " The person in charge of the case"],
["optionPersonInCharge", "Select Person In Charge of the case"],
["optionPersonInCharge1", "Person In Charge 1"],
["optionPersonInCharge2", "Person In Charge 2"],
["pageSpanSalesRepresentative", " Sales Representative"],
["pageSpanCustomerCompanyName", "Customer company name"],
["pageSpanCustomerRepresentativeName", "Customer Representative Name"],
["pageSpanNameofDispatcher", " Name of dispatcher "],
["pageSpanContacInformationOfDispatcher", "Contact information of dispatcher"],
["pageSpanNameOfDispatcherGrievance", "Name of dispatcher grievance handler "],
["pageSpanContactInfoDispatcherGrievance", "Contact information for the dispatcher's grievance handler "],
["pageSpanCommanderName", "Commander Name"],
["pageSpanCommanderContact", "Commander Contact "],
["pageSpanOfficerName", " Officer name "],
["pageSpanResponsibleContact", "Responsible contact"],
["pageSpanComplaintContactName", "Complaint contact name "],
["pageSpanComplaintContactInformation", "Complaint contact information "],
["pageSpanEmploymentStatus", "Whether it is permanent employment or fixed-term employment or a dispatched worker subject to the agreement"],
["pageSpanAgeStatus", " Whether or not you are over 60 years old "],
["pageSpanPeriodStart", "Implementation Period (Start)"],
["pageSpanPeriodEnd", "Implementation Period (End)"],
["AddNewFile", "Add New File"],
["buttonCaseRegistration", "Case Registration"],
["#tableImplementationDetailsTHNo", "No"],
["#tableImplementationDetailsTHDuplicateSelection", "Duplicate selection"],
["#tableImplementationDetailsTHImplementationPeriod", "Implementation period Invoice creation"],
["#tableImplementationDetailsTHWorkLocation", "Work location"],
["#tableImplementationDetailsTHAssemblyTime", "Assembly time"],
["#tableImplementationDetailsTHStartingTime", "Starting time"],
["#tableImplementationDetailsTHEndingTime", "Ending time"],
["#tableImplementationDetailsTHRequiredNumberOfPeople", "Required number of people"],
["#tableAssignmentInformationTHNo", "No"],
["#tableAssignmentInformationTHAssignStaff", "Assign Staff"],
["#tableAssignmentInformationTHConflictDate", "Conflict date (individual unit)"],
["#tableAssignmentInformationTHNotification", "Notification date and time"],
["#tableAssignmentInformationTHAssignOtherProjects", "Assign other projects"],
["addSkillSheetRow", "Add Row"],
["pageSpanAssignmentRemarks", "Remarks"],

                     
 
 ];

CaseImplementation=[

["accordionImplementationInformation", "Implementation Information"],
["pageSpanWorkingDays", "Working days"],
["pageSpanWorkingDaysSunday", "Sunday"],
["pageSpanWorkingDaysMonday", "Monday"],
["pageSpanWorkingDaysTuesday", "Tuesday"],
["pageSpanWorkingDaysWednesday", "Wednesday"],
["pageSpanWorkingDaysThursday", "Thursday"],
["pageSpanWorkingDaysFriday", "Friday"],
["pageSpanWorkingDaysSaturday", "Saturday"],
["pageSpanHolidays", "Holidays"],
["pageSpanHolidaySunday", "Sunday"],
["pageSpanHolidayMonday", "Monday"],
["pageSpanHolidayTuesday", "Tuesday"],
["pageSpanHolidayWednesday", "Wednesday"],
["pageSpanHolidayThursday", "Thursday"],
["pageSpanHolidayFriday", "Friday"],
["pageSpanHolidaySaturday", "Saturday"],
["pageSpanInternalCommunication", "Internal communication information (private)"],
["pageSpanDetailsOfImplementation", "(S)Details of implementation information (for publication)"],
["buttonSaveImplementInfo", "Save Implementation Information"],
["buttonUpdateImplementInfo", "Update Implementation Information"],

["accordionWorkLocationInfo", "Work Location Information"],
["pageSpanNearestStationTo", " (S) Nearest station to the venue "],
["pageSpanMeetingPlace", " (S) Meeting place "],
["pageSpanOfficeName", " Office Name "],
["pageSpanOrganizationName", "Organization name "],
["pageSpanWorkLocation", "(S) Work Location "],
["pageSpanWorkAddress", "(S) Work Address (including contact information)"],
["pageSpanSalaryUnitPrice", "Salary unit price"],
["pageSpanProjectUnitPrice", "Project unit price"],
["pageSpanStaffUnitPrice", "Staff unit price"],
["pageSpanBasicSalary", "Basic Salary(hourly wage)"],
["pageSpanBilledAmount", "Billed Amount(for 1 person, hourly wage)"],
["pageSpanBillingUnitPriceSetting", "Billing Unit Price Setting"],
["billingUnitPriceSettingDailySalary", "Daily Salary"],
["billingUnitPriceSettingHourlyWage", "Hourly Wage"],
["billingUnitPriceSettingFullMonthlySalary", "Full Monthly Salary"],
["billingUnitPriceSettingDailySalaryMonthly", "Daily Salary Monthly Salary"],
["pageSpanWorkLocationTransportation", "Work Location Transportation"],
["pageSpanStationArrivalTime", "Station Arrival Time"],
["pageSpanStationMeetingTime", "Meeting Time"],
["pageSpanStationScheduledStartTime", "Scheduled Start Time "],
["pageSpanStationScheduledEndTime", "Scheduled End Time "],
["pageSpanStationScheduledActualWorkTime", "Scheduled actual work time "],
["pageSpanScheduleBreaktimeTime", "Scheduled break time "],
["pageSpanDepartureTime", "Scheduled departure time "],
["pageSpanMidnightBreakingTime", " (Inside)Scheduled midnight break time "],
["pageSpanStationDescriptionTime", " Scheduled start and end times are references for hourly wage calculation. Input correctly. If the scheduled break time includes the midnight time zone (22: 00-05: 00), enter it in the (inside) midnight break scheduled time. If the scheduled actual work time is not entered, the overtime, midnight work, and holiday work hours will not be calculated correctly and will not be calculated automatically. "],
["pageSpanWorkRemarks", "(S) Work remarks(break time, etc.) "],
["pageSpanOvertimePaymentUnit", "Overtime payment unit"],
["pageSpanNoOvertimeBillingFee", "No overtime billing fee"],
["pageSpanNoOvertimeBillingNote", "If you check 'No overtime billing fee', you can set the billing fee for overtime work, late night work, and holiday work not to be included in the invoice to the customer."],
["buttonSaveWorkLocation", "Save Work Location Information"], 
["buttonUpdateWorkLocation", "Update Work Location Information"],         

["accordionNotificationOfWorkingConditions", "Notification of working conditions and explicit information on working conditions"],
["pageSpanWorkRemarksNote", "It is applied to the notification of working conditions and the statement of working conditions. Please fill in within the range stipulated by law. "],
["pageSpanmidnightOvertimeHolidayAllowance", "Midnight /overtime / holiday allowance "],
["pageSpanPaymentTerms", " Payment terms "],
["pageSpanAnnualPaidLeave", " Annual paid leave "],
["pageSpanOvertimeHolidayWork", " Overtime/ holiday work "],
["pageSpanSafetyAndHygiene", " Safety and hygiene "],
["pageSpanEmploymentStabilizationMeasures", "Employment stabilization measures for dispatched workers taken by canceling the dispatch contract "],
["pageSpanGrievanceRelatedMatters", "Grievance related matters "],
["pageSpanReasonForNotSubmittingEmployment", "Reason for not submitting employment / social insurance insured qualification notification"],
["pageSpanUseOfWelfareFacilities", " Use of welfare facilities, etc."],
["pageSpanRetirementRelatedMatters", "Retirement related matters"],
["pageSpanContractRenewalRelated", "Contract renewal related Cases "],
["pageSpanConflictPreventionMeasures", "Conflict prevention measures for direct employment of dispatched workers "],
["buttonSaveWorkConditions", "Save Work Condition Information"], 
["buttonUpdateWorkConditions", "Update Work Condition Information"],                    

["accordionDivAssignmentInformation", "Assignment Information"],
["pageSpanRequiredNumberOfStaff", "Required number of staff "],
["buttonAssignmentManagement", "Assignment Management"],
["tableAssignmentInformationTHNo", "No"],
["tableAssignmentInformationTHAssignStaff", "Assign Staff"],
["tableAssignmentConflictDate", "Conflict date (individual unit)"],
["tableAssignmentReferenceBasicSalary", "Reference Basic Salary"],
["tableAssignmentInformationNotification", "Notification date and time"],
["pageSpanInvoiceCreation", "Invoice creation"],
["pageSpanAssignmentRemarks", "Remarks"],
["textAreaAssignmentRemarks", "If you have any particular requests regarding treatment, occupation, working hours, place of work, etc., enter them."],
["buttonSaveAssignmentInfo", "Save Assignment Information"],
["buttonUpdateAssignmentInfo", "Update Assignment Information"],
["notCreated", "notCreated"],
["created", "Created"],
["selectInvoice", "Select Invoice"],
["optionDivisionByBusinessAdministrativecivilservant", "Administrative civil servant"],
["optionDivisionByBusinessCorporategroupofficers", "Corporate / group officers"],
["optionDivisionByBusinessCorporategroupmanagementstaff", "Corporate / group management staff"],
["optionDivisionByBusinessOtheradministrativeworkers", "Other administrative workers"],
["optionDivisionByBusinessresearcher", "researcher"],
["optionDivisionByBusinessAgricultureforestryandfisheriesengineers", "Agriculture, forestry and fisheries engineers"],
["optionDivisionByBusinessManufacturingtechnician", "Manufacturing technician"],
["optionDivisionByBusinessArchitectureCivilEngineeringSurveyor", "Architecture / Civil Engineering / Surveyor"],
["optionDivisionByBusinessInformationprocessingcommunicationengineer", "Information processing / communication engineer"],
["optionDivisionByBusinessOthertechnicians", "Other technicians"],
["optionDivisionByBusinessDoctordentistveterinarianpharmacist", "Doctor, dentist, veterinarian, pharmacist"],
["optionDivisionByBusinessPublichealthnursesmidwivesnurses", "Public health nurses, midwives, nurses"],
["optionDivisionByBusinessMedicaltechnician", "Medical technician"],
["optionDivisionByBusinessOtherhealthcareworkers", "Other health care workers"],
["optionDivisionByBusinessSocialwelfareprofessionals", "Social welfare professionals"],
["optionDivisionByBusinessLegalworker", "Legal worker"],
["optionDivisionByBusinessProfessionalsinmanagementfinanceandinsurance", "Professionals in management, finance, and insurance"],
["optionDivisionByBusinessTeacher", "Teacher"],
["optionDivisionByBusinessReligiousperson", "Religious person"],
["optionDivisionByBusinessWriterreportereditor", "Writer, reporter, editor"],
["optionDivisionByBusinessArtistdesignerphotographerfilmmaker", "Artist, designer, photographer, filmmaker"],
["optionDivisionByBusinessMusicianperformingarts", "Musician, performing arts"],
["optionDivisionByBusinessOtherprofessionalworkers", "Other professional workers"],
["optionDivisionByBusinessGeneralofficeworker", "General office worker"],
["optionDivisionByBusinessAccountingclerk", "Accounting clerk"],
["optionDivisionByBusinessProductionrelatedofficeworkers", "Production-related office workers"],
["optionDivisionByBusinessSalessalesofficeworker", "Sales / sales office worker"],
["optionDivisionByBusinessOutsideofficeworker", "Outside office worker"],
["optionDivisionByBusinessTransportationandpostalofficeworkers", "Transportation and postal office workers"],
["optionDivisionByBusinessOfficeequipmentoperator", "Office equipment operator"],
["optionDivisionByBusinessProductsalesworker", "Product sales worker"],
["optionDivisionByBusinessSaleslikeprofessionalworkers", "Sales-like professional workers"],
["optionDivisionByBusinessSalespositionworker", "Sales position worker"],
["optionDivisionByBusinessFamilylifesupportserviceprofessionalworker", "Family life support service professional worker"],
["optionDivisionByBusinessLongtermcareserviceworker", "Long-term care service worker"],
["optionDivisionByBusinessHealthcareserviceprofessionals", "Health care service professionals"],
["optionDivisionByBusinessLifehygieneserviceworker", "Life hygiene service worker"],
["optionDivisionByBusinessFoodanddrinkcook", "Food and drink cook"],
["optionDivisionByBusinessCustomerservicewaiterworkers", "Customer service / waiter workers"],
["optionDivisionByBusinessManagerofresidentialfacilitiesbuildings", "Manager of residential facilities, buildings, etc."],
["optionDivisionByBusinessOtherserviceworkers", "Other service workers"],
["optionDivisionByBusinessSelfdefenseofficials", "Self-defense officials, judicial police officers, etc."],
["optionDivisionByBusinessAgriculturalist", "Agriculturalist"],
["optionDivisionByBusinessForestryworkers", "Forestry workers"],
["optionDivisionByBusinessFishermen", "Fishermen"],
["optionDivisionByBusinessProductionequipmentcontrol", " Production equipment control / monitoring worker"],
["optionDivisionByBusinessMachineassemblyequipmentcontrol", "Machine assembly equipment control / monitoring worker"],
["optionDivisionByBusinessProductmanufacturing", "Product manufacturing / processing workers"],
["optionDivisionByBusinessMachineassembler", "Machine assembler"],
["optionDivisionByBusinessMachinemaintenance", "Machine maintenance / repair workers"],
["optionDivisionByBusinessProductinspector", "Product inspector"],
["optionDivisionByBusinessMechanicalinspector", "Mechanical inspector"],
["optionDivisionByBusinessProductionrelated", "Production-related"],
["optionDivisionByBusinessRailwayoperator", "Railway operator"],
["optionDivisionByBusinessCardriver", "Car driver"],
["optionDivisionByBusinessShipaircraftoperator", "Ship / aircraft operator"],
["optionDivisionByBusinessOthertransporters", "Other transporters"],
["optionDivisionByBusinessStationaryconstructionmachineoperator", "Stationary"],
["optionDivisionByBusinessConstructionskeletonconstructionworker", "Construction skeleton construction worker"],
["optionDivisionByBusinessConstructionworkers", "Construction workers(excluding construction workers)"],
["optionDivisionByBusinessElectricalengineer", "Electrical engineer"],
["optionDivisionByBusinessCivilengineer", "Civil engineer"],
["optionDivisionByBusinessMiner", "Miner"],
["optionDivisionByBusinessTransporter", "Transporter"],
["optionDivisionByBusinessCleaningworker", "Cleaning worker"],
["optionDivisionByBusinessPackagingworker", "Packaging worker"],
["optionDivisionByBusinessUnclassifiableoccupations", "Unclassifiable occupations"],
["optionDivisionByBusinessInformationprocessingsystemdevelopment", "Information processing system development"],
["optionDivisionByBusinessMechanicaldesign", "Mechanical design"],
["optionDivisionByBusinessOfficeequipmentoperation", "Office equipment operation"],
["optionDivisionByBusinessInterpretationtranslationshorthand", "Interpretation, translation, shorthand"],
["optionDivisionByBusinessSecretary", "Secretary"],
["optionDivisionByBusinessFiling", "Filing"],
["optionDivisionByBusinessSurvey", "Survey"],
["optionDivisionByBusinessTreasury", "Treasury"],
["optionDivisionByBusinessTrade", "Trade"],
["optionDivisionByBusinessDemonstration", "Demonstration"],
["optionDivisionByBusinessTourguide", "Tour guide"],
["optionDivisionByBusinessReceptionInformation", "Reception / Information"],
["optionDivisionByBusinessRD", "R & D"],
["optionDivisionByBusinessPlanningandplanningofprojectimplementationsystem", "Planning and planning of project implementation system"],
["optionDivisionByBusinessProductioneditingofbooks", "Production / editing of books, etc."],
["optionDivisionByBusinessSalesengineersalesfinancialproductsales", "Sales engineer sales, financial product sales"],
["optionDivisionByBusinessAdvertisingdesign", "Advertising design"],
["optionDivisionByBusinessOAinstructions", "OA instructions"],
["optionEmploymentStatusFixedTermEmploymentWorker", "Fixed-Term Employment Worker"],
["optionEmploymentStatusFixedTermEmploymentWorkerDispatched", "Fixed-Term Employment Workers(Dispatched workers subject to the agreement)"],
["optionEmploymentStatusPermanentWorker", "Permanent Worker"],
["optionEmploymentStatusPermanentWorkerDispatched", "Permanent Employment Workers(Dispatched workers subject to the agreement)"],
["optionAgeStatusLimitedOver60", "Limited to over 60 years old"],
["optionAgeStatusNotLimitedOver60", "Not Limited to over 60 years old"],
["optionOvertimePaymentUnitDaily", "Daily"],
["optionInvoiceCreation", "Select Invoice Creation"],
["optionInvoiceCreationNotCreated", "Not Created"],
["optionInvoiceCreationCreated", "Created"],
["buttonValueSpanCaseImplementationDelete", "Delete Case Implementation"],
["detailsOfImplementation", "[Clothing] [What to bring]"],
["pageSpanImplementationDate", "(S) Implementation date"],
["exampleModalCenterTitleInchargeStaff", "Duplicate Implementation Date"],
["titleSelectStaffInCharge", "Select Date"],
["inchargebatchChangeClose", "Close"],
["btnImplementationDuplicate", "Duplicate"],
["exampleModalLabel1", "Worker dispatch individual contract output"],
["exampleModalLabelNote1", "* Create an individual contract for dispatching workers for the specified period."],
["pageSpanImplementationPeriodStart1", "Target period (start)"],
["pageSpanImplementationPeriodEnd1", "Target period (End)"],
["buttonWorkerDispatchIndividualContractOutput", "Worker dispatch individual contract output"],
["exampleModalLabel2", "Dispatch source management ledger output"],
["exampleModalLabelNote2", "* Create a dispatch source management ledger for the specified period."],
["pageSpanImplementationPeriodStart2", "Target period (start)"],
["pageSpanImplementationPeriodEnd2", "Target period (End)"],
["buttonWorkerDispatchIndividualContractOutput", "Dispatch source management ledger output"],
["exampleModalLabel3", "Dispatch destination management ledger output"],
["exampleModalLabelNote3", "* Create a Dispatch destination management ledger for the specified period."],
["pageSpanImplementationPeriodStart3", "Target period (start)"],
["pageSpanImplementationPeriodEnd3", "Target period (End)"],
["buttonDispatchDestinationManagementLedgerOutput", "Dispatch destination management ledger output"],
["exampleModalLabel4", "Output of working condition notification and working condition statement"],
["exampleModalLabelNote4", "* We will create a notification of working conditions and a written statement of working conditions for the specified period."],
["pageSpanImplementationPeriodStart4", "Target period (start)"],
["pageSpanImplementationPeriodEnd4", "Target period (End)"],
["buttonWorkingConditionNotificationWorkingConditionStatement", "Output of working condition notification and working condition statement"],


 ];
 
caseErrorArray ={"E2000":"Invalid Case Number",
 				  "E2001":"Invalid Quotation Number",
 				  "E2002":"Invalid Customer Representative Name",
 				  "E2003":"Implementation Periods do not match",
 				  "E2004":"Conflict Dates do not match",
 				  "E2005":"Cannot be empty",
 				  "E2006":"Invalid Case Number",
 				  "E2007":"Invalid Required Number of People",
 				  "E2008":"Invalid Name of Dispatcher",
 				  "E2009":"Invalid Mobile Number",
 				  "E2010":"Invalid Name Of Dispatcher Grievance handler",
 				  "E2011":"Invalid Commander Name", 
 				  "E2012":"Invalid Officer name",
 				  "E2013":"Implementation Periods do not match!",
 				  "E2014":"Invalid Complaint Contact Name",
 				  "E2015":"Invalid Complaint Contact Information",
 				  "E2016":"Invalid Basic Salary",
 				  "E2017":"Invalid Billed Amount",
 				  "E2018":"Invalid Required Number Of Staff",
 				  "E2019":"Invalid Reference Basic Salary",
 				  "E2020":"Please select a Salary Unit Price",
 				  "E2021":"Invalid Salary",
 				  "E2022":"Invalid Number Of Hires",
 				  "E2023": "Scheduled Times do not match",
 				  "E2024": "Please enter time duration in hh:mm format",
 				  "E2025": "Invalid Midnight /overtime / holiday allowance",
 				  }
 
 