function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(CustomerSearch);
    convertContentToLanguage(CustomerDetails);
    convertTitleToLanguageByName(TitleList);
}

TopMenu = [
 
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

TitleList = [
	["viewDetails", "View Details"],
	["MakeQuotation", "Make A Quotation"],
	["MakeInvoice", "Make an Invoice"],
];

CustomerSearch = [
 
   ["pageTitleCustomerList", "Customer List"],
    ["pageSpanHeadingCustomer", "Customer List"],
    ["pageSpanSearch", "Search"],
    ["buttonSpanCustomerReg", "Customer Registration"],
    ["buttonSpanImportCustomerData", "Import Existing Customer Data"],
    ["buttonSpanCustomerListCSV", "Output Customer List CSV"],
    ["pageCardDivTotalCustomers", "Total Number of Customers"],
    ["pageCardDivTotalActiveCustomers", "Total Active Customers"],
    ["pageCardDivTotalAvailableCustomers", "Total Available Customers"],
    ["pageCardDivTotalPendingCustomers", "Total Pending Customers"],
    ["pageLabelCompanyName", "Company Name"],
    ["companyNames", "Enter Company Name"],
    ["pageLabelCompanyNameKatakana", "Company Name Katakana"],
    ["companyNameKatakana", "Enter Company Name Katakana"],
    ["pageLabelBelonging", "Belonging"],
    ["companyBelonging", "Enter Belonging"],
    ["pageLabelCustomerCode", "Customer Code"],
    ["customerCode", "Enter Customer Code"],
    ["pageLabelMobilePhone", "Mobile Phone"],
    ["mobilePhone", "Enter Mobile Number"],
    ["pageLabelMailAddress", "Email Address"],
    ["mailAddress", "Enter Email Address"],
    ["pageLabelDispatchClassification", "Dispatch Classification"],
    ["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
    ["pageSpanGeneralDispatch", "General dispatch"],
    ["pageSpanBusinessContract", "Out Sourcing"],
    ["pageSpanIntroductionDispatching", "Temp - to - Perm"],
    ["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
    ["pageLabelPostalcode", "Postal code"],
    ["postalCode", "Enter Postal code"],
    ["pageLabelPrefectures", "Prefectures"],
    ["selectOptionSelectPrefectures", "Select Prefecture"],
    ["pageOption1Prefecture", "Hokkaido"],
     ["pageOption2Prefecture", "Aomori"],
     ["pageOption3Prefecture", "Iwate"],
     ["pageOption4Prefecture", "Miyagi"],
     ["pageOption5Prefecture", "Akita"],
     ["pageOption6Prefecture", "Yamagata"],
     ["pageOption7Prefecture", "Fukushima"],
     ["pageOption8Prefecture", "Ibaraki"],
     ["pageOption9Prefecture", "Tochigi"],
     ["pageOption10Prefecture", "Gunma"],
     ["pageOption11Prefecture", "Saitama"],
     ["pageOption12Prefecture", "Chiba"],
     ["pageOption13Prefecture", "Tokyo"],
     ["pageOption14Prefecture", "Kanagawa"],
     ["pageOption15Prefecture", "Niigata"],
     ["pageOption16Prefecture", "Toyama"],
     ["pageOption17Prefecture", "Ishikawa"],
     ["pageOption18Prefecture", "Fukui"],
     ["pageOption19Prefecture", "Yamanashi"],
     ["pageOption20Prefecture", "Nagano"], // changed
     ["pageOption21Prefecture", "Gifu"], // changed
     ["pageOption22Prefecture", "Shizuoka"],
     ["pageOption23Prefecture", "Aichi"],
     ["pageOption24Prefecture", "Mie"],
     ["pageOption25Prefecture", "Shiga"],
     ["pageOption26Prefecture", "Kyoto"],
     ["pageOption27Prefecture", "Osaka"],
     ["pageOption28Prefecture", "Hyogo"],
     ["pageOption29Prefecture", "Nara"],
     ["pageOption30Prefecture", "Wakayama"],
     ["pageOption31Prefecture", "Tottori"],
     ["pageOption32Prefecture", "Shimane"],
     ["pageOption33Prefecture", "Okayama"],
     ["pageOption34Prefecture", "Hiroshima"],
     ["pageOption35Prefecture", "Yamaguchi"],
     ["pageOption36Prefecture", "Tokushima"],
     ["pageOption37Prefecture", "Kagawa"],
     ["pageOption38Prefecture", "Ehime"],
     ["pageOption39Prefecture", "Kochi"],
     ["pageOption40Prefecture", "Fukuoka"],
     ["pageOption41Prefecture", "Saga"],
     ["pageOption42Prefecture", "Nagasaki"],//changed
     ["pageOption43Prefecture", "Kumamoto"],
     ["pageOption44Prefecture", "Oita"], // changed
     ["pageOption45Prefecture", "Miyazaki"],
     ["pageOption46Prefecture", "Kagoshima"],
     ["pageOption47Prefecture", "Okinawa"],
    ["pageLabelAddress", "Address"],
    ["companyAddress", "Enter Company Address"],
    ["pageOrganizationName", "Organization Name"],
    ["companyOrganizationName", "Enter Organization Name"],
    ["pageLabelRepresentativeName", "Customer Representative Name"],
    ["companyRepresentativeName", "Enter Customer Representative Name"],
    ["pageLabelRepresentativeNameKatakana", "Customer Representative Name Katakana"],
    ["companyRepresentativeNameKatakana", "Enter Customer Representative Name Katakana"],
    ["pageLabelManager", "Manager"],
    ["selectOptionSelectCompanyManager", "Select Manager"],
    ["selectOptionSelectCompanyManagerA", "Company Manager A"],
    ["selectOptionSelectCompanyManagerB", "Company Manager B"],
    ["selectOptionSelectCompanyManagerC", "Company Manager C"],
    ["selectOptionSelectCompanyManagerD", "Company Manager D"],
    ["selectOptionSelectCompanyManagerE", "Company Manager E"],
    ["pageLabelCustomerRank", "Rank"],
    ["selectOptionSelectRank", "Select Rank"],
    ["clearAllBtn", "Clear All"],
    ["searchBtn", "Search"],
    ["pageSpanSearchCustomerDetails", "Search Customer Details"],
    ["buttonSpanCheckAll", "Check All"],
    ["buttonSpanUncheckAll", "Uncheck All"],
    ["buttonSpanBatchDeletion", "Batch Deletion"],
    ["tableSearchStaffTHNo", "No"],
    ["tableSearchStaffTHChoice", "Choice"],
    ["tableSearchCustomerTHCustomerCode", "Customer Code"],
    ["tableSearchCustomerTHTel", "Tel/Email"],
    ["tableSearchCustomerTHDispatchClassification", "Dispatch Classification"],
    ["tableSearchCustomerTHAddress", "Address"],
    ["tableSearchCustomerTHCompanyName", "Customer Company Name"],
    ["tableSearchCustomerTHCustomerRepresentative", "Customer Representative Name"],
    ["tableSearchCustomerTHManager", "Manager"],
    ["tableSearchCustomerTHRank", "Rank"],
    ["exampleModalCenterTitle", "Batch Deletion"],
    ["modalAreYouSure", "Are You Sure?"],
    ["modalDoYouWantDelete", "Do You Really Want to Delete this Records?"],
    ["modalProcesCannotBeUndone", "This Process Cannot be Undone."],
    ["tableSearchStaffTHNo", "Record No"],
    ["tableSearchCustomerOrganizationName", "Organization Name"],
    ["tableSearchStaffCustomerRepresentativeName", "Customer Representative Name"],
    ["tableSearchCustomerCode", "Customer Code"],
    ["batchDeleteConfirm", "Confirm"],
    ["batchDeleteClose", "Close"]
    
];


CustomerDetails = [
   ["CustomerRegistrationHeader", "Customer Registration"],
    ["pageTitleCustomerDetail", "Customer Details"],
    ["pageSpanHeadingCustomerRegistration", "Customer Registration"],
    ["pageSpanHeadingCustomerDetails", "Customer Details"],
    ["pageSpanSubHeadingCustomerRegistration", "You can register as a customer."],
    ["pageSpanSubHeadingCustomerDetails", "You can modify the customer and create a quote related to this customer."],
    ["buttonSpanCreateFromThisCustomer", "Create From This Customer"],
    ["buttonValueSpanCustomerMakeQuote", "Make a Quote"],
    ["buttonValueSpanCustomerProposalCreation", "Proposal creation"],
    ["buttonValueSpanCustomerInvoiceCreation", "Invoice Creation"],
    ["buttonValueSpanCustomerCopyAndCreateAnotherCustomer", "Copy And Create Another Customer"],
    ["buttonSpanStaffDetailsDelete", "Delete"],
    ["buttonValueSpanStaffDetailsDelete", "Delete Customer"],
    ["buttonSpanReturn", "Return"],
    ["accordionDivCustomerInformation", "Customer Information"],
    ["pageSpanCompanyName", "Company Name"],
    ["pageSpanCompanyNameKatakana", "Company Name Katakana"],
    ["pageSpanRepresentativePosition", "Representative Position"],
    ["pageSpanRepresentativeName", "Representative Name"],
    ["pageLabelMobilePhone", "Mobile Phone"],
    ["pageSpanHelpMobile", "Please enter without hyphens"],
    ["pageSpanFaxNumber", "Fax Number"],
    ["pageSpanHelpFax", "Please enter without hyphens"],
    ["pageLabelMailAddress", "Email Address"],
    ["pageSpanCustomerCode", "Customer Code"],
    ["pageSpanDisClassification", "Dispatch classification"],
    ["pageSpanGeneralDispatch", "General Dispatch"],
    ["pageSpanBusinessContract", "Out Sourcing"],
    ["pageSpanIntroductionDispatching", "Temp -to-Perm"],
    ["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
    ["pageSpanPartTime", "Part Time"],
    ["pageLabelPostalcode", "Postal code"],
    ["btnAddressSearch", "Address Search"],
    ["pageSpanHelpZipCode", "Please enter without hyphens"],
    ["pageSpanPrefecture", "Prefecture"],
    ["pageSpanAddress", "Address", "住所"],
    ["pageSpanHelpAddress", "Please be sure to enter the apartment name and building name"],
    ["pageSpanOrganizationName", "Organization Name"],
    ["pageSpanBillingDeadline", "Billing Deadline"],
    ["pageSpanCustomerRepresentativeName", "Customer Representative Name"],
    ["pageSpanCustomerRepresentativeNameKatakana", "Customer Representative Name Katakana"],
    ["pageSpanCustomerContact", "Customer Contact"],
    ["pageSpanManager", "Manager"],
    ["SelectCompanyManager", "Select Manager"],
    ["SelectCompanyManager1", "Manager A"],
    ["SelectCompanyManager2", "Manager B"],
    ["SelectCompanyManager3", "Manager C"],
    ["SelectCompanyManager4", "Manager D"],
    ["SelectCompanyManager5", "Manager E"],
    ["pageSpanBelongned", "Belonged"],
    ["pageSpanWebsiteURL", "URL (own website)"],
    ["pageSpanConflictDate", "Conflict Date (Business Unit)"],
    ["pageSpanRank", "Rank"],
    ["selectRank", "Select Rank"],
    ["pageSpanRemarks", "Remarks"],
    ["buttonEditCompanyInformation", "Update Company Information"],
    ["buttonSaveCompanyInformation", "Save Company Information"],
    ["pageSpanHelpContact", "Please enter without hyphens"],
    ["pageHeadingCustomerBatchRegistration", "Customer Batch Registration"],
    ["pageSpanHeadingCustomerBatchRegistration", "Customer Batch Registration"],
    ["spanDownloadLink", "Click Here To Download File Upload Template Link"],
    ["buttonUploadFile", "Upload File"],
    ["exampleModalTitleUploadSummary", "Upload Summary"],
    ["spanUploadedFileName", "Uploaded File Name :"],
    ["spanTotalRowCount", "Total Row Count : "],
    ["spanValidRowCount", "Valid Row Count : "],
    ["spanInvalidRowCount", "Invalid Row Count : "],
    ["btnDownloadSummaryFilelink", "Download Summary File"],
    ["batchDeleteClose", "Close"],
    
];


customerErrorArray = {"E1001":"Invalid Customer Code", "E1002":"Invalid Mobile Number", "E1003":"Invalid Email", "E1004":"Invalid Postal Code", "E1005":"cannot be empty", "E1006":" Invalid Company Representative Name", "E1007":"Invalid Fax Number", "E1008":"Customer Representative Name can not be empty", "E1009":"Invalid Customer Representative Name", "E1010":"Customer Representative Name Katakana can not be empty", "E1011":"Invalid Customer Representative Name Katakana", "E1012":" Invalid Customer Contact Number", "E1013":"Invalid URL","E1014":"Invalid Company Name", "E1015":"This Email Already Exists",  }
		



