function switchLanguage(siteLanguage) {
	convertContentToLanguage(TopMenu);
	convertContentToLanguage(LeftMenu);
	convertContentToLanguage(Employee)
}

TopMenu = [

	["menuButtonProfile", "Profile"],
	["menuButtonManual", "Manual"],
	["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management"],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

Employee = [
	["pageTitleEmployeeManagement", "Employee Management"],
	["pageTitleEmployeeDetails", "Employee Details"],
	["pageTitleEmployeeRegistration", "Employee Registration"],
	["pageSpanHeadingEmployeeList", "Employee List"],
	["buttonSpanEmployeeRegistration", "Employee Registration"],
	["pageSpanSearch", "Search"],
	["pageLabelName", "Name"],
	["name", "Enter Name "],
	["pageLabelDateofJoiningFrom", "Date of Joining From"],
	["pageLabelMailAddress", "Mail Address"],
	["mailAddress", "Enter Mail Address"],
	["pageLabelDateofJoiningTo", "Date of Joining To"],
	["pageLabelAuthority", "Authority"],
	["selectOptionSelectAuthority", "Select Authority"],
	["pageOptionAdministrator", "Administrator"],
	["pageOptionInchargeoftheMatter", "Incharge of the Matter"],
	["pageOptionSales", "Sales"],
	["pageOptionAccounting", "Accounting"],
	["pageOptionStaffCharge", "Staff Charge"],
	["pageOptionProfessional", "Professional"],
	["pageOptionOthers", "Others"],
	["optionClassification", "Select Classification"],
	["pageLabelValidClassification", "Valid Classification"],
	["option0ValidClassification", "Select Valid Classification"],
	["option1ValidClassification", "Valid"],
	["option2ValidClassification", "Invalid"],
	["clearAllBtn", "Clear All"],
	["searchBtn", "Search"],
	["pageCardDivTotalStaff", "Total Number of Staff"],
	["pageCardDivTotalActiveStaff", "Total Active Staff"],
	["pageCardDivTotalAvailableStaff", "Total Available Staff"],
	["pageCardDivTotalPendingStaff", "Total Pending Staff"],
	["pageSpanSearchStaffDetails", " Search Employee Details"],
	["tableSearchEmployeeTHNo", "No"],
	["tableSearchEmployeeTHName", "Name"],
	["tableSearchEmployeeTHEmail", "Email"],
	["tableSearchEmployeeTHAuthority", "Authority"],
	["tableSearchEmployeeTHDateofJoining", "Date of joining"],
	["tableSearchEmployeeTHValidClassification", "Valid Classification"],
	["search_table_info", "No records available "],
	["pageSpanHeadingRegistrationEmployeeRegister", "Employee Registration"],
	["pageSpanSubHeadingRegistrationStaffDetails", "You can register as an employee."],
	["buttonSpanRegistrationReturn", "Return"],
	["accordionDivRegistrationEmployeeInformation", "Employee Information"],
	["pageSpanRegistrationEmployeeName", "Name"],
	["pageSpanregistrationEmailaddress", "Email Address"],
	["pageSpanregistrationAuthority", "Authority"],
	["optionregistrationAuthoritySelectAuthority", "Select Authority"],
	["optionregistrationAuthorityAdministrator", "Administrator"],
	["optionregistrationAuthorityInchargeofthematter", "In charge of the matter"],
	["optionregistrationAuthoritySales", "Sales"],
	["optionregistrationAuthorityAccounting", "Accounting"],
	["optionregistrationAuthorityStaffCharge", "Staff Charge"],
	["pageSpanregistrationTransferfinancialinstitutionname", "Transfer financial institution name"],
	["pageSpanregistrationBankCode", "Bank Code"],
	["pageSpanregistrationTransferbranchname", "Transfer Branch Name"],
	["pageSpanregistrationBranchCode", "Branch Code"],
	["pageSpanregistrationAccounttype", "Account type"],
	["optionAccountTyperegistrationSelect", "Select Account Type"],
	["optionAccountTyperegistrationUsually", "Usually"],
	["optionAccountTyperegistrationCurrent", "Current"],
	["optionAccountTyperegistrationSavings", "Savings"],
	["optionAccountTyperegistrationOthers", "Others"],
	["pageSpanregistrationAccountNumber", "Account Number"],
	["pageSpanregistrationAccountName", "Account Name"],
	["pageSpanregistrationDateofjoiningthecompany", "Date of joining the company"],
	["pageSpanregistrationSuperiorName", "Superior Name"],
	["pageSpanregistrationPassword", "Password"],
	["pageSpanregistrationForPasswordConfirmation", "For Password Confirmation"],
	["pageSpanregistrationRemarks", "Remarks"],
	["pageSpanregistrationValidclassification", "Valid Classification"],
	["optionregistrationvalidclassification", "Valid"],
	["optionregistrationInValidclassification", "Invalid"],
	["pageSpanregistrationTerminationDate", "Termination date"],
	["buttonSaveregistrationEmployeeInformation", "Register Employee"],
	["pageSpanHeadingEmployeeDetails", "Employee Details"],
	["pageSpanSubHeadingEmployeeDetails", "Employee information can be modified"],
	["buttonSpanReturn", "Return"],
	["accordionDivEmployeeInformation", "Employee Information"],
	["pageSpanName", "Name"],
	["pageSpanEmailaddress", "Email address"],
	["pageSpanAuthority", "Authority"],
	["pageSpanTransferfinancialinstitutionname", "Transfer Financial Institution Name"],
	["pageSpanBankCode", "Bank Code"],
	["pageSpanTransferbranchname", "Transfer Branch Name"],
	["pageSpanBranchCode", "Branch Code"],
	["pageSpanAccounttype", "Account Type"],
	["optionAccountTypeSelectAccountType", "Select Account Type"],
	["optionAccountTypeUsually", "Usually"],
	["optionAccountTypeCurrent", "Current"],
	["optionAccountTypeSavings", "Savings"],
	["optionAccountTypeOthers", "Others"],
	["pageSpanAccountNumber", "Account Number"],
	["pageSpanAccountName", "Account Name"],
	["pageSpanDateofjoiningthecompany", "Date of joining the company"],
	["pageSpanSuperiorName", "Superior Name"],
	["pageSpanNewPassword", "New Password"],
	["pageSpanForNewPasswordConfirmation", "For New Password Confirmation"],
	["pageSpanRemarks", "Remarks"],
	["pageSpanValidclassification", "Valid Classification"],
	["optionvalidclassification", "Valid"],
	["optionInvalidclassification", "Invalid"],
	["pageSpanTerminationDate", "Termination Date"],
	["buttonUpateEmployeeInformation", "Update Employee"],
	["pageSpanSearchEmployeeDetails", "Search Employee Details"],
	["pageCardDivTotalNumberofStaff", "Total Number of Staff"],
	["pageSpanHeadingEmployeeRegister", "Employee Registration"],
	["pageSpanSubHeadingStaffDetails", "You can register as an employee."],
	["pageSpanHeadingEmployeeDetails", "Employee Details"],
	["pageSpanEmployeeName", "Name "],
	["pageSpanPassword", "Password "],
	["pageSpanForPasswordConfirmation", "Password Confirmation "],
	["optionAccountTypeSelect", "Select Account Type"],
	["pageSpanRetirementDate", "Retirement date"],
	["buttonSaveEmployeeInformation", "Register Employee"],
	["optionSuperiorName", "Select  Superior Name"],
	["optionSelectvalidclassification", "Select Valid classification"],
	["pageLabelDateJoinFrom", "Date of Joining From"],
	["pageTitleEmployeeRegistration", "Employee Registration"],
	["pageTitleEmployeeDetails", "Employee Details"],
	["pageTitleEmployeeManagement", "Employee Management"],
];

employeeErrorArray = { "E2180": "Can not be empty", "E2184": "Invalid Name", "E2185": "Invalid Email", "E2186": "Password does not match", "E2183": "Dates of Joining do not match", "E2187":"This email already exists" }




