function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(Invoice);
    convertContentToLanguageByName(nameList);
}

TopMenu = [
 
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];


Invoice = [
    ["pageTitleInvoiceManagement", "Invoice Management"],
    ["pageSpanHeadingInvoiceManagement", "Invoice List"],
    ["pageTitleInvoiceDetails", "Invoice Details"],
    ["pageTitleInvoiceCreate", "Invoice Create"],
    ["pageSpanHeadingInvoiceCreate", "Invoice Create"],
    ["pageSpanHeadingInvoiceCreate", "Invoice Create"],
	["pageSpanSubHeadingInvoiceCreate", "You can Create the invoice"],
	["pageSpanInvoiceManagementNote", "You can check the invoice information in a list.If you want to create an invoice from a quote, select the target quote details button and click the Create from this quote button.If you want to create an invoice from a case, select the target cases from a details and click the Create from this case button"],
	["buttonSpanInvoicefromCustomer", "Invoice from Customer"],
	["buttonSpanInvoiceCreationfromMatter", "Invoice Creation from Case"],
	["buttonSpanInvoiceCreationfromQuotation", "Invoice Creation from Quotation"],
	["buttonSpanInvoiceListCSVOutput", "Invoice List CSV Output"],
	["pageSpanSearch", " Search"],
	["pageLabelInvoiceNumber", "Invoice Number"],
	["pageLabelQuotationNumber", "Quotation Number"],
	["quotationNumber", "Enter Quotation Number"],
	["pageLabelBillingStatus", "Billing Status"],
	["optionSelectBillingStatusSelect", "Select Invoice Status"],
	["optionSelectBillingStatusUnpaid", "Unpaid"],
	["optionSelectBillingStatusDeposited", "Deposited"],
	["optionSelectBillingStatusReserve", "Reserve"],
	["optionSelectBillingStatusCancel", "Cancel"],
	["pageLabelProjectTitle", "Project Title"],
	["pageLabelDeadlineFrom", "Deadline From"],
	["pageLabelClosingDateTo", "Closing Date To"],
	["pageLabelCustomerCompanyName", "Customer Company Name"],
	["pageLabelcustomerRepresentativeName", "Customer Representative Name"],
	["pageLabelBelongs", "Belongs"],
	["pageLabelSalesRepresentativeName", "Sales Representative Name"],
	["pageLabelNameofPersonInchargeofMatter", "Name of Person In charge of Case"],
	["invoiceNumber", "Enter Invoice Number"],
	["projectTitle", "Enter Project Title"],
	["customerCompanyName", "Enter Customer Company Name"],
	["customerRepresentativeName", "Enter Customer Represent Name"],
	["belongs", "Enter Belongs"],
	["salesRepresentativeName", "Enter Sales Representative Name"],
	["nameofPersonInchargeofMatter", "Enter Name of Person Incharge Case"],
	["clearAllBtn", "Clear All"],
	["searchBtn", "Search"],
	["pageCardDivTotalNumberofInvoices", "Total	Number of Invoices"],
	["pageCardDivNumberofDeposedInvoices", "Number of Deposited Invoices"],
	["pageCardDivNumberofonHoldInvoices", "Number of on Hold Invoices "],
	["pageCardDivNumberofcancelInvoices", "Number of Cancel Invoices "],
	["pageSpanSearchCaseList", "Searched Invoice"],
	["pageSpanDataTableNote", "After confirming the assigned staff, select the staff name in the assigned staff column and send the Case assignment email."],
	["tableSearchTHNo", "No"],
	["tableSearchTHInvoiceNumber", "Invoice Number"],
	["tableSearchTHQuotationNumber", "Quotation Number"],
	["tableSearchTHBillingStatus", "Billing Status"],
	["tableSearchTHMatter", "Case"],
	["tableSearchTHClosingDate", "Closing Date"],
	["tableSearchTHCustomerCompanyName", "Customer Company Name"],
	["tableSearchTHCustomerRepresentativeName", "Customer Representative Name"],
	["tableSearchTHOccupationClassification", "Occupation Classification"],
	["tableSearchTHSalesRepresentative", "Sales Representative"],
	["tableSearchTHCaseManager", "Case Manager"],
	["tableSearchTHAmountofMoney", "Amount of Money"],
	["search_table_info", "No records available"],
	["pageSpanHeadingInvoiceDetails", " Invoice Details "],
	["pageSpanSubHeadingInvoiceDetails", "You can modify the invoice"],
	["buttonValueSpanDeleteInvoice", "Delete Invoice"],
	["buttonSpanDelete", "Delete"],
	["buttonSpanReturn", "Return"],
	["buttonSpanOutputInvoice", "Output Invoice"],
	["accordionDivInvoiceInformation", "Invoice	Information"],
	["pageSpanInvoiceInformation", "Invoice Information"],
	["pageSpanInvoiceNumber", "Invoice Number"],
	["pageSpanInvoiceCreationDate", "Invoice Creation Date"],
	["pageSpanorderNumber", "Order Number"],
	["pageSpanClosingDate", "Closing Date"],
	["pageSpanCaseManager", "Case Manager"],
	["pageSpanCaseRepresentative", "Case Representative"],
	["pageSpanCustomerCompanyName", "Customer Company Name"],
	["pageSpanCustomerRepresentativeName", "Customer Representative Name"],
	["pageSpanTaxRate", "Tax Rate"],
	["pageSpanBillingStatus", "Billing	Status"],
	["selectOptionSelectInvoiceStatus", "Select Invoice Status"],
	["pageSpanBillingStatusMakeAInvoice", "Make	a Invoice"],
	["pageSpanBillingInvoiceSubmitted", "Invoice Submitted"],
	["pageSpanBillingDuringNegotiations", "During Negotiations"],
	["pageSpanBillingReceived", "Orders Received"],
	["pageSpanBillingOnHold", "On Hold"],
	["pageSpanBillingCancel", "Cancel"],
	["tableInvoiceDetailsTHNo", "No"],
	["tableInvoiceDetailsTHMajorItems", "Item"],
	["tableInvoiceDetailsTHContents", "Contents"],
	["tableInvoiceDetailsTHAmountMoney", "Amount of Money"],
	["tableInvoiceDetailsTHConsumptionTax", "Consumption Tax"],
	["tableInvoiceDetailsTHConsumptionTaxSubTotal", "Consumption Sub Total"],
	["Calculation1", "Calculation"],
	["Calculation2", "Calculation"],
	["Calculation3", "Calculation"],
	["Calculation4", "Calculation"],
	["Calculation5", "Calculation"],
	["Calculation6", "Calculation"],
	["Calculation7", "Calculation"],
	["Calculation8", "Calculation"],
	["Calculation9", "Calculation"],
	["Calculation10", "Calculation"],
	["tableInvoiceDetailsSubtotalTaxable", "Total"],
	["TaxableInvoiceItemRowAdd", "Add Row"],
	["pageSpanRemarks", "Remarks"],
	["buttonSaveInvoiceDetails", "Save Invoice"],
	["buttonUpdateInvoiceDetails", "Update Invoice"],
	["pageSpanPersonInCharge", "Case manager"],
	["optionPersonInCharge", "Select Person In Charge of the case"],
	["optionPersonInCharge1", "Person In Charge 1"],
	["optionPersonInCharge2", "Person In Charge 2"],
	["pageSpanSalesRepresentative", "Sales Representative"],
	["selectSalesRepresentative", "Select Sales Representative"],
	["selectSalesRepresentative1", "Sales Representative 1"],
	["selectSalesRepresentative2", "Sales Representative 2"],
	["pageSpanTargetPeriodStart", "Target Period Start"],
	["pageSpanTargetPeriodEnd", "Target Period End"],
	["pageSpanInvoiceDetails", "Invoice Details"],
	["pageSpanInvoiceDetailsHelp", "If you change the details, the amount may differ from the output 'Internal work details'."],
	["selectOptionSelecttaxRate", "Select Tax Rate"],
];

nameList = [
["calculation", "calculation"],
];

invoiceErrorArray ={"E2181":"Invalid Invoice Number",
					"E2182":"Invalid Quotation Number",
					"E2183":"Closing Dates do not match",
					"E2184":"Invalid Customer Representative Name",
					"E2185":"Invalid Sales Representative Name",
					"E2186":"Invalid Name of Person Incharge of Case",
					"E2187":"Cannot be empty",
					"E2188":"Invalid Order Number",
					"E2189":"Target Periods do not match"};
