function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(section1);
}

TopMenu = [
 
     ["menuButtonProfile", "Profile"],
     ["menuButtonManual", "Manual"],
     ["menuButtonLogout", "Logout"],
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];


section1 = [
	["pageTitlePayrollPayslip", "Payroll Payslip"],
	["pageSpanHeadingPayslip","Payslip"],
	["buttonSpanReturn","Return"],
	["pageSpanSubHeadingPayrollPayslip","You can modify payroll information and send pay slip emails."],
	["accordionStaffInformation","Staff Information"],
	["pageSpanStaffCode","Staff Code"],
	["pageSpanStaffName","Staff Name"],
	["pageSpanStaffMobile","Staff Mobile"],
	["pageSpanStaffNearestStation","Staff Nearest Station"],
	["pageSpanSalaryPaymentMethod","Salary Payment Method"],
	["pageSpanSalaryPaymentForm","Salary Payment Form"],
	["pageSpanStandardClosingDate","Standard Closing Date"],
	["pageSpanTheTargetDate","The Target Date"],
	["pageSpanNumberOfSalaries","Number of Salaries"],
	["buttonSaveInformation","Save Information"],
	["accordionSalaryInformation","Salary Information"],
	["pageSpanTargetPeriod","Target Period"],
	["pageSpanTitleSupply","Supply"],
	["pageSpanSalaryAllowance","(S) Salary Allowance"],
	["payrollSalaryAllowanceHelp","* Including taxable allowance amount"],
	["pageSpanOtherPayment","(S) Other Payment"],
	["pageSpanAdvancePayment","(S) Advance Payment"],
	["pageSpanTaxExemptionAllowance","(S) Tax Exemption Allowance"],
	["pageSpanPaidDays","Paid Days"],
	["pageSpanPaidAmount","(S) Paid Amount"],
	["pageSpanSubtotal","Subtotal"],
	["pageSpanSubtotalHelp","Salary allowance + Other payment + Advance payment + Tax exemption allowance + Paid amount"],
	["pageSpanSubtotalHelpDaily","Salary allowance + Advance payment + Tax exemption allowance + Paid amount"],
	["pageSpanTaxable","(S) Taxable"],
	["pageSpanTaxableHelp","salary allowance + other payment + paid amount"],
	["pageSpanTaxableHelpDaily","salary allowance + paid amount"],
	["pageSpanTitleDeduction","Deduction"],
	["pageSpanPrepaidAmount","(S) Prepaid Amount"],
	["pageSpanOtherDeductions","(S) Other Deductions"],
	["pageSpanHealthInsurancePremium","(S) Health Insurance Premium"],
	["pageSpanWelfarePensionPremium","(S) Welfare Pension Premium"],
	["pageSpanLongTermCareInsurance","(S) Long-term Care Insurance Premium"],
	["pageSpanEmploymentInsurance","(S) Employment Insurance premium"],
	["pageSpanIncomeTax","(S) Income Tax"],
	["pageSpanResidentTax","(S) Resident Tax"],
	["pageSpanAbsenceDays","Absence Days"],
	["pageSpanAbsenceDeductionAmount","(S) Absence Deduction Amount"],
	["pageSpanNumberDaysLeaveEarly","Number of Days to Leave early"],
	["pageSpanEarlyDepartureDeductionAmount","(S) Early Departure Deduction Amount"],
	["pageSpanSubtotalDeduction","Subtotal"],
	["pageSpanSubtotalDeductionHelp","Prepaid amount + Other deduction + Income tax  + Absence deduction amount + Early departure deduction amount"],
	["buttonSaveSalaryInformation","Save Information"],
	["accordionBonusInformation","Bonus Information"],
	["pageSpanTitleSupply","Supply"],
	["pageSpanBonusAmount","(S) Bonus Amount"],
	["buttonCalculateBonusSocialInsurance","Calculate Bonus Social Insurance Premium"],
	["pageSpanTitleDeduction","Deduction"],
	["pageSpanHealthInsurancePremium","(S) Health Insurance Premium"],
	["pageSpanWelfarePensionPremium","(S) Welfare Pension Premium"],
	["pageSpanLongTermCareInsurance","(S) Long-term Care Insurance Premium"],
	["pageSpanEmploymentInsurance","(S) Employment Insurance premium"],
	["pageSpanIncomeTax","(S) Income Tax"],
	["pageSpanSubtotalDeduction","Subtotal"],
	["pageSpanBonusSocialInsuranceHelp","Bonus Social Insurance premium"],
	["pageSpanTotalDeductionPayment","Total Deduction Payment"],
	["pageSpanTotalPayment","Total Payment"],
	["totalPaymentHelp","Payment-deduction"],
	["buttonSaveBonusInformation","Save Information"],
	["accordionWorkInformationList","Work Information List"],
	["tableSearchTHNo","No"],
	["tableWorkInfoTHImplementationDate","Implementation Date"],
	["tableWorkInfoTHCase","Case"],
	["tableWorkInfoTHScheduledActualWork","Scheduled actual work time"],
	["tableWorkInfoTHStart","Start"],
	["tableWorkInfoTHEnd","End"],
	["tableWorkInfoTHBreakTime","Break Time"],
	["tableWorkInfoTHInsideMidnightBreak","Inside Midnight break time"],
	["tableWorkInfoTHActualWorkingHours","Actual Working Hours"],
	["tableWorkInfoTHOvertimeHours","Overtime Hours"],
	["tableWorkInfoTHMidnightWorkingours","Midnight Working hours"],
	["tableWorkInfoTHBasicSalary","Basic Salary"],
	["tableWorkInfoTHOvertimeCosts","Overtime Costs"],
	["tableWorkInfoTHMidnightLaborCosts","Midnight Labor costs"],
	["tableWorkInfoTHHolidayLaborCosts","Holiday  Labor costs"],
	["tableWorkInfoTHAllowance","Allowance"],
	["tableWorkInfoTHTransportationExpenses","Transportation Expenses"],
	["tableWorkInfoTHPurchaseMoney","Purchase Money"],
	["tableWorkInfoTHTExpenses","Expenses"],
	["tableWorkInfoTHAccommodationFee","Accommodation fee"],
	["tableWorkInfoTHOthers","Others"],
	["tableWorkInfoTHTAdvancePayment","Advance Payment"],
	["tableWorkInfoTHOtherDeductions","Other deductions"],
	["tableWorkInfoTHDailySalaryMonthlySalaryDeduction","Daily salary monthly salary deduction"],
	["tableWorkInfoTHTotal","Total"],
	["tableWorkInfoTHPaid","Paid"],
	["buttonSaveWorkInformation","Save Information"],
	["accordionMonthlySalaryInformationList","Monthly Salary Information List"],
	["tableSearchTHNo","No"],
	["tableWorkInfoTHImplementationPeriod","Implementation Period"],
	["tableWorkInfoTHCase","Case"],
	["tableWorkInfoTHProjectSalaryUnit","Project Salary Unit price"],
	["tableWorkInfoTHBasicSalary","Basic Salary"],
	["pageSpanDontSendPaySlips","Don't Send Pay Slips to staff"],
	["pageSpanDontSendPaySlipsHelp","Select the checkbox if you do not want to email the pay slip to the staff"],
	["buttonSaveWorkInformation","Save Information"],
	["accordionApprovalLocationInfo","Approval Information"],
	["pageSpanApprovalDateAndTime","Approval Date and Time"],
	["pageSpanAuthorizer","Authorizer"],
	["pageSpanApprovalStatus","Approval Status"],
	["optionApprovalStatus","Select Approval Status"],
	["option1ApprovalStatus","Approved"],
	["option2ApprovalStatus","Unapproved"],
	["pageSpanApprovalStatusHelp1","* If you change to approval and save, the salary will be fixed. Please note that you will not be able to change it."],
	["pageSpanApprovalStatusHelp2","* If approved, a salary statement PDF will be sent to the staff by email."],
	["pageSpanApprovalStatusHelp3","* You can also download the pay slip from the following in Excel."],
	["pageSpanPaySlip","Pay Slip"],
	["buttonDownloadPayslips","Download Payslips in Excel"],
	["pageSpanRemarks","Remarks"],
	["buttonUpdatePaySlip","Update Pay Slip"],
	["pageTitlePayrollManagement","Payroll Management"],
	["pageSpanHeadingSalaryList","Salary List"],
	["pageSpanSubHeadingSalaryList","You can check salary information for each staff member according to the status of expense report submission."],
	["buttonSpanCSVOutputForPayroll","CSV Output for Payroll Transfer"],
	["buttonSpanBatchProcessingCSVOutput","Batch Processing CSV Output"],
	["buttonSpanBatchProcessingCSVInput","Batch Processing CSV Input"],
	["buttonSpanProcessedListCSV","Processed List CSV Output"],
	["pageSpanSearch","Search"],
	["pageLabelSalaryPaymentForm","Salary Payment Form"],
	//["optionsalaryPaymentForm","Select Salary Payment Form"],
	//["option1salaryPaymentForm","Daily/ Weekly Payment"],
	//["option2salaryPaymentForm","Monthly Payment"],
	["pageLabelTargetYear","Target Year"],
	["pageLabelTargetMonth","Target Month"],
	["pageOptionTargetMonth","Select Target Month"],
	["pageOptionJanuary","January"],
	["pageOptionFebruary","February"],
	["pageOptionMarch","March"],
	["pageOptionApril","April"],
	["pageOptionMay","May"],
	["pageOptionJune","June"],
	["pageOptionJuly","July"],
	["pageOptionAugust","August"],
	["pageOptionSeptember","September"],
	["pageOptionOctober","October"],
	["pageOptionNovember","November"],
	["pageOptionDecember","December"],
	["pageLabelSalaryClosingDate","Salary Closing Date"],
	["OptiontargetDate","Select Salary Closing Date"],
	//["OptiontargetDate0","The End of the month"],
	["OptiontargetDate1","1 st"],
	["OptiontargetDate2","2 nd"],
	["OptiontargetDate3","3 rd"],
	["OptiontargetDate4","4 th"],
	["OptiontargetDate5","5 th"],
	["OptiontargetDate6","6 th"],
	["OptiontargetDate7","7 th"],
	["OptiontargetDate8","8 th"],
	["OptiontargetDate9","9 th"],
	["OptiontargetDate10","10 th"],
	["OptiontargetDate11","11 th"],
	["OptiontargetDate12","12 th"],
	["OptiontargetDate13","13 th"],
	["OptiontargetDate14","14 th"],
	["OptiontargetDate15","15 th"],
	["OptiontargetDate16","16 th"],
	["OptiontargetDate17","17 th"],
	["OptiontargetDate18","18 th"],
	["OptiontargetDate19","19 th"],
	["OptiontargetDate20","20 th"],
	["OptiontargetDate21","21 st"],
	["OptiontargetDate22","22 nd"],
	["OptiontargetDate23","23 rd"],
	["OptiontargetDate24","24 th"],
	["OptiontargetDate25","25 th"],
	["OptiontargetDate26","26 th"],
	["OptiontargetDate27","27 th"],
	["OptiontargetDate28","28 th"],
	["OptiontargetDate29","29 th"],
	["OptiontargetDate30","30 th"],
	["OptiontargetDate31","31 st"],
	["pageLabelName","Name"],
	["pageLabelNameKatakana","Name Katakana"],
	["pageLabelStaffCode","Staff Code"],
	["pageLabelInChargeStaff","In Charge Staff"],
	["OptionSelectInChargeStaff","Select In charge staff"],
	["OptionSelectInChargeStaff1","In charge staff 1"],
	["OptionSelectInChargeStaff2","In charge staff 2"],
	["pageLabelBelonging","Belonging"],
	["clearAllBtn","Clear All"],
	["searchBtn","Search"],
	["pageCardDivTotalStaff","Total Number of Staff"],
	["pageCardDivDailyWeeklyPayments","Daily/ Weekly Payments"],
	["pageCardDivMonthlyPayments","Monthly Payments"],
	["home-basic-tab","Processed"],
	["profile-basic-tab","Unprocessed (Expense Report submitted)"],
	["contact-basic-tab","Unprocessed (Expense Report not submitted)"],
	["pageSpanSearchProcessed","Processed"],
	["pageSpanSearchProcessedHelp1","The dispatched staff whose daily salary has been confirmed is displayed. You can check the payment status (paid / unpaid) in the salary display part."],
	["pageSpanSearchProcessedHelp2","If you want to change the payment status, select the target item in the details ⇒ work information list, and select the salary payment check box for daily salary information."],
	["tableSearchTHNo","No"],
	["tableSearchTHChoice","Choice"],
	["tableSearchTHStaffMobile","Staff (mobile)"],
	["tableSearchTHSalaryPaymentMethod","Salary Payment Method"],
	["tableSearchTHClosingDate","Closing Date"],
	["tableSearchTHApprovalDate","Approval Date and Time"],
	["tableSearchTHAuthorizer","Authorizer"],
	["tableSearchTHSalary","Salary"],
	["tableSearchTHInChargeStaff","In Charge Staff"],
	["buttonSpanCheckAll","Check All"],
	["buttonSpanUncheckAll","Uncheck All"],
	["pageSpanSearchUnprocessedExpenseReport","Unprocessed (Expense Report submitted)"],
	["pageSpanSearchUnprocessedHelp","Dispatched staff whose daily salary has not been confirmed are displayed. To confirm the salary amount, click the 'Calculate salary information' button from the staff assignment details."],
	["tableSearchTHNo","No"],
	["tableSearchTHChoice","Choice"],
	["tableSearchTHStaffMobile","Staff (mobile)"],
	["tableSearchTHSalaryPaymentMethod","Salary Payment Method"],
	["tableSearchTHClosingDate","Closing Date"],
	["tableSearchTHImplementationDate","Implementation Date"],
	["tableSearchTHProjectTitle","Project Title"],
	["tableSearchTHWorkLocation","Work Location"],
	["tableSearchTHSalary","Salary"],
	["tableSearchTHInChargeStaff","In Charge Staff"],
	["buttonSpanCheckAll","Check All"],
	["buttonSpanUncheckAll","Uncheck All"],
	["pageSpanSearchUnprocessedExpenseNotReport","Unprocessed (Expense Report Not submitted)"],
	["pageSpanSearchUnprocessedNotHelp","Dispatched staff who have not submitted an expense report are displayed."],
	["tableSearchTHNo","No"],
	["tableSearchTHChoice","Choice"],
	["tableSearchTHStaffMobile","Staff (mobile)"],
	["tableSearchTHSalaryPaymentMethod","Salary Payment Method"],
	["tableSearchTHClosingDate","Closing Date"],
	["tableSearchTHImplementationDate","Implementation Date"],
	["tableSearchTHProjectTitle","Project Title"],
	["tableSearchTHWorkLocation","Work Location"],
	["tableSearchTHSalary","Salary"],
	["tableSearchTHInChargeStaff","In Charge Staff"],
	["buttonSpanCheckAll","Check All"],
	["buttonSpanUncheckAll","Uncheck All"],
	["selectSalaryPaymentForm","Select Salary Payment Form"],
	["selectSalaryPaymentFormDaily","Daily/ Weekly Payment"],
	["selectSalaryPaymentFormMonthly","Monthly Payment"],
	["targetYear","Enter Target Year"],
	["salaryListName","Enter Name"],
	["salaryListNameKatakana","Enter Name Katakana"],
	["staffCode","Enter Staff Code"],
	["salaryListBelonging","Enter Belonging"],
	["pageCardDivTotalProceedStaff","Total Proceed Staff"],
	["pageCardDivTotalUnprocessedSubmitted","Total Unprocessed Submitted"],
	["pageCardDivTotalUnprocessedNotSubmitted","Total Unprocessed Not Submitted"],
];


payrollErrorArray ={"E2140":"Cannot be empty!", 
					"E2141":"Invalid Target Year",	
					"E2142":"Invalid Name",	
					"E2143":"Invalid Name Katakana",
					"E2144":"Invalid Staff Code", ////////////////  
					"E2145":"Invalid Other Payment ",
					"E2146":"Invalid Prepaid Amount",
					"E2147":"Invalid Other Deductions",
					"E2148":"Invalid Absence Days",
					"E2149":"Invalid Absence Deduction Amount",
					"E2150":"Invalid Number of Days to Leave Early",
					"E2151":"Invalid Early Departure Deduction Amount",
					"E2152":"Invalid Bonus Amount",
					"E2153":"Invalid Health Insurance Premium ",
					"E2154":"Invalid Welfare Pension Premium",
					"E2155":"Invalid LongTerm Care Insurance  Premium",
					"E2156":"Invalid Employment Insurance  Premium",
					"E2157":"Invalid Income Tax",
					"E2158":"Invalid Paid Days",
					"E2159":"Invalid Paid Amount",
 				  	}

