function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(StaffShiftScheduleManagement);
    convertContentToLanguage(shiftScheduleDeitail);
	addShiftScheduleRow();
	onloadShiftSchedule();
}

TopMenu = [
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
];

LeftMenu = [
	["pageTitle", "Staff List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanCustomer", "Customer Management"],
	["menuSpanQuoMan", "Quotation Management"],
	["menuSpanInvoiceMan", "Invoice Management"],
	["menuSpanMatterMan", "Case Management"],
	["menuSpanAssignment", "Assignment Management"],
	["menuSpanStaff", "Staff Management"],
	["menuSpanShifftSchedule", "Staff Shift Schedule Management" ],
	["menuSpanAttendance", "Attendance"],
	["menuSpanPayrollMan", "Payroll Management"],
	["menuSpanAnnualPayroll", "Annual Payroll"],
	["menuSpanPaidGrand", "Paid Grant"],
	["menuSpanEmployeeManagement", "Employee Management"],
	["menuSpanAgencyManagement", "Agency Management"],
	["menuSpanStaffPageLogin", "Staff Page Login"],
	["menuSpanMasterAdmin", "Master Admin"],
	["menuSubSpanCompanyInformationManagement", "Company Information"],
	["menuSubSpanConsumptionTaxManagement", "Consumption Tax"],
	["menuSubSpanDailyIncomeTax", "Income Tax Daily"],
	["menuSubSpanMonthlyTaxManagement", "Monthly Tax"],
	["menuSubSpanAllowanceManagement", "Over Time/Holiday Allowance"],
	["menuSubSpanPaidTableManagement", "Paid Table"],
	["menuSubSpanContractTerms", "Contract Terms"],
	["menuSubSpanEmailTemplateManagement", "Email Template"],
	["menuSubSpanQuoteTemplateManagement", "Quote Template"],
	["menuSpanAboutCompliance", "About Compliance"],
	["menuTermsofServices", "Terms of Services"],
	["menuPrivacyPolicy", "Privacy Policy"],
	["menuBasedCommercial", "Transaction Laws"]
];

StaffShiftScheduleManagement = [
	["pageTitleStaffList", "Staff List"],
    ["pageSpanHeading", "Staff Shift Schedule List"],
	["pageSpanHeadingHelpStaffShift", "You can check the staff shift schedule in a list. You can send a remainder email to staff who have not submitted shift schedule"],
    ["buttonOutputShiftSchedule", "Output Shift Schedule List CSV"],
    ["pageSpanSearch", " Search"],
    ["pageLabelTargetYear", "Target Year"],
    ["targetYear", "Enter Target Year"],
    ["pageLabelName", "Name"],
    ["name", "Enter Name"],
    ["pageLabelDispathClassification", "Dispath Classification"],
    //["dispathClassification", "Enter Dispath Classification"],
    ["pageTargetDate", "Target Date"],
    //["targetDate", "Enter Target Date"],
    ["pageLabelAddress", " Address"],
    ["address", "Enter Address"],
    ["pageLabelExperience", "Experience"],
    ["experience", "Enter Experience"],
    ["pageLabelTargetMonth", "Target Month"],
    //["targetMonth", "Enter Target Month"],
    ["pageLabelStaff", "Staff"],
    //["staff", "Enter Staff"],
    ["pageLabeloccupationClassification", "Occupation Classification"],
    //["occupationClassification", "Enter Occupation Classification"],
    ["pageLabelAttendanceStatus", "Attendance Status"],
    //["attendanceStatus", "Enter Attendance Status"],
    ["pageLabelDateofBirthFrom", "Date of Birth From"],
    ["pageLabelAttribute", "Attribute"],
    ["attribute", "Enter Attribute"],
    ["pageLabelstaffCode", "Staff Code"],
    ["staffCode", "Enter Staff Code"],
    ["pageLabelShiftSubmissionCategory", "Shift Submission Category"],
    ["pageOption0Attribute", "Select Shift Submission Category"],
    ["pageLabelBelongs", "Belongs"],
    ["optionSelectBelongs", "Select belongs"],
    ["belongs", "Enter belongs"],
    ["pageLabelPrefectures", "Prefectures"],
    //["prefectures", "Enter Prefectures"],
    ["pageLabelDateofBirthTo", "Date of Birth To"],
    ["dateofBirthTo", "Enter Date of Birth"],
    ["pageLabelGender", "Gender"],
    //["gender", "Enter Gender"],
    ["clearAllBtn", "Clear All"],
    ["searchBtn", "Search"],
    ["pageCardDivTotalNumberofShiftSchedule", "Total Number of Shift Schedule"],
    ["pageCardDivTotalNumberofStaffShiftSchedule", "Total Number of Staff Shift Schedule"],
    ["pageCardDivSubmittedShiftSchedule", "Submitted Shift Schedule"],
    ["pageCardDivPendingShiftSchedule", "Pending Shift Schedule"],
    ["pageSpanSearchStaffDetails", " Search Staff Details"],
    ["tableSearchStaffTHNo", "No"],
    ["tableSearchStaffTHChoice", "Choice"],
    ["tableSearchStaffTHName", "Name"],
    ["tableSearchStaffTHMobileE-MailAddress", "Mobile/E-Mail Address"],
    ["tableSearchStaffTHPrefectureAttribute", "Prefecture/Attribute"],
    ["tableSearchStaffTHPrivateMemo", "Private Memo"],
    ["tableSearchStaffTHSubmissionDateandTime", "Submission Date and Time"],
    ["tableSearchStaffTHStaffstaff", "Staff staff"],
    ["tableSearchStaffTHStaffCode", "Staff Code"],
    ["buttonSpanCheckAll", "Check All"],
    ["buttonSpanUncheckAll", "Uncheck All"],
    ["buttonsendNotificationEmail", "Send Notification Email in Bulk"],
    ["buttonSubmissionRemainderEmail", "Submission Remainder Email Batch Transmission"],
    ["pageOptionSelectTargetMonth", "Select Target Month"],
    ["pageOptionJanuary", "January"],
    ["pageOptionFebruary", "February"],
    ["pageOptionMarch", "March"],
    ["pageOptionApril", "April"],
    ["pageOptionMay", "May"],
    ["pageOptionJune", "June"],
    ["pageOptionJuly", "July"],
    ["pageOptionAugust", "August"],
    ["pageOptionSeptember", "September"],
    ["pageOptionOctober", "October"],
    ["pageOptionNovember", "November"],
    ["pageOptionDecember", "December"],
    ["optionPersonInCharge", "Select Person In Charge of the case"],
	["optionPersonInCharge1", "Person In Charge 1"],
	["optionPersonInCharge2", "Person In Charge 2"],
	["pageOptionSelectShiftSubmissionCategory", "Select Shift Submission Category"],
	["pageOptionShiftnotSubmitted", "Shift not Submitted"],
	["pageOptionShiftSubmitted", "Shift Submitted"],
	["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
	["pageSpanGeneralDispatch", "General Dispatch"],
	["pageSpanBusinessContract", "Out Sourcing"],
	["pageSpanIntroductionDispatching", "Temp-to-Perm"],
	["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
	["pageSpanPartTime", "Part Time"],
	["selectOptionSelectOccupationClassification", "Select Occupation Classification"],
	["pageSpanOfficeSystem", "Office System"],
    ["pageSpanSalesSystem", "Sales / Sales System"],
    ["pageSpanITCreative", "IT / Creative"],
    ["pageSpanMedicalWelfareSystem", "Medical/Welfare System"],
    ["pageSpanManufacturingBusiness", "Manufacturing Business"],
    ["pageSpanProfessional", "Professional"],
    ["pageSpanOthers", "Others"],
    ["OptiontargetDate", "Select Target Date"],
    ["OptiontargetDate1","1 st"],
	["OptiontargetDate2","2 nd"],
	["OptiontargetDate3","3 rd"],
	["OptiontargetDate4","4 th"],
	["OptiontargetDate5","5 th"],
	["OptiontargetDate6","6 th"],
	["OptiontargetDate7","7 th"],
	["OptiontargetDate8","8 th"],
	["OptiontargetDate9","9 th"],
	["OptiontargetDate10","10 th"],
	["OptiontargetDate11","11 th"],
	["OptiontargetDate12","12 th"],
	["OptiontargetDate13","13 th"],
	["OptiontargetDate14","14 th"],
	["OptiontargetDate15","15 th"],
	["OptiontargetDate16","16 th"],
	["OptiontargetDate17","17 th"],
	["OptiontargetDate18","18 th"],
	["OptiontargetDate19","19 th"],
	["OptiontargetDate20","20 th"],
	["OptiontargetDate21","21 st"],
	["OptiontargetDate22","22 nd"],
	["OptiontargetDate23","23 rd"],
	["OptiontargetDate24","24 th"],
	["OptiontargetDate25","25 th"],
	["OptiontargetDate26","26 th"],
	["OptiontargetDate27","27 th"],
	["OptiontargetDate28","28 th"],
	["OptiontargetDate29","29 th"],
	["OptiontargetDate30","30 th"],
	["OptiontargetDate31","31 st"],
    ["OptionattendanceStatusSelectAttendance", "Select Attendance Status"],
    ["selectWorkAvailabilityUnanswered", " Unanswered"],
    ["selectOptionSelectPrefectures", "Select Prefecture"],
    ["pageOption1Prefecture", "Hokkaido"],
     ["pageOption2Prefecture", "Aomori"],
     ["pageOption3Prefecture", "Iwate"],
     ["pageOption4Prefecture", "Miyagi"],
     ["pageOption5Prefecture", "Akita"],
     ["pageOption6Prefecture", "Yamagata"],
     ["pageOption7Prefecture", "Fukushima"],
     ["pageOption8Prefecture", "Ibaraki"],
     ["pageOption9Prefecture", "Tochigi"],
     ["pageOption10Prefecture", "Gunma"],
     ["pageOption11Prefecture", "Saitama"],
     ["pageOption12Prefecture", "Chiba"],
     ["pageOption13Prefecture", "Tokyo"],
     ["pageOption14Prefecture", "Kanagawa"],
     ["pageOption15Prefecture", "Niigata"],
     ["pageOption16Prefecture", "Toyama"],
     ["pageOption17Prefecture", "Ishikawa"],
     ["pageOption18Prefecture", "Fukui"],
     ["pageOption19Prefecture", "Yamanashi"],
     ["pageOption20Prefecture", "Nagano"], // changed
     ["pageOption21Prefecture", "Gifu"], // changed
     ["pageOption22Prefecture", "Shizuoka"],
     ["pageOption23Prefecture", "Aichi"],
     ["pageOption24Prefecture", "Mie"],
     ["pageOption25Prefecture", "Shiga"],
     ["pageOption26Prefecture", "Kyoto"],
     ["pageOption27Prefecture", "Osaka"],
     ["pageOption28Prefecture", "Hyogo"],
     ["pageOption29Prefecture", "Nara"],
     ["pageOption30Prefecture", "Wakayama"],
     ["pageOption31Prefecture", "Tottori"],
     ["pageOption32Prefecture", "Shimane"],
     ["pageOption33Prefecture", "Okayama"],
     ["pageOption34Prefecture", "Hiroshima"],
     ["pageOption35Prefecture", "Yamaguchi"],
     ["pageOption36Prefecture", "Tokushima"],
     ["pageOption37Prefecture", "Kagawa"],
     ["pageOption38Prefecture", "Ehime"],
     ["pageOption39Prefecture", "Kochi"],
     ["pageOption40Prefecture", "Fukuoka"],
     ["pageOption41Prefecture", "Saga"],
     ["pageOption42Prefecture", "Nagasaki"],//changed
     ["pageOption43Prefecture", "Kumamoto"],
     ["pageOption44Prefecture", "Oita"], // changed
     ["pageOption45Prefecture", "Miyazaki"],
     ["pageOption46Prefecture", "Kagoshima"],
     ["pageOption47Prefecture", "Okinawa"],
     ["selectOptionSelectGender", "Select Gender"],
     ["selectOptionSelectGenderMale", "Male"],
     ["selectOptionSelectGenderFemale", "Female"],
     ["shiftScheduleName", "Enter Name"],
];

shiftScheduleDeitail =[
	["pageTitleStaffShiftSchedule","Staff Shift Schedule"],
	["pageSpanHeadingStaffShiftSchedule","Staff Shift Schedule"],
	["pageSpanSubHeadingStaffShiftSchedule","You can modify the staff shift schedule and check the assignment status of this staff."],
	["buttonSpanAssignmentList","Assignment List"],
	["buttonSpanReturn","Return"],
	["pageSpanStaffShiftScheduleName","Name"],
	["pageSpanNameKatakana","Name Katakana"],
	["pageSpanStaffCode","Staff Code"],
	["pageSpanSubmissionDate","Submission Date and Time"],
	["tableShiftScheduleTHDate","Date"],
	["spanStaffShiftScheduleWorkAvailability","(S) Work Availability"],
	["selectWorkAvailability1","O"],
	["selectWorkAvailability2","&#916;"],
	["selectWorkAvailability3","X"],
	["tableShiftScheduleTHPublicMemo","(S) Public Memo"],
	["tableShiftScheduleTHPrivateMemo","Private Memo"],
	["pageSpanPrivateMemo","Private Memo (for displaying the staff shift list screen)"],
	["pageSpanRemarks","Remarks"],
	["pageSpanConfirmationDateAndTime","Confirmation Date and Time"],
	["pageSpanConfirmationPerson","Confirmation Person"],
	["selectConfirmationPerson","Select Confirmation Person"],
	["selectConfirmationPerson1","Confirmation Person 1"],
	["selectConfirmationPerson2","Confirmation Person 2"],
	["buttonUpdateStaffShiftSchedule","Update Staff Shift Schedule"]
];

