function switchLanguage(siteLanguage) {
  //  convertContentToLanguage(TopMenu);
  //  convertContentToLanguage(LeftMenu);
  //  convertContentToLanguage(StaffManagement);
  //  convertContentToLanguage(StaffDetails);
  //  convertContentToLanguage(StaffBatchRegister);
  //  convertContentToLanguage(InChargeStaffChange);
  //  convertTitleToLanguageByName(TitleList);
}

TopMenu = [
 
    ["menuButtonProfile", "Profile"],
    ["menuButtonManual", "Manual"],
    ["menuButtonLogout", "Logout"]
    ["pageTitle", "Item List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanItemList", "Item List"],
	["menuSpanShiftScheduleRegistration", "Shift Schedule"],
	["menuSpanMonthlyAttendanceList", "Attendance List"],
	["menuSpanStaffInformation", "Staff Information"]
];

LeftMenu = [
	["pageTitle", "Item List"],
	["menuSpanHome", "Home"],
	["menuSubSpanHome", "Home"],
	["menuSpanItemList", "Item List"],
	["menuSpanShiftScheduleRegistration", "Shift Schedule"],
	["menuSpanMonthlyAttendanceList", "Attendance List"],
	["menuSpanStaffInformation", "Staff Information"]
];



TitleList = [
	["viewDetails", "View Details"],
	["shiftSchedule", "View Shift Schedule"],
	["assignmentList", "View Assignment List"],
	["pageSpanAge", "years old /"],
];


StaffManagement = [
     ["pageSpanHeading", "Staff List"],
     ["buttonSpanStaffReg", "Staff Registration"],
     ["buttonSpanBatchReg", "Batch Registration"],
     ["buttonSpanStaffListCSV", "Staff List CSV Output"],
     ["pageSpanSearch", "Search"],
     ["pageLabelGivenNames", "Given Names"],
     ["givenNames", "Enter Given Names"],
     ["pageLabelNameKatakana", "Name Katakana"],
     ["nameKatakana", "Enter Name Katakana"],
     ["pageLabelStaffCode", "Staff Code"],
     ["staffCode", "Enter Staff Code"],
     ["pageLabelPrefectures", "Prefectures"],
     ["selectOptionSelectPrefectures", "Select Prefecture"],
     ["pageLabelStreetAddress", "Street Address"],
     ["streetAddress", "Enter Street Address"],
     ["pageLabelDOB", "Date of Birth"],
     ["dateOfBirthFrom", "From"],
     ["dateOfBirthTo", "To"],
     ["pageLabelMobilePhone", "Mobile Phone"],
     ["mobilePhone", "Enter Mobile Number"],
     ["pageLabelStaffStaff", "In Charge Staff"],
     ["staffInChargeStaff", "Enter In Charge Staff"],
     ["pageLabelMailAddress", "Mail Address"],
     ["mailAddress", "Enter Mail Address"],
     ["pageLabelExperience", "Experience"],
     ["experience", "Enter Experience"],
     ["pageLabelRegistrationDivision", "Registration Division"],
     ["selectOptionSelectRegistrationDevision", "Select Registration Division"],
     ["selectOptionSelectRegistrationDevision1", "Main registration"],
     ["selectOptionSelectRegistrationDevision2", "Temporary registration"],
     ["pageLabelDispatchClassification", "Dispatch Classification"],
     ["selectOptionSelectDispatchClassification", "Select Dispatch Classification"],
     ["pageLabelOccupationClassification", "Occupation Classification"],
     ["selectOptionSelectOccupationClassification", "Select Occupation Classification"],
     ["pageLabelAttribute", "Attribute"],
     ["pageOption0Attribute", "Select Attribute"],
     ["pageOption1Attribute", "Elderly (65+)"],
     ["pageOption2Attribute", "Foreign Student"],
     ["pageOption3Attribute", "Foreign Workers"],
     ["pageOption4Attribute", "High schooler"],
     ["attribute", "Enter Attribute"],
     ["pageLabelValidClassification", "Valid Classification"],
     ["selectOptionSelectValidClassification", "Select Valid Classification"],
     ["pageLabelCurrentUnitPrice", "Current Unit Price"],
     ["unitPriceFrom", "From"],
     ["unitPriceTo", "To"],
     ["pageLabelBelongs", "Belongs"],
     ["belongs", "Enter Belongs"],
     ["pageLabelGender", "Gender"],
     ["selectOptionSelectGender", "Select Gender"],
     ["selectOptionSelectGenderMale", "Male"],
     ["selectOptionSelectGenderFemale", "Female"],
     ["selectOptionSelectGender_1", "Select Gender"],
     ["selectOptionSelectGenderMale_1", "Male"],
     ["selectOptionSelectGenderFemale_1", "Female"],
     ["clearAllBtn", "Clear All"],
     ["searchBtn", "Search"],
     ["pageCardDivTotalStaff", "Total Number of Staff"],
     ["pageCardDivTotalActiveStaff", "Total Active Staff"],
     ["pageCardDivTotalAvailableStaff", "Total Available Staff"],
     ["pageCardDivTotalPendingStaff", "Total Pending Staff"],  
     ["pageSpanSearchStaffDetails", "Search Staff Details"],
     ["tableSearchStaffTHNo", "No"],
     ["tableSearchStaffTHChoice", "Choice"],
     ["tableSearchStaffTHName", "Name"],
     ["tableSearchStaffTHNameKatakana", "Name Katakana"],
     ["tableSearchStaffTHAttribute", "Attribute"],
     ["tableSearchStaffTHStaffCode", "Staff Code"],
     ["tableSearchStaffTHStaffStaff", "In Charge Staff"],
     ["tableSearchStaffTHCellPhone", "Cell Phone"],
     ["tableSearchStaffTHEmailAddress", "Email Address"],
     ["tableSearchStaffTHDispatchClassification", "Dispatch Classification"],
     ["tableSearchStaffTHPrefecture", "Prefecture"],
     ["tableSearchStaffTHPostalCode", "Postal Code"],
     ["tableSearchStaffTHExperience", "Experience"],
     ["tableSearchStaffTHAddress", "Address"],
     ["tableSearchStaffTHOccupationClassification", "Occupation Classification"],
     ["tableSearchStaffTHDOB", "Date of Birth/Age/Gender"],
     ["tableSearchStaffTHRegistrationCategory", "Registration Category/Valid Category"],
     ["tableSearchStaffTHUnitPrice", "Current Unit Price"],

     ["tableButtonDetails", "Details"],
     ["tableButtonScheduleShift", "Schedule Shift"],
     ["tableButtonAssignmentList", "Assignment List"],
     ["tableButtonDetails_2", "Details"],
     ["tableButtonScheduleShift_2", "Schedule Shift"],
     ["tableButtonAssignmentList_2", "Assignment List"],
     ["tableButtonDetails_3", "Details"],
     ["tableButtonScheduleShift_3", "Schedule Shift"],
     ["tableButtonAssignmentList_3", "Assignment List"],
     ["search_staff_table_previous", "Previous"],
     ["search_staff_table_next", "Next"],
     ["buttonSpanCheckAll", "Check All"],
     ["buttonSpanUncheckAll", "Uncheck All"],
     ["buttonSpanBatchDeletion", "Batch Deletion"],
     ["buttonSpanBatchChange", "Change In Charge Staff"],
     ["buttonSpanBatchChange", "Change In Charge Staff"],
     ["buttonSpanBatchChange", "Change In Charge Staff"],
     ["buttonSpanBatchChange", "Change In Charge Staff"],
     ["selectInchargeofStaff", "Select Incharge of Staff"],
    
];


StaffDetails = [
        ["pageSpanHeadingStaffInformation", "Staff Information"],
        ["pageTitleStaffInformation", "Staff Information"],
        ["pageSpanHeadingStaffDetails", "Staff Details"],
        ["pageSpanHeadingStaffRegister", "Staff Registration"],
        ["pageSpanSubHeadingStaffDetails", "You can modify the staff  check the shift schedule of this staff and check the assignment status."],
        ["buttonSpanStaffDetailsOption", "Option"],
        ["buttonValueSpanStaffDetailsRegister", "Register Staff"],
        ["buttonValueSpanStaffDetailsDelete", "Delete Staff"],
        ["buttonSpanScheduledShifts", "Scheduled Shifts"],
        ["buttonSpanAssinmentList", "Assignment List"],
        ["buttonSpanReturn", "Return"],

        ["accordionDivStaffInformation", "Staff Information"],
        ["accordionDivTransportationInformation", "Transportation Information"],
        ["accordionDivResumeInformation", "Resume Information"],
        ["accordionDivPayrollInformation", "Payroll Information"],
        ["accordionDivSocialInsuranceInformation", "Social Insurance / Income Tax / Resident Tax Information"],
        ["accordionDivLoginInformation", "Login Information"],
        ["accordionDivOtherInformation", "Other Information"],

     ["pageSpanName", "Name"],
     ["pageSpanHelpTextName", "Please put a space between the first and last name"],
     ["pageSpanNameKatakana", "Name Katakana"],
     ["pageSpanHelpTextNameKatakana", "Please put a space between the first and last name"],
     ["pageSpanZipCode", "Zip Code"],
     ["btnAddressSearch", "Address Search"],
     ["pageSpanHelpZipCode", "Please enter without hyphens"],
     ["pageSpanPrefecture", "Prefectures"],
     ["pageSpanAddress", "Address"],
     ["pageSpanHelpAddress", "Please be sure to enter the apartment name and building name"],
     ["pageSpanAddressKatakana", "Address Katakana"],
     ["pageSpanDateofBirth", "Date of Birth"],
     ["pageSpanGender", "Gender"],
     ["pageSpanMobile", "Mobile"],
     ["pageSpanHelpMobile", "Please enter without hyphens"],
     ["pageSpanHomeParent", "Home (parent's home)"],
     ["pageSpanFax", "Fax"],
     ["pageSpanHelpFax", "Please enter without hyphens"],
     ["pageSpanAttributeclassification1", "Attribute classification 1"],
     ["pageSpanAttributeclassification2", "Attribute classification 2"],
     ["pageSpanLaborManagementExpirationDate", "Labor-management agreement expiration date"],
     ["pageSpanAttribute", "Attribute"],
     ["pageSpanBelongs", "Belongs"],
     ["pageSpanDisClassification", "Dispatch classification"],
     ["pageSpanGeneralDispatch", "General Dispatch"],
     ["pageSpanBusinessContract", "Out Sourcing"],
     ["pageSpanIntroductionDispatching", "Temp-to-Perm"],
     ["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement"],
     ["pageSpanPartTime", "Part Time"],
     ["pageSpanOccuClassification", "Occupation Classification"],
     ["pageSpanOfficeSystem", "Office System"],
     ["pageSpanSalesSystem", "Sales / Sales System"],
     ["pageSpanITCreative", "IT / Creative"],
     ["pageSpanMedicalWelfareSystem", "Medical/Welfare System"],
     ["pageSpanManufacturingBusiness", "Manufacturing Business"],
     ["pageSpanProfessional", "Professional"],
     ["pageSpanOthers", "Others"],
     ["pageSpanDailySalaryUnitPrice", "Daily salary unit price"],
     ["pageSpanHelpDailySalaryUnitPrice", "This unit price will be referred to when the paid calculation method is set to regular wages."],
     ["pageSpanHourlyWageUnitPrice", "Hourly Wage Unit Price"],
     ["pageSpanHelpHourlyWageUnitPrice", "Enter this if the unit price is fixed regardless of the job description."],
     ["pageSpanConflictDate", "Conflict Date (individual unit) list"],
     ["tableConflictDateTHNo", "No."],
     ["tableConflictDateTHProjectTitle", "Project Title"],
     ["tableConflictDateTHConflictDate", "Conflict date (individual unit)"],


     ["pageSpanNearestStation", "Nearest Station"],
     ["pageSpanTimeRequiredNearestStation", "Time required to reach the nearest station (minutes)"],
     ["pageSpanTransportationNearestStation", "Transportation to the nearest station"],
     ["pageSpanBusUseSectionFrom", "Bus use section From"],
     ["pageSpanHelpBusUseSectionFrom", "*Fill in only for bus users to the nearest station"],
     ["pageSpanBusUseSectionTo", "Bus use section To"],
     ["pageSpanHelpBusUseSectionTo", "*Fill in only for bus users to the nearest station"],
     ["pageSpanRoundTripBusFare", "Round-trip bus fare (yen)"],
     ["pageSpanHelpRoundTripBusFare", "*Fill in only for bus users to the nearest station"],
    
     ["pageSpanEducationalBackground", "Educational Background"],
     ["tableEducationalBackgroundTHYear", "Year"],
     ["tableEducationalBackgroundTHMonth", "Month"],
     ["tableEducationalBackgroundTHContent", "Contents"],
     ["pageSpanWorkHistory", "Work History"],
     ["pageSpanLicenceQualification", "License Qualification"],
     ["pageSpanHope", "Hope"],
     ["buttonOutputStaffResume", "Output Staff Resume"],

     ["pageSpanSalaryPaymentMethod", "Salary Payment Method"],
     ["selectOption", "Select Salary Payment Method"],
     ["selectOptionPersonalDelivery", "Personal Delivery"],
     ["selectOptionTransfer", "Transfer"],
     ["pageSpanSalaryPaymentForm", "Salary Payment Form"],
     ["selectOptionSalary", "Select Salary Payment Form"],
     ["selectOptionSalaryPaymentFormDailyWeekly", "Daily / Weekly payment"],
     ["selectOptionSalaryPaymentFormMonthly", "Monthly Payment"],
     ["pageSpanSalaryClosingDate", "Salary Closing Date"],
     ["selectOptionSalaryClosingDate", "Select Salary Closing Date"],
     ["selectOptionSalaryClosingDateTheEndOfTheMonth", "The end of the month"],
     ["selectOptionSalaryClosingDate1Day", "1 day"],
     ["selectOptionSalaryClosingDate2Day", "2 days"],
     ["selectOptionSalaryClosingDate3Day", "3 days"],
     ["selectOptionSalaryClosingDate4Day", "4 days"],
     ["selectOptionSalaryClosingDate5Day", "5 days"],
     ["selectOptionSalaryClosingDate6Day", "6 days"],
     ["selectOptionSalaryClosingDate7Day", "7 days"],
     ["selectOptionSalaryClosingDate8Day", "8 days"],
     ["selectOptionSalaryClosingDate9Day", "9 days"],
     ["selectOptionSalaryClosingDate10Day", "10 days"],
     ["selectOptionSalaryClosingDate11Day", "11 days"],
     ["selectOptionSalaryClosingDate12Day", "12 days"],
     ["selectOptionSalaryClosingDate13Day", "13 days"],
     ["selectOptionSalaryClosingDate14Day", "14 days"],
     ["selectOptionSalaryClosingDate15Day", "15 days"],
     ["selectOptionSalaryClosingDate16Day", "16 days"],
     ["selectOptionSalaryClosingDate17Day", "17 days"],
     ["selectOptionSalaryClosingDate18Day", "18 days"],
     ["selectOptionSalaryClosingDate19Day", "19 days"],
     ["selectOptionSalaryClosingDate20Day", "20 days"],
     ["selectOptionSalaryClosingDate21Day", "21 days"],
     ["selectOptionSalaryClosingDate22Day", "22 days"],
     ["selectOptionSalaryClosingDate23Day", "23 days"],
     ["selectOptionSalaryClosingDate24Day", "24 days"],
     ["selectOptionSalaryClosingDate25Day", "25 days"],
     ["selectOptionSalaryClosingDate26Day", "26 days"],
     ["selectOptionSalaryClosingDate27Day", "27 days"],
     ["selectOptionSalaryClosingDate28Day", "28 days"],
    
    
     ["pageSpanHelpSalaryPaymentMethod", "If you choose to transfer please enter your account information"],
     ["pageSpanPaidTarget", "Paid Target"],
     ["selectOptionPaidTargetYes", "Yes"],
     ["selectOptionPaidTargetNothing", "Nothing"],
     ["pageSpanPaidStartDate", "Paid Start Date"],
     ["pageSpanTransferFinancialInstitution", "Transfer Financial Institution Name"],
     ["pageSpanTransferBranchName", "Transfer Branch Name"],
     ["pageSpanHelpTransferBranchName", "For Japan Post Bank enter the store name (example: 1988)"],
     ["pageSpanBankCode", "Bank Code"],
     ["pageSpanHelpBankCode", "Not entered for Japan Post Bank"],
     ["pageSpanBranchCode", "Branch Code"],
     ["pageSpanHelpBranchCode", "For Japan Post Bank enter the store name (example: 1988)"],
     ["pageSpanAccountType", "Account Type"],
     ["selectOptionAccountTypeUsually", "Usually"],
     ["selectOptionAccountTypeCurrent", "Current"],
     ["selectOptionAccountTypeSavings", "Savings"],
     ["selectOptionAccountTypeOthers", "Others"],
     ["pageSpanAccountNumber", "Account Number"],
     ["pageSpanAccountName", "Account Name"],
 


     ["accordionDivSkillSheetInformation", "Skill Sheet Information"],
     ["pageSpanNameInitials", "Name (initials only)"],
     ["pageSpanCurrentAddress", "Current Address"],
     ["pageSpanHelpCurrentAddress", "Please enter the information of the address you want to display after the prefecture"],
     ["pageDivWorkHistory", "Work history (for skill sheet)"],
     ["pageSpanHelpWorkHistory", "Describe the career history since the last academic background. Listed by industry / industry with the company name hidden  such as 'Trading company D'  'Major advertising agency' and 'Service industry'."],
     ["tableSkillSheetInformationTHYear", "Year"],
     ["tableSkillSheetInformationTHMonth", "Month"],
     ["tableSkillSheetInformationTHContent", "Contents"],
     ["pageSpanRemarks", "Remarks"],
     ["staffSkillRemark", "If you have any particular requests regarding treatment, occupation, working hours, place of work, etc. enter them."],
     ["buttonOutputStaffSkillSheet", "Output Staff Skill Sheet"],




     ["pageSpanMyNumber", "My Number"],
     ["pageSocialInsuranceCoverage", "Social Insurance Coverage"],
     ["selectOptionSocialInsuranceCoverage", "Select Social Insurance Coverage"],
     ["selectOptionSocialInsuranceCoverageNotSubscribed", "Not Subscribed"],
     ["selectOptionSocialInsuranceCoverageSubscribed", "Subscribed"],
     ["pageSpanOpensocialinsurance", "Open social insurance / income tax / resident tax information"],
     ["pageSpanHealthInsuranceCoverage", "Health insurance coverage"],
     ["selectOptionHealthInsuranceCoverage", "Select Health insurance coverage"],
     ["selectOptionHealthInsuranceCoverageNotSubscribed", "Not Subscribed"],
     ["selectOptionHealthInsuranceCoverageSubscribed", "Subscribed"],
     ["selectOptionHealthInsuranceGrade", "Select Health insurance grade"],
     ["selectOptionWelfareHealthInsuranceCoverage", "Select Welfare pension insurance participation status"],
     ["selectOptionWelfareHealthInsuranceCoverageNotSubscribed", "Not Subscribed"],
     ["selectOptionWelfareHealthInsuranceCoverageSubscribed", "Subscribed"],
     ["selectOptionEmploymentInsuranceCoverageNotSubscribed", "Not Subscribed"],
     ["selectOptionEmploymentInsuranceCoverageSubscribed", "Subscribed"],
     ["pageSpanHealthInsuranceGrade", "Health insurance grade"],
     ["selectOptionHealthInsuranceGrade", "Select Health insurance grade"],
     ["selectOptionHealthInsuranceGradeNotSubscribed", "Not Subscribed"],
     ["selectOptionHealthInsuranceGradeGrade1", "Grade 1 to 63,000"],
     ["selectOptionHealthInsuranceGradeGrade2", "2nd Grade 63,000 to 73,000"],
     ["selectOptionHealthInsuranceGradeGrade3", "3rd Grade 73,000 to 83,000"],
     ["selectOptionHealthInsuranceGradeGrade4", "4th Grade 83,000 to 93,000"],
     ["selectOptionHealthInsuranceGradeGrade5", "5th Grade 93,000 to 101,000"],
     ["selectOptionHealthInsuranceGradeGrade6", "6th Grade 101,000 to 107,000"],
     ["selectOptionHealthInsuranceGradeGrade7", "7th Grade 107,000 to 114,000"],
     ["selectOptionHealthInsuranceGradeGrade8", "8th Grade 114,000 to 122,000"],
     ["selectOptionHealthInsuranceGradeGrade9", "9th Grade 122,000 to 130,000"],
     ["selectOptionHealthInsuranceGradeGrade10", "10th Grade 130,000 to 138,000"],
     ["selectOptionHealthInsuranceGradeGrade11", "11th Grade 138,000 to 146,000"],
     ["selectOptionHealthInsuranceGradeGrade12", "12th Grade 146,000 to 155,000"],
     ["selectOptionHealthInsuranceGradeGrade13", "13th Grade 155,000 to 165,000"],
     ["selectOptionHealthInsuranceGradeGrade14", "14th Grade 165,000 to 175,000"],
     ["selectOptionHealthInsuranceGradeGrade15", "15th Grade 175,000 to 185,000"],
     ["selectOptionHealthInsuranceGradeGrade16", "16th Grade 185,000 to 195,000"],
     ["selectOptionHealthInsuranceGradeGrade17", "17th Grade 195,000 to 210,000"],
     ["selectOptionHealthInsuranceGradeGrade18", "18th Grade 210,000 to 230,000"],
     ["selectOptionHealthInsuranceGradeGrade19", "19th Grade 230,000 to 250,000"],
     ["selectOptionHealthInsuranceGradeGrade20", "20th Grade 250,000 to 270,000"],
     ["selectOptionHealthInsuranceGradeGrade21", "21st Grade 270,000 to 290,000"],
     ["selectOptionHealthInsuranceGradeGrade22", "22nd Grade 290,000 to 310,000"],
     ["selectOptionHealthInsuranceGradeGrade23", "23rd Grade 310,000 to 330,000"],
     ["selectOptionHealthInsuranceGradeGrade24", "24th Grade 330,000 to 350,000"],
     ["selectOptionHealthInsuranceGradeGrade25", "25th Grade 350,000 to 370,000"],
     ["selectOptionHealthInsuranceGradeGrade26", "26th Grade 370,000 to 395,000"],
     ["selectOptionHealthInsuranceGradeGrade27", "27th Grade 395,000 to 425,000"],
     ["selectOptionHealthInsuranceGradeGrade28", "28th Grade 425,000 to 455,000"],
     ["selectOptionHealthInsuranceGradeGrade29", "29th Grade 455,000 to 485,000"],
     ["selectOptionHealthInsuranceGradeGrade30", "30th Grade 485,000 to 515,000"],
     ["selectOptionHealthInsuranceGradeGrade31", "31st Grade 515,000 to 545,000"],
     ["selectOptionHealthInsuranceGradeGrade32", "32nd Grade 545,000 to 575,000"],
     ["selectOptionHealthInsuranceGradeGrade33", "33rd Grade 575,000 to 605,000"],
     ["selectOptionHealthInsuranceGradeGrade34", "34th Grade 605,000 to 635,000"],
     ["selectOptionHealthInsuranceGradeGrade35", "35th Grade 635,000 to 665,000"],
     ["selectOptionHealthInsuranceGradeGrade36", "36th Grade 665,000 to 695,000"],
     ["selectOptionHealthInsuranceGradeGrade37", "37th Grade 695,000 to 730,000"],
     ["selectOptionHealthInsuranceGradeGrade38", "38th Grade 730,000 to 770,000"],
     ["selectOptionHealthInsuranceGradeGrade39", "39rd Grade 770,000 to 810,000"],
     ["selectOptionHealthInsuranceGradeGrade40", "40th Grade 810,000 to 855,000"],
     ["selectOptionHealthInsuranceGradeGrade41", "41st Grade 855,000 to 905,000"],
     ["selectOptionHealthInsuranceGradeGrade42", "42nd Grade 905,000 to 965,000"],
     ["selectOptionHealthInsuranceGradeGrade43", "43rd Grade 965,000 to 1,5,000"],
     ["selectOptionHealthInsuranceGradeGrade44", "44th Grade 1,5,000 to 1,55,000"],
     ["selectOptionHealthInsuranceGradeGrade45", "45th Grade 1,55,000 to 1,115,000"],
     ["selectOptionHealthInsuranceGradeGrade46", "46th Grade 1,115,000 to 1,175,000"],
     ["selectOptionHealthInsuranceGradeGrade47", "47th Grade 1,175,000 to 1,235,000"],
     ["selectOptionHealthInsuranceGradeGrade48", "48th Grade 1,235,000 to 1,295,000"],
     ["selectOptionHealthInsuranceGradeGrade49", "49th Grade 1,295,000 to 1,355,000"],
     ["selectOptionHealthInsuranceGradeGrade50", "50th Grade 1,355,000 ~ "],
    
     ["selectOptionWelfarePensionInsuranceGrade2", "Grade 1 - 93,000"],
     ["selectOptionWelfarePensionInsuranceGrade3", "2nd Grade 93,000 - 101,000"],
     ["selectOptionWelfarePensionInsuranceGrade4", "3rd Grade 101,000 - 107,000"],
     ["selectOptionWelfarePensionInsuranceGrade5", "4th Grade 107,000 - 114,000"],
     ["selectOptionWelfarePensionInsuranceGrade6", "5th Grade 114,000 - 122,000"],
     ["selectOptionWelfarePensionInsuranceGrade7", "6th Grade 122,000 - 130,000"],
     ["selectOptionWelfarePensionInsuranceGrade8", "7th Grade 130,000 - 138,000"],
     ["selectOptionWelfarePensionInsuranceGrade9", "8th Grade 138,000 - 146,000"],
     ["selectOptionWelfarePensionInsuranceGrade10", "9th Grade 146,000 - 155,000"],
     ["selectOptionWelfarePensionInsuranceGrade11", "10th Grade 155,000 - 165,000"],
     ["selectOptionWelfarePensionInsuranceGrade12", "11th Grade 165,000 - 175,000"],
     ["selectOptionWelfarePensionInsuranceGrade13", "12th Grade 175,000 - 185,000"],
     ["selectOptionWelfarePensionInsuranceGrade14", "13th Grade 185,000 - 195,000"],
     ["selectOptionWelfarePensionInsuranceGrade15", "14th Grade 195,000 - 210,000"],
     ["selectOptionWelfarePensionInsuranceGrade16", "15th Grade 210,000 - 230,000"],
     ["selectOptionWelfarePensionInsuranceGrade17", "16th Grade 230,000 - 250,000"],
     ["selectOptionWelfarePensionInsuranceGrade18", "17th Grade 250,000 - 270,000"],
     ["selectOptionWelfarePensionInsuranceGrade19", "18th Grade 270,000 - 290,000"],
     ["selectOptionWelfarePensionInsuranceGrade20", "19th Grade 290,000 - 310,000"],
     ["selectOptionWelfarePensionInsuranceGrade21", "20th Grade 310,000 - 330,000"],
     ["selectOptionWelfarePensionInsuranceGrade22", "21st Grade 330,000 - 350,000"],
     ["selectOptionWelfarePensionInsuranceGrade23", "22nd Grade 350,000 - 370,000"],
     ["selectOptionWelfarePensionInsuranceGrade24", "23rd Grade 370,000 - 395,000"],
     ["selectOptionWelfarePensionInsuranceGrade25", "24th Grade 395,000 - 425,000"],
     ["selectOptionWelfarePensionInsuranceGrade26", "25th Grade 425,000 - 455,000"],
     ["selectOptionWelfarePensionInsuranceGrade27", "26th Grade 455,000 - 485,000"],
     ["selectOptionWelfarePensionInsuranceGrade28", "27th Grade 485,000 - 515,000"],
     ["selectOptionWelfarePensionInsuranceGrade29", "28th Grade 515,000 - 545,000"],
     ["selectOptionWelfarePensionInsuranceGrade30", "29th Grade 545,000 - 575,000"],
     ["selectOptionWelfarePensionInsuranceGrade31", "30th Grade 575,000 - 605,000"],
     ["selectOptionWelfarePensionInsuranceGrade32", "31st Grade 605,000 ~"],
    
    
    
    
     ["pageSpanWelfarePensionInsurance", "Welfare pension insurance participation status"],
     ["pageSpanWelfarePensionInsuranceGrade", "Welfare pension insurance grade"],
     ["pageSpanLongTermCareInsuranceParticipation", "Long-term care insurance participation status"],
     ["pageSpanEmploymentInsuranceCoverage", "Employment insurance coverage"],
     ["pageSpanHelpEmploymentInsuranceCoverage1", "Condition (1) Scheduled to work 20 hours or more per week", "Condition (2) Scheduled to be employed for 31 days or more"],
     ["pageSpanHelpEmploymentInsuranceCoverage2", "*However, please note that students are not eligible in principle"],
     ["pageSpanIncomeTaxTaxpayerClassification", "Income tax taxpayer classification"],
     ["pageSpanHelpIncomeTaxTaxpayerClassification", "Please select the dispatched staff who have submitted the declaration of dependent deductions for salaried workers \the dispatched staff who have not submitted the declaration of dependent deductions for salaried workers \and the dispatched staff who are day laborers or part-time workers."],
     ["pageSpanNumberofDependents", "Number of dependents"],
     ["pageSpanHelpNumberOfDependents", "Please enter the number of dependents directly. Please note that the number of dependent relatives may not match the actual number because the calculation method of the dependent deduction amount differs depending on the disability classification of the dependent relatives."],
     ["pageSpanDependents", "Dependents"],
     ["tableConflictDateTHFamilyName", "family name"],
     ["tableConflictDateTHNameKatakana", "Name katakana"],
     ["tableConflictDateTHBirthday", "Birthday"],
     ["tableConflictDateTHGender", "Gender"],
     ["tableConflictDateTHRelationship", "Relationship"],
     ["tableConflictDateTHClassification", "Classification"],
     ["tableConflictDateTHLivingTogether", "Living Together"],
     ["tableConflictDateTHHandicapped", "Handicapped"],
     ["tableConflictDateTHDuplicate", "Duplicate"],
     ["btnSpanDuplicateInTheBottomLine1", "Duplicate In The Bottom Line"],
     ["btnSpanDuplicateInTheBottomLine2", "Duplicate In The Bottom Line"],
     ["btnSpanDuplicateInTheBottomLine3", "Duplicate In The Bottom Line"],
     ["btnSpanDuplicateInTheBottomLine4", "Duplicate In The Bottom Line"],
     ["btnSpanDuplicateInTheBottomLine5", "Duplicate In The Bottom Line"],
     ["pageSpanResidentTaxClassification", "Resident tax classification"],
     ["pageSpanNormalCollection", "Normal Collection"],
     ["pageSpanSpecialCollection", "Special Collection"],


     ["pageSpanEmail", "Email address"],
     ["pageSpanHelpEmail1", "*It will be the ID to log in to the system"],
     ["pageSpanHelpEmail2", "*It will be the address to receive the business contact email"],
     ["pageSpanNewPassword", "NewPassword"],
     ["pageSpanHelpNewPassword", "*6 characters or more half-width alphanumeric characters"],
     ["pageSpanNewPasswordConfirm", "For new password confirmation"],
     ["pageSpanEmailAddressConfirm", "Email Address Confirmation"],
     ["pageSpanRegistrationDivision", "Registration Division"],
     ["pageSpanMainRegistration", "Main Registration"],
     ["pageSpanTemporaryRegistration", "Temporary  Registration"],
     ["pageSpanLineRegistration", "LINE Registration"],
     ["pageSpanUnregistered", "Unregistered"],

     ["pageSpanStaffCode", "Staff Code"],
     ["pageSpanFacePhoto", "Face Photo"],
     ["pageSpanHelpFacePhoto", "This is a face photo to be displayed in the list and resume."],
     ["pageSpanPreview", "Face Photo Preview"],
     ["pageSpanEmergencyContactName", "Emergency Contact Name"],
     ["pageSpanHelpEmergencyContactName", "Please put a space between the first and last name"],
     ["pageSpanEmergencyContactNameKatakana", "Emergency Contact Name Katakana"],
     ["pageSpanHelpEmergencyContactNameKatakana", "Please put a space between the first and last name"],
     ["pageSpanPostalCode", "Postal Code"],
     ["buttonSpanAddressSearch", "Address Search"],
     ["buttonSpanHelpAddressSearch", "Please enter without hyphens"],
     ["pageSpanPrefectures", "Prefectures"],
    
     ["pageOption1Prefecture", "Hokkaido"],
     ["pageOption2Prefecture", "Aomori"],
     ["pageOption3Prefecture", "Iwate"],
     ["pageOption4Prefecture", "Miyagi"],
     ["pageOption5Prefecture", "Akita"],
     ["pageOption6Prefecture", "Yamagata"],
     ["pageOption7Prefecture", "Fukushima"],
     ["pageOption8Prefecture", "Ibaraki"],
     ["pageOption9Prefecture", "Tochigi"],
     ["pageOption10Prefecture", "Gunma"],
     ["pageOption11Prefecture", "Saitama"],
     ["pageOption12Prefecture", "Chiba"],
     ["pageOption13Prefecture", "Tokyo"],
     ["pageOption14Prefecture", "Kanagawa"],
     ["pageOption15Prefecture", "Niigata"],
     ["pageOption16Prefecture", "Toyama"],
     ["pageOption17Prefecture", "Ishikawa"],
     ["pageOption18Prefecture", "Fukui"],
     ["pageOption19Prefecture", "Yamanashi"],
     ["pageOption20Prefecture", "Nagano"], // changed
     ["pageOption21Prefecture", "Gifu"], // changed
     ["pageOption22Prefecture", "Shizuoka"],
     ["pageOption23Prefecture", "Aichi"],
     ["pageOption24Prefecture", "Mie"],
     ["pageOption25Prefecture", "Shiga"],
     ["pageOption26Prefecture", "Kyoto"],
     ["pageOption27Prefecture", "Osaka"],
     ["pageOption28Prefecture", "Hyogo"],
     ["pageOption29Prefecture", "Nara"],
     ["pageOption30Prefecture", "Wakayama"],
     ["pageOption31Prefecture", "Tottori"],
     ["pageOption32Prefecture", "Shimane"],
     ["pageOption33Prefecture", "Okayama"],
     ["pageOption34Prefecture", "Hiroshima"],
     ["pageOption35Prefecture", "Yamaguchi"],
     ["pageOption36Prefecture", "Tokushima"],
     ["pageOption37Prefecture", "Kagawa"],
     ["pageOption38Prefecture", "Ehime"],
     ["pageOption39Prefecture", "Kochi"],
     ["pageOption40Prefecture", "Fukuoka"],
     ["pageOption41Prefecture", "Saga"],
     ["pageOption42Prefecture", "Nagasaki"],//changed
     ["pageOption43Prefecture", "Kumamoto"],
     ["pageOption44Prefecture", "Oita"], // changed
     ["pageOption45Prefecture", "Miyazaki"],
     ["pageOption46Prefecture", "Kagoshima"],
     ["pageOption47Prefecture", "Okinawa"],
   
     ["staffGender0", "Select Gender"],
     ["staffGender1", "Male"],
     ["staffGender2", "Female"],
     ["pageSpanHelpMobile", "Please enter without hyphens"],
     ["pageSpanHelpHome", "Please enter without hyphens"],
     ["pageOption0AttributeClassification1", "Select Attribute classification 1"],
     ["pageOption1AttributeClassification1", "In-house"],
     ["pageOption2AttributeClassification1", "Out sourcing"],
     ["pageOption0AttributeClassification2", "Select Attribute classification 2"],
     ["pageOption1AttributeClassification2", "Fixed-term employment worker"],
     ["pageOption2AttributeClassification2", "Fixed-term employment workers(Dispatched Workers Subject to the agreement"],
     ["pageOption3AttributeClassification2", "Permanent Worker"],
     ["pageOption4AttributeClassification2", "Permanent Employment Workers(Dispatched Workers Subject to the agreement)"],
     ["pageOption0Attribute", "Select Attribute"],
    
    //RESUME INFO
     ["tableEducationalBackgroundTHDateFrom", "Date From"],
     ["tableEducationalBackgroundTHDateTo", "Date To"],
     ["tableEducationalBackgroundTHInstitute", "Institute / School"],
     ["tableEducationalBackgroundTHQualificationType", "Qualification Type"],
     ["tableWorkHistoryTHYear", "Date From"],
     ["tableWorkHistoryTHMonth", "Date To"],
     ["tableWorkHistoryTHDesignation", "Designation"],
     ["tableWorkHistoryTHCompany", "Company"],
     ["tableWorkHistoryTHContent", "Experience"],
     ["tableLicenseTHDateFrom", "Date From"],
     ["tableLicenseTHDateTo", "Date To"],
     ["tableLicenseTHLicenseQualification", "License Qualification"],
     ["tableLicenseTHLicenseNumber", "License Number"],
     ["tableLicenseTHLiContents", "License Operating Item"],
     ["staffHope", "If you have any particular requests regarding treatment, occupation, working hours, place of work, etc. enter them."],
    
    //PAYROLL INFO
     ["selectOptionSalaryPaymentMethod0", "Select Salary Payment Method"],
     ["selectOptionSalaryPaymentForm0", "Select Salary Payment Form"],
     ["selectOptionSalaryClosingDate0", "Select Salary Closing Date"],
     ["selectOptionPaidTarget", "Select Paid Target"],
     ["selectOptionAccountType", "Select Account Type"],
    
    //Social Info
     ["insuranceTaxinformation", "insurance / income tax / resident tax information"],
     ["selectOptionLongTermInsuranceStatus", "Select Long-term care insurance participation status"],
     ["selectOptionLongTermInsuranceStatus2", "Subscribed"],
     ["selectOptionLongTermInsuranceStatus1", "Not Subscribed"],
     ["selectOptionLongTermInsuranceStatus2", "Subscribed"],
     ["selectIncomeTaxTaxpayer", "Select Income tax taxpayer classification"],
     ["selectOptionInstep", "Instep"],
     ["selectOptionB", "B"],
     ["selectOptionHinoe", "Hinoe"],
     ["selectOptionWelfarePensionInsuranceGrade", "Select Welfare pension insurance grade"],
     ["selectOptionWelfarePensionInsuranceGradeNotSubscribed", "Not Subscribed"],
     ["selectOptionEmploymentInsuranceCoverage", "Select Employment insurance coverage"],
     ["SelectStaffResidentTaxClassification", "Select Resident tax classification"],
     ["addLicenseRow", "Add Row"],
     ["addEducationalRow", "Add Row"],
     ["addWorkRow", "Add Row"],
     ["addSkillSheetRow", "Add Row"],
     ["addDependentRow", "Add Row"],
     ["addDependentRow", "Add Row"],
     ["dependentGenderMale", "Male"],
     ["dependentGenderFemale", "Female"],
     ["dependentRelationshipWife", "Wife"],
     ["dependentRelationshipChild", "Child"],
     ["dependentRelationshipFather", "Father"],
     ["dependentRelationshipMother", "Mother"],
     ["dependentRelationshipOlderBrother", "Older Brother"],
     ["dependentRelationshipYoungerBrother", "Younger Brother"],
     ["dependentRelationshipSister", "Sister"],
     ["dependentRelationshipGrandchild","Grand child"],
     ["dependentRelationshipGrandfather","Grandfather"],
     ["dependentRelationshipGrandmotherr" ,"Grandmother"],
     ["dependentRelationshipFather-in-law" ,"Father-in-law"],
     ["dependentRelationshipMother-in-law","Mother-in-law"],
     ["dependentRelationshipGrandfather-in-law" ,"Grandfather-in-law"],
     ["dependentRelationshipGrandmother-in-law" ,"Grandmother-in-law"],
     ["dependentRelationshipOthers","Others"],
     ["dependentClassificationGeneralDependents", "General Dependents"],
     ["dependentClassificationSpecificDependents", "Specific Dependents"],
     ["dependentClassificationDependentsOfElderly", "Dependents Of Elderly"],
     ["dependentLivingTogether", "Living Together"],
     ["dependentSeparated", "Separated"],
     ["dependentSeparatedOverseas", "Separated overseas"],
     ["dependentGeneralDisabled", "General disabled"],
     ["dependentSpeciallyDisabled", "Specially disabled"],
     ["dependentHealthy", "Healthy"],
    
     ["pageSpanConflictDateList", "Conflict date individual unit) list"],
     ["accordionDivCredentialsInformation", "Credentials Information"],
     ["pageSpanLicenceQualifi", "License Qualification"],
     ["#tableWorkHistoryTHYear", "Date From"],
     ["#tableWorkHistoryTHMonth", "Date To"],
     ["#tableWorkHistoryTHDesignation", "Designation"],
     ["#tableWorkHistoryTHCompany", "Company"],
     ["#tableWorkHistoryTHContent", "Experience"],
    
        
     ["#pageOption1Prefecture", "Hokkaido"],
     ["#pageOption2Prefecture", "Aomori"],
     ["#pageOption3Prefecture", "Iwate"],
     ["#pageOption4Prefecture", "Miyagi"],
     ["#pageOption5Prefecture", "Akita"],
     ["#pageOption6Prefecture", "Yamagata"],
     ["#pageOption7Prefecture", "Fukushima"],
     ["#pageOption8Prefecture", "Ibaraki"],
     ["#pageOption9Prefecture", "Tochigi"],
     ["#pageOption10Prefecture", "Gunma"],
     ["#pageOption11Prefecture", "Saitama"],
     ["#pageOption12Prefecture", "Chiba"],
     ["#pageOption13Prefecture", "Tokyo"],
     ["#pageOption14Prefecture", "Kanagawa"],
     ["#pageOption15Prefecture", "Niigata"],
     ["#pageOption16Prefecture", "Toyama"],
     ["#pageOption17Prefecture", "Ishikawa"],
     ["#pageOption18Prefecture", "Fukui"],
     ["#pageOption19Prefecture", "Yamanashi"],
     ["#pageOption20Prefecture", "Nagano"], // changed
     ["#pageOption21Prefecture", "Gifu"], // changed
     ["#pageOption22Prefecture", "Shizuoka"],
     ["#pageOption23Prefecture", "Aichi"],
     ["#pageOption24Prefecture", "Mie"],
     ["#pageOption25Prefecture", "Shiga"],
     ["#pageOption26Prefecture", "Kyoto"],
     ["#pageOption27Prefecture", "Osaka"],
     ["#pageOption28Prefecture", "Hyogo"],
     ["#pageOption29Prefecture", "Nara"],
     ["#pageOption30Prefecture", "Wakayama"],
     ["#pageOption31Prefecture", "Tottori"],
     ["#pageOption32Prefecture", "Shimane"],
     ["#pageOption33Prefecture", "Okayama"],
     ["#pageOption34Prefecture", "Hiroshima"],
     ["#pageOption35Prefecture", "Yamaguchi"],
     ["#pageOption36Prefecture", "Tokushima"],
     ["#pageOption37Prefecture", "Kagawa"],
     ["#pageOption38Prefecture", "Ehime"],
     ["#pageOption39Prefecture", "Kochi"],
     ["#pageOption40Prefecture", "Fukuoka"],
     ["#pageOption41Prefecture", "Saga"],
     ["#pageOption42Prefecture", "Nagasaki"], //changed
     ["#pageOption43Prefecture", "Kumamoto"],
     ["#pageOption44Prefecture", "Oita"], // changed
     ["#pageOption45Prefecture", "Miyazaki"],
     ["#pageOption46Prefecture", "Kagoshima"],
     ["#pageOption47Prefecture", "Okinawa"],
     ["pageOption0Prefecture", "Select Prefecture"],
     ["#pageOption0Prefecture", "Select Prefecture"],
    
     ["pageSpanOtheAddress", "Address"],
     ["staffEmergencyAddress", "Example: 1-11-11 Shibuya, Shibuya-ku ○○○○ Building 1F"],
     ["pageSpanOtherHelpAddress", "Please be sure to enter the apartment name and building name"],
     ["pageSpanEmergencyContactPhoneNumber", "Emergency Contact Phone Number"],
     ["pageSpanHelpEmergencyContactPhoneNumber", "Please enter without hyphens"],
     ["pageSpanRelationship", "Relationship"],
     ["pageSpanDateofJoiningTheCompany", "Date of Joining The Company"],
     ["pageSpanStaffStaff", "In Charge Staff"],
     ["pageSpanExperience", "Experience"],
     ["staffExperience", "Example: Have sales experience.  Experienced as a leader in restaurants.  * You can search for input contents by free word from the search item 'Experience' in the staff list."],
     ["pageSpanStaffMemo", "Staff Memo"],
     ["StaffMemo", "Example: On February 1, a complaint occurred without following the business instructions of the dispatched company.  Be careful about the next assignment."],
     ["staffMemo", "Example: On February 1, a complaint occurred without following the business instructions of the dispatched company.  Be careful about the next assignment."],
     ["pageSpanStaffInformationUpdateHistory", "Staff Information Update History"],
     ["StaffInformationUpdate", "The update date / update staff is automatically registered, but it can also be used as an internal memo."],
     ["pageSpanValidClassification", "Valid Classification"],
     ["option0ValidClassification", "Select Valid classification"],
     ["option1ValidClassification", "Valid"],
     ["option2ValidClassification", "Invalid"],
     ["pageSpanDateofleavingthecompany", "Date of leaving the company"],
     ["buttonUpdateStaff", "Update Staff"],
     ["buttonAddStaff", "Add Staff"],
     ["staffEmergencyContactName", "Example: Taro Yamada"],
     ["staffEmergencyContactNameKatakana", "Example: Taro Yamada"],
     ["staffEmergencyPostalCode", "Example: 1234567"],
     ["staffEmergencyContactPhoneNumber", "Example: 09012345678"],
     ["staffRelationship", "Example: father"],
     ["buttonEditOtherInformation", "Update Other Information"],
     ["buttonEditLoginInformation", "Update Login Information"],
     ["buttonEditSocialInformation", "Update Social Information"],
     ["buttonEditSkillSheet", "Update Skill Sheet"],
     ["buttonEditPayrollInformation" ,"Update Payroll Information"],
     ["buttonEditStaffResume", "Update Staff Resume"],
     ["buttonEditCredentialInformation", "Update Credential Information"],
     ["buttonEditTransportationInformation", "Update Transportation Information"],
     ["buttonEditStaffInformation", "Update Staff Information"],
     ["buttonSaveStaffInformation", "Save Staff Information"],
     ["buttonSaveTransportationInformation", "Save Transportation Information"],
     ["buttonSaveResumeInformation", "Save Resume Information"],
     ["buttonSavePayrollInformation", "Save Payroll Information"],
     ["buttonSaveSocialInformation", "Save Social Information"],
     ["buttonSaveLoginInformation", "Save Login Information"],
     ["buttonSaveOtherInformation", "Save Other Information"],
     ["pageSpanGrievanceStatusFromStaff", "Grievance status from staff"],
     ["pageSpanHelpGrievanceStatusFromStaff", "*The input contents will be reflected in the dispatch source management ledger that is output in association with this staff."],
     ["pageSpanContentOfEducationAndTraining", "Date and time and content of education and training"],
     ["pageSpanHelpContentOfEducationAndTraining", "*The input contents will be reflected in the dispatch source management ledger that is output in association with this staff."],
     ["pageSpanContentOfCareerConsulting", "Date and content of career consulting"],
     ["pageSpanHelpContentOfCareerConsulting", "*The input contents will be reflected in the dispatch source management ledger that is output in association with this staff."],
     ["pageSpanDetailsOfEmploymentStabilizationMeasures", "Details of employment stabilization measures"],
     ["pageSpanHelpDetailsOfEmploymentStabilizationMeasures", "*The input contents will be reflected in the dispatch source management ledger that is output in association with this staff."],
     ["pageSpanCVFileUpload", "CV File Upload"],
     ["pageSpanHelpCVFileDownload", "Download CV File"],
     ["exampleModalCenterTitle", "Batch Deletion"],
     ["modalH4AreYouSure", "Are You Sure?"],
     ["modalH4ReallyWantToDelete", "Do You Really Want to Delete this Records ?"],
     ["modalH4CannotBeUndone", "This Process Cannot be Undone."],
     ["tableModalSearchStaffTHNo", "Record No"],
     ["tableModalSearchStaffTHName", "Name"],
     ["tableModalSearchStaffTHNameKatakana", "Name Katakana"],
     ["tableModalSearchStaffTHStaffCode", "Staff Code"],
     ["batchDeleteConfirm", "Confirm"],
     ["batchDeleteClose", "Close"], 
    
];


StaffBatchRegister = [
	 ["titleStaffBatchRegistration", "Staff Batch Registration"],
	 ["pageSpanHeadingStaffBatchRegistration", "Staff Batch Registration"],
	 ["spanDownloadLink", "Click Here To Download File Upload Template Link"],
 	 ["buttonUploadFile", "Upload File"],
 	 ["exampleModalTitleUploadSummary", "Upload Summary"],
	 ["spanUploadedFileName", "Uploaded File Name :"],
	 ["spanTotalRowCount", "Total Row Count :"],
	 ["spanValidRowCount", "Valid Row Count :"],
	 ["spanInvalidRowCount", "Invalid Row Count :"],
     ["btnDownloadSummaryFile", "Download Summary File"],
	 ["batchDeleteClose", "Close"],

];


InChargeStaffChange = [
	 ["exampleModalCenterTitleInchargeStaff", "In Charge Staff Batch Change"],
	 ["titleSelectStaffInCharge", "Select In Charge Staff"],
	 ["selectInchargeofStaffBatchChange", "Select InCharge Staff"],
	 ["tableModalSelectInChargeTHNo", "Record No"],
     ["tableModalSelectInChargeTHName", "Name"],
     ["tableModalSelectInChargeTHNameKata", "Name Katakana"],
     ["tableModalSelectInChargeTHStaffCode", "Staff Code"],
     ["inchargebatchChangeClose", "Close"],
     ["inchargebatchChangeConfirm", "Confirm"],

    

];

staffErrorArray ={  "E1030":"Invalid Date of Birth Range", 
						"E1031":"Invalid Mobile Number ", 
						"E1032":"Invalid Mail Address", 
						"E1033":"Invalid Given Name",
						"E1034":"Invalid Staff Code", 
						"E1035":"Unit Price Should be Number", 
						"E1036":"Invalid price range",
						"E1037":"Please check the Name", 
						"E1038":"Please check the Name Katakana", 
						"E1039":"Please check the Postal Code ", 
						"E1040":"Prefecture is required ", 
						"E1041":"Please check Address", 
						"E1042":"Please check Address katakana", 
						"E1043":"Please Check date of birth", 
						"E1044":"Cannot be empty", 
						"E1045":"Please check fax number", 
						"E1046":"Select at least one from dispatch classification", 
						"E1047":"Select at least one from Occupation classification", 
						"E1048":"Invalid Nearest Station", 
						"E1049":"Enter the time in minutes(0-999)", 
						"E1050":"Invalid Round Trip Bus Fare ", 
						"E1051":"Educational information is Not Valid. Date to should be greater than or equal to Date from!", 
						"E1052":"Work History information is Not Valid. Date to should be greater than or equal to Date from!", 
						"E1053":"License information is Not Valid. Date to should be greater than or equal to Date from!", 
						"E1054":"Educational Background information is Not Valid. All the columns of a row should be filled!",
						"E1055":"Work History information is Not Valid. All the columns of a row should be filled!", 
						"E1056":"License Qualification information is Not Valid. All the columns of a row should be filled!", 
						"E1057":"Invalid Daily salary unit price", 
						"E1058":"Invalid Hourly Salary unit price", 
						"E1059":"Salary Payment method is required", 
						"E1060":"Salary Payment Form is required", 
						"E1061":"Invalid Bank Code", 
						"E1062":"Invalid Branch Code", 
						"E1063":"Invalid Account Number", 
						"E1064":"Please enter your Number",
						"E1065":"Select Social Insurance Coverage ", 
						"E1066":"Select Income tax taxpayer classification", 
						"E1067":"Invalid Number of Dependents", 
						"E1068":"Dependents info is Not Valid. All the columns of a row should be filled!",  
						"E1069":"Email does not match ", 
						"E1070":"Please enter the Postal Code 。", 
						"E1071":"Check the Emergency Contact Number 。", 
						"E1072":"Date of Joining the Company is required ", 
						"E1073":"Valid Classification is required ", 
						"E1074":"Please check the Name", 
						"E1075":"Work History info is Not Valid. All the columns of a row should be filled!", 
						"E1076":"Invalid Password 。", 
						"E1077":"Password does not match", 
						"E1078":"Invalid File Type", 
						"E1079":"Dependents info is Not Valid. All the columns of a row should be filled!",
						"E1080":"Invalid Family Name", 
						"E1081":"Invalid Name Katakana", 
						"E1082":"Invalid Birthday",
						"E1083":"This Email Already Exists",
						"E1084":"Educational Background information is Not Valid. Date To and Institute / School columns should be filled",
						"E1085":"Work History information is Not Valid. Date From, Date To and Designation columns should be filled ",
						"E1086":"License Qualification information is Not Valid. Date From and License Qualification columns should be filled ",}
		