var notificationArray = {
				"N0000":"",
				"N0001":"Quotation Information Updated Successfully!<br/>Old Quotation No:<br/>",
				"N0002":",<br/> New Quotation No:<br/>",
				"N0003":"Quotation Information Save Successfully! <br/> New Quotation No:<br/>",
				"N0004":"Cancel",
				"N0005":"OK",
				"N0006":"Are you sure you want to logout?",
				"N0007":"Yes, Logout Me!",
				"E1021":"Customer Information save Successful", 
				"E1022":"Customer Information save Unsuccessful",
		 		"E1023":"Bulk delete successful", 
			    "E1024":"Bulk delete Unsuccessful",
		        "E1025":"Please Select the Customer from Customer Details",
		        "E1026":"Customer Information Update Successful", 
		        "E1027":"Customer Information Update Unsuccessful",
		        "E1028":"Customer Delete Successful",
		        "E1029":"Customer Delete Unsuccessful",
		        "E1030":"Invalid Postal Code", 
		        "E1080":"Are you sure you want to log out?", 
		        "E1081":"Are You Sure?", 
		        "E1082":"Do You Really Want to Delete this Records?",
		        "E1083":"This Process Cannot be Undone.", 
		        "E1084":"Bulk delete successful", 
		        "E1085":"Bulk delete Unsuccessful",
		        "E1086":"Please Select the Staff from Staff Details!", 
		        "E1087":"Staff Information Successfully Saved", 
		        "E1088":"staff Information save Unsuccessful", 
		        "E1089":"Transportation Information Successfully Saved", 
		        "E1090":"Transportation Information save Unsuccessful", 
		        "E1091":"Resume Information Successfully Saved", 
		        "E1092":"Resume Information save Unsuccessful", 
		        "E1093":"Payroll Information Successfully Saved", 
		        "E1094":"Payroll Information save Unsuccessful", 
		        "E1095":"Social Information Successfully Saved", 
		        "E1096":"Social Information save Unsuccessful", 
		        "E1097":"Login Information Successfully Saved", 
		        "E1098":"Login Information save Unsuccessful", 
		        "E1099":"Other Information Successfully Saved", 
		        "E1100":"Other Information save Unsuccessful", 
		        "E1101":"Sorry cannot remove this row!", 
		        "E1102":"Staff Information Update Successful", 
		        "E1103":"staff Information Update Unsuccessful", 
		        "E1104":"Transportation Information Update Successful", 
		        "E1105":"Transportation Information Update Unsuccessful",
		        "E1106":"Credentials Information Update Successful", 
		        "E1107":"Credentials Information Update Unsuccessful", 
		        "E1108":"Resume Information Update Successful", 
		        "E1109":"Resume Information Update Unsuccessful", 
		        "E1110":"Payroll Information Update Successful", 
		        "E1111":"Payroll Information Update Unsuccessful", 
		        "E1112":"Skill Sheet Information Update Successful", 
		        "E1113":"Skill Sheet Information Update Unsuccessful", 
		        "E1114":"Social Insurance/ Income Tax/ Resident Tax Information Update Successful", 
		        "E1115":"Social Insurance/ Income Tax/ Resident Tax Information Update Unsuccessful", 
		        "E1116":"Login Information Update Successful", 
		        "E1117":"Login Information Update Unsuccessful", 
		        "E1118":"Other Information Update Successful", 
		        "E1119":"Other Information Update Unsuccessful", 
		        "E1120":"User Delete Successful", 
		        "E1121":"User Delete Unsuccessful", 
		        "E1122":"Invalid Postal Code!", 
		        "N1093":"Please Check Search Values",  
		        "N1094":"Please Re-Check Values!",
		        "N1200":"Please Input a valid number!",
		        "N1201":"Please Fill the Taxation Quotation Items Table Correctly",
		        "N1202":"Please Fill the Non-Taxation Quotation Items Table Correctly",
		        "N1203":"Please fill the data correctly!",
		        "N1204":"Quotation Template Registration Successful",
		        "N1205":"Quotation Template Registration Unsuccessful",
		        "N1206":"Sorry can not remove this row!",
		        "N1207":"Quotation Template Updated Successful",
		        "N1208":"Quotation Template Update Unsuccessful",
		        "N1209":"Quotation Template Deleted Successful",
		        "N1210":"Quotation Template Unsuccessful",
		        "N1211":"Please Check Search Values",
		        "N1212":"Please Re-Check Values!",
		        "N1213":"Valid Info",
		        "N1214":"Case Information Save Unsuccessful",
		        "N1215":"Quotation Information Save Unsuccessful",
		        "N1216":"Quotation Save Unsuccessful",
		        "N1217":"Quotation item Update Unsuccessful",
		        "N1218":"Quotation item Save Unsuccessful",
		        "N1219":"Quotation Information Save Successfully! <br/> Quotation No: <br/>",
		        "N1220":"Sorry can not remove this row!",
		        "N1221":"Quotation Information Update Unsuccessful",
		        "N1222":"Case Information Update Unsuccessful",
		        "N1223":"Quotation Information Updated Successful",
		        "N1224":"Old Quotation No:",
		        "N1225":"Quotation update Unsuccessful",
		        "N1226":"Quotation Information Updated Successful",
		        "N1227":"New Quotation No:",
		        "N1228":"Quotation Delete Successful",
		        "N1229":"Quotation Delete Unsuccessful",
				"N1230":"Case Information Update Successful",
				"N1231":"Case Saved Successfully! <br/> Case Number: <br/>",
				"N1232":"Can not Delete, Already create case",
				"N1233":"Case detail Update Successful",
				"N1234":"Case detail Update Unsuccessful",
				"N1235":"Case Implementation Update Successful",
				"N1236":"Case Implementation Update Unsuccessful",
				"N1237":"Work Location Update Successful",
				"N1238":"Work Location Update Unsuccessful",
				"N1239":"Working Condition Update Successful",
				"N1240":"Working Condition Update Unsuccessful",
				"N1241":"Assignment Information Update Successful",
				"N1242":"Assignment Information Update Unsuccessful",
				"N1243":"User registered! Registration Division Update Successful",
				"N1244":"Can not Delete Quotation, Already Created case",
				"N1245":"Please Fill the Assignment Information Table Correctly",
				"N1246":"Case Delete Successful",
				"N1247":"Case Delete Unsuccessful",
				"N1248":"Case Implementation Delete Successful",
				"N1249":"Case Implementation Delete Unsuccessful",
				"N1250":"Registration Unsuccessfully! staff already Registered",
				"N1251":"User Register Unsuccessful!",
				"N1252":"Case detail Save Successful",
				"N1253":"Case detail Save Unsuccessful",
				"N1254":"Case Implementation Save Successful",
				"N1255":"Case Implementation Save Unsuccessful",
				"N1256":"Work Location Save Successful",
				"N1257":"Work Location Save Unsuccessful",
				"N1258":"Working Condition Save Successful",
				"N1259":"Working Condition Save Unsuccessful",
				"N1260":"Assignment Information Save Successful",
				"N1261":"Assignment Information Save Unsuccessful",
				"N1262":"Do you want to delete This Record ? ",
				"N1263":"Are you sure, Do you want to delete this Business Related Material ? ",
				"N1264":"Business Related Material Delete Successful ",
				"N1265":"Sorry, Operation Unsuccessful",
				"N1266":"Operation Successful",
				"N1100":"Please Fill the Allowance Table Correctly",
				"N1267":"Invoice Save Successfully! <br/> New Invoice No:<br/>",
				"N1268":"Invoice Save Unsuccessful",
				"N1269":"Invoice Update Successful",
				"N1270":"Invoice Update Unsuccessful",
				"N1271":"Employee Management Save Successful",
				"N1272":"Employee Management Save Unsuccessful",
				"N1273":"Employee Management Update Successful",
				"N1274":"Employee Management Update Unsuccessful",
				"N1275":"Please Select the Checkbox",
				"N1276":"Can not Assign staff over the required number",

		        }
		        
		var genderArray = {"":"",1:"Male",2 : "Female"}
		
		var monthArrayW = {1:"January", 2:"February", 3:"March", 4:"April", 5:"May", 6:"June", 7:"July", 8:"August", 9:"September", 10:"October", 11:"November", 12:"December"}
		
		var attributeClassificationArray = {"":"",1:"In-house",2 : "Out sourcing"}
		
		var salaryPayementFormArray = {"":"",1:"Daily / Weekly payment",2 : "Monthly Payment"}
		
		var salaryPayementMethodArray = {"":"",1:"Personal Delivery",2 : "Transfer"}
		
		var attributeArray = {"":"",1:"Elderly",2 : "Foreign Student",3 : "Foreign worker",4 : "High schooler"}
		
		var validClassificationArray = {"":"", 0:"", 1:"Valid",2 : "Invalid"}
		
		var dispatchClassificationArray = {"":"",1 : "General Dispatch",2 : "Out Sourcing",3 : "Temp -to- Perm",4 : "Talent Introduction/Recruiting/Placement",5:"Part Time"}
		
		var occupationClassificationArray = {"":"",1:"Office System",2 : "Sales / Sales System",3:"IT / Creative",4:"Medical/Welfare System",5:"Manufacturing Business",6:"Professional",7:"Others"}
		
		var prefectureArray =  {"":"", 1 : "Hokkaido", 2 : "Aomori", 3 : "Iwate", 4 : "Miyagi", 5 : "Akita", 6 : "Yamagata", 7 : "Fukushima", 8 : "Ibaraki", 9 : "Tochigi", 10 : "Gunma", 11 : "Saitama", 12 : "Chiba", 13 : "Tokyo", 14 : "Kanagawa",15 : "Niigata", 16 : "Toyama", 17 : "Ishikawa", 18 : "Fukui", 19 : "Yamanashi", 20 : "Nagano", 21 : "Gifu", 22 : "Shizuoka", 23 : "Aichi", 24 : "Mie", 25 : "Shiga", 26 : "Kyoto", 27 : "Osaka", 28 : "Hyogo", 29 : "Nara", 30 : "Wakayama", 31 : "Tottori", 32 : "Shimane", 33 : "Okayama", 34 : "Hiroshima", 35 : "Yamaguchi", 36 : "Tokushima", 37 : "Kagawa", 38 : "Ehime", 39 : "Kochi", 40 : "Fukuoka", 41 : "Saga", 42 : "Nagasaki",43 : "Kumamoto",44 : "Oita",45 : "Miyazaki",46 : "Kagoshima",47 : "Okinawa"}
				
		var assignmentClassificationArray = {"":"", 1 : "Assign By Date", 2 : "Assign By Period"}	
		
		var personInChargeArray = {"":"", 0 : "", 1 : "Person In Charge 1", 2 : "Person In Charge 2"}
		
		var salesRepresentativeArray = {"":"", 0 : "", 1 : "Sales Representative 1", 2 : "Sales Representative 2"}		
		
		var proposalDiscloserArray = {"":"", 1 : "Release", 0 : "Private"}
		
		var estimatedStatusArray = {"" : "", 1 : "Make a Quotation", 2 : "Quotation Submitted", 3 : "During Negotiations", 4 : "Orders Received", 5 : "On Hold", 6 : "Cancel"}

		var divisionByBusinessArray = {"":"", 
		"1": "Administrative civil servant",
		"2": "Corporate / group officers",
		"3": "Corporate / group management staff",
		"4": "Other administrative workers",
		"5": "researcher",
		"6": "Agriculture, forestry and fisheries engineers",
		"7": "Manufacturing technician",
		"8": "Architecture / Civil Engineering / Surveyor",
		"9": "Information processing / communication engineer",
		"10": "Other technicians",
		"11": "Doctor, dentist, veterinarian, pharmacist",
		"12": "Public health nurses, midwives, nurses",
		"13": "Medical technician",
		"14": "Other health care workers",
		"15": "Social welfare professionals",
		"16": "Legal worker",
		"17": "Professionals in management, finance, and insurance",
		"18": "Teacher",
		"19": "Religious person",
		"20": "Writer, reporter, editor",
		"21": "Artist, designer, photographer, filmmaker",
		"22": "Musician, performing arts",
		"23": "Other professional workers",
		"24": "General office worker",
		"25": "Accounting clerk",
		"26": "Production-related office workers",
		"27": "Sales / sales office worker",
		"28": "Outside office worker",
		"29": "Transportation and postal office workers",
		"30": "Office equipment operator",
		"31": "Product sales worker",
		"32": "Sales-like professional workers",
		"33": "Sales position worker",
		"34": "Family life support service professional worker",
		"35": "Long-term care service worker",
		"36": "Health care service professionals",
		"37": "Life hygiene service worker",
		"38": "Food and drink cook",
		"39": "Customer service / waiter workers",
		"40": "Manager of residential facilities, buildings, etc.",
		"41": "Other service workers",
		"42": "Self-defense officials, judicial police officers, etc.",
		"43": "Agriculturalist",
		"44": "Forestry workers",
		"45": "Fishermen",
		"46": "Production equipment control / monitoring worker",
		"47": "Machine assembly equipment control / monitoring worker",
		"48": "Product manufacturing / processing workers",
		"49": "Machine assembler",
		"50": "Machine maintenance / repair workers",
		"51": "Product inspector",
		"52": "Mechanical inspector",
		"53": "Production-related",
		"54": "Railway operator",
		"55": "Car driver",
		"56": "Ship / aircraft operator",
		"57": "Other transporters",
		"58": "Stationary",
		"59": "Construction skeleton construction worker",
		"60": "Construction workers(excluding construction workers)",
		"61": "Electrical engineer",
		"62": "Civil engineer",
		"63": "Miner",
		"64": "Transporter",
		"65": "Cleaning worker",
		"66": "Packaging worker",
		"67": "Unclassifiable occupations",
		"68": "Information processing system development",
		"69": "Mechanical design",
		"70": "Office equipment operation",
		"71": "Interpretation, translation, shorthand",
		"72": "Secretary",
		"73": "Filing",
		"74": "Survey",
		"75": "Treasury",
		"76": "Trade",
		"77": "Demonstration",
		"78": "Tour guide",
		"79": "Reception / Information",
		"80": "R & D",
		"81": "Planning and planning of project implementation system",
		"82": "Production / editing of books, etc.",
		"83": "Sales engineer sales, financial product sales",
		"84": "Advertising design",
		"85": "OA instructions"}

		var rankArray = {"":"", 1 : "A", 2 : "B", 3 : "C", 4 : "D", 5 : "E"}
		
		var managerAray = {"":"", 1 : "Manager A", 2 : "Manager B", 3 : "Manager C", 4 : "Manager D", 5 : "Manager E"}
		
		var billingStatusArray ={"":"", 1 : "Not Payment", 2 : "Deposited", 3 : "On Hold", 4 : "Cancel"}
		
		var authorityAray = {"":"", 1 : "Administrator", 2 : "In charge of the Matter", 3 : "Sales", 4 : "Accounting", 5 : "Staff Charge"}
		
		var unitPriceArray = {"":"", 1 :"Daily Salary", 2 : "Hourly Wage", 3:"Full Monthly Salary", 4:"Day to month"}
		
		var ageTextArray = {"":"", 1 :" years old / "}
