function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(AgencySearch);
    convertContentToLanguage(AgencyDetails);
    convertContentToLanguage(AgencyBatchUpload);
}

TopMenu = [
 
      ["menuButtonProfile", "プロフィール"],
      ["menuButtonManual", "マニュアル"],
      ["menuButtonLogout", "ログアウト"],
];

LeftMenu = [
		["pageTitle", "スタッフ一覧"],
		["menuSpanHome", "Home"],
		["menuSubSpanHome", "Home"],
		["menuSpanCustomer", "顧客管理"],
		["menuSpanQuoMan", "見積書管理"],
		["menuSpanInvoiceMan", "請求書管理"],
		["menuSpanMatterMan", "案件管理"],
		["menuSpanAssignment", "アサイン管理"],
		["menuSpanStaff", "スタッフ管理"],
		["menuSpanShifftSchedule", "スタッフシフト予定管理" ],
		["menuSpanAttendance", "勤怠管理"],
		["menuSpanPayrollMan", "給与管理"],
		["menuSpanAnnualPayroll", "Annual Payroll"],
		["menuSpanPaidGrand", "Paid Grant"],
		["menuSpanEmployeeManagement", "社員管理"],
		["menuSpanAgencyManagement", "代理店管理"],
		["menuSpanStaffPageLogin", "スタッフページログイン"],
		["menuSpanMasterAdmin", "マスタ管理"],
		["menuSubSpanCompanyInformationManagement", "会社情報管理"],
		["menuSubSpanConsumptionTaxManagement", "消費税管理"],
		["menuSubSpanDailyIncomeTax", "源泉徴収日額管理"],
		["menuSubSpanMonthlyTaxManagement", "源泉徴収月額管理"],
		["menuSubSpanAllowanceManagement", "残業・休日手当管理"],
		["menuSubSpanPaidTableManagement", "有給テーブル管理"],
		["menuSubSpanContractTerms", "契約書条件"],
		["menuSubSpanEmailTemplateManagement", "メールテンプレート管理"],
		["menuSubSpanQuoteTemplateManagement", "見積りテンプレート管理"],
		["menuSpanAboutCompliance", "コンプライアンスについて"],
		["menuTermsofServices", "利用規約"],
		["menuPrivacyPolicy", "プライバシーポリシー"],
		["menuBasedCommercial", "特定商取引法に基づく表示"]
];

AgencySearch = [
     ["pageTitleAgencyList", "代理店リスト"],
     ["pageSpanHeadingAgency", "代理店リスト"],
     ["pageSpanSubHeadingAgency", "代理店情報を一覧で確認することができます"],
     ["buttonSpanAgencyReg", "代理店登録"],
     ["buttonSpanImportAgencyData", "既存代理店データ取込"],
     ["buttonSpanAgencyListCSV", "代理店一覧CSVを出力"],
     ["pageSpanSearch", "検索"],
     ["pageLabelAgencyName", "代理店名"],
     ["pageLabelAgencyNameKatakana", "代理店名カナ"],
     ["pageLabelBelonging", "所属"],
     ["pageLabelAgencyCode", "代理店コード"],
     ["pageLabelMobilePhone", "連絡先"],
     ["pageLabelMailAddress", "メールアドレス"],
     ["pageLabelAddress", "住所"],
     ["pageLabelPostalcode", "郵便番号"],
     ["pageLabelPrefectures", "都道府県"],
     ["pageLabelDispatchClassification", "派遣区分"],
     ["pageLabelAgencyRepresentativeName", "代理店担当者連絡先"],
     ["pageLabelAgencyRepresentativeNameKatakana", "代理店担当者名カナ"],
     ["pageOrganizationName", "組織名"],
     ["pageLabelManager", "担当者"],
     ["pageLabelCustomerRank", "ランク"],
     ["clearAllBtn", "すべて消去"],
     ["searchBtn", "検索"],
     ["pageSpanSearchAgencyDetails", "検索結果"],
     ["tableSearchStaffTHNo", "記録番号"],
     ["tableSearchStaffTHChoice", "選択"],
     ["tableSearchTHAgencyName", "代理店名"],
     ["tableSearchCustomerTHTel", "TEL/メールアドレス"],
     ["tableSearchCustomerTHDispatchClassification", "派遣区分"],
     ["tableSearchCustomerTHAddress", "住所"],
     ["tableSearchTHAgencyCode", "代理店コード"],
     ["tableSearchTHAgencyRepresentative", "代理店代表者氏名"],
     ["tableSearchCustomerTHRank", "ランク"],
     ["agencyName", "機関名を入力"],
     ["agencyNameKatakana", "代理店名カタカナを入力"],
     ["agencyBelonging", "所属を入力する"],
     ["agencyCode", "代理店コードを入力"],
     ["mobilePhone", "携帯電話番号の入力"],
     ["mailAddress", "メールアドレスを入力してください"],
     ["companyAddress", "代理店住所を入力"],
     ["postalCode", "郵便番号の入力"],
     ["selectOptionSelectPrefectures", "県を選択"],
     ["pageOption1Prefecture", "北海道"],
      ["pageOption2Prefecture", "青森県"],
      ["pageOption3Prefecture", "岩手県"],
      ["pageOption4Prefecture", "宮城県"],
      ["pageOption5Prefecture", "秋田県"],
      ["pageOption6Prefecture", "山形県"],
      ["pageOption7Prefecture", "福島県"],
      ["pageOption8Prefecture", "茨城県"],
      ["pageOption9Prefecture", "栃木県"],
      ["pageOption10Prefecture", "群馬県"],
      ["pageOption11Prefecture", "埼玉県"],
      ["pageOption12Prefecture", "千葉県"],
      ["pageOption13Prefecture", "東京都"],
      ["pageOption14Prefecture", "神奈川県"],
      ["pageOption15Prefecture", "新潟県"],
      ["pageOption16Prefecture", "富山県"],
      ["pageOption17Prefecture", "石川県"],
      ["pageOption18Prefecture", "福井県"],
      ["pageOption19Prefecture", "山梨県"],
      ["pageOption20Prefecture", "長野県"], // changed
      ["pageOption21Prefecture", "岐阜県"], // changed
      ["pageOption22Prefecture", "静岡県"],
      ["pageOption23Prefecture", "愛知県"],
      ["pageOption24Prefecture", "三重県"],
      ["pageOption25Prefecture", "滋賀県"],
      ["pageOption26Prefecture", "京都府"],
      ["pageOption27Prefecture", "大阪府"],
      ["pageOption28Prefecture", "兵庫県"],
      ["pageOption29Prefecture", "奈良県"],
      ["pageOption30Prefecture", "和歌山県"],
      ["pageOption31Prefecture", "鳥取県"],
      ["pageOption32Prefecture", "島根県"],
      ["pageOption33Prefecture", "岡山県"],
      ["pageOption34Prefecture", "広島県"],
      ["pageOption35Prefecture", "山口県"],
      ["pageOption36Prefecture", "徳島県"],
      ["pageOption37Prefecture", "香川県"],
      ["pageOption38Prefecture", "愛媛県"],
      ["pageOption39Prefecture", "高知県"],
      ["pageOption40Prefecture", "福岡県"],
      ["pageOption41Prefecture", "佐賀県"],
      ["pageOption42Prefecture", "長崎県"],  //changed
      ["pageOption43Prefecture", "熊本県"],
      ["pageOption44Prefecture", "大分県"], // changed
      ["pageOption45Prefecture", "宮崎県"],
      ["pageOption46Prefecture", "鹿児島県"],
      ["pageOption47Prefecture", "沖縄県"],
      ["selectOptionSelectDispatchClassification", "派遣区分の選択"],
     ["agencyRepresentativeName", "代理店代表者名を入力してください。"],
     ["AgencyRepresentativeNameKatakana", "代理店代表者名カタカナを入力"],
     ["companyOrganizationName", "組織名を入力"],
     ["selectOptionSelectCompanyManager", "セレクトマネージャー"],
     ["selectOptionSelectRank", "セレクトランク"],
     ["buttonSpanCheckAll", "すべてをチェック"],
     ["buttonSpanUncheckAll", "すべてのチェックをはずす"],
     ["buttonSpanBatchDeletion", "一括削除"],
     ["exampleModalCenterTitle", "一括削除"],
     ["modalAreYouSure", "本当ですか？"],
     ["modalDoYouWantDelete", "本当にこのレコードを削除しますか？"],
     ["modalProcesCannotBeUndone", "このプロセスを元に戻すことはできません。"],
     ["tableSearchAgencyNo", "記録番号"],
     ["tableSearchAgencyCode", "代理店コード"],
     ["tableSearchAgencyName", "代理店名"],
     ["tableSearchAgencyRepresentativeName", "代理店代表者名"],
     ["batchDeleteConfirm", "確認"],
     ["batchDeleteClose", "選ぶ"], 
     ["pageSpanbusinessContract", "業務請負"],
     ["pageSpanintroductionDispatching", "紹介予定派遣"],
     ["pageSpanrecruitment", "人材紹介"],
          
 ];

AgencyDetails = [
    ["pageTitleAgencyDetails", "代理店詳細"],
    ["pageSpanHeadingAgencyDetails", "代理店詳細"],
    ["pageSpanSubHeadingAgencyDetails", "代理店の詳細情報を確認・更新することができます。"],
    ["buttonSpanReturn", "戻る"],
    ["accordionDivAgencyInformation", "代理店情報"],
    ["pageSpanAgencyName", "代理店名"],
    ["pageSpanAgencyNameKatakana", "代理店名カナ"],
    ["pageSpanRepresentativePosition", "代表者役職"],
    ["pageSpanRepresentativeName", "代表者氏名"],
    ["pageLabelContactNumber", "連絡先"],
    ["pageSpanFaxNumber", "FAX番号"],
    ["pageLabelMailAddress", "メールアドレス"],
    ["pageSpanAgencyCode", "代理店コード"],
    ["pageSpanDisClassification", "派遣区分"],
    ["pageSpanGeneralDispatch", "一般派遣"],
    ["pageSpanBusinessContract", "業務請負"],
    ["pageSpanIntroductionDispatching", "紹介予定派遣"],
    ["pageSpanRecruitment", "人材紹介"],
	["pageSpanPartTime", "アルバイト"],
    ["pageLabelPostalcode", "郵便番号"],
    ["btnAddressSearch", "住所検索"],
    ["pageSpanHelpZipCode", "ハイフンなしで入力してください"],
    ["pageSpanPrefecture", "都道府県"],
    ["pageSpanAddress", "住所"],
    ["pageSpanOrganizationName", "組織名"],
    ["pageSpanBillingDeadline", "請求締め日"],
    ["pageSpanAgencyContact", "代理店担当者連絡先"],
    ["pageSpanAgencyRepresentativeNameKatakana", "代理店担当者名"],
    ["pageSpanAgencyContactKana", "代理店担当者名カナ"],
    ["pageSpanRank", "ランク"],
    ["pageSpanManager", "担当者"],
    ["SelectCompanyManager", "担当者を選択"],
    ["pageSpanWebsiteURL", "URL(自社HPなど)"],
	["pageSpanBelongned", "所属"],
	["pageSpanConflictDate", "抵触日(事業所単位)"],
    ["pageSpanRemarks", "備考"],
    ["buttonUpdateAgencyInformation", "代理店情報の更新"],
    ["pageSpanHeadingAgencyRegistration", "代理店登録"],
    ["pageSpanSubHeadingAgencyRegistration", "代理店として登録することができます"],
    ["buttonRegisterAgencyInformation", "登録"],
    ["pageTitleAgencyRegistration", "代理店登録"]
];

AgencyBatchUpload = [
    ["pageSpanHeadingAgencyBatchRegistration", "代理店フ一括登録"],
    ["spanDownloadLink", "ファイルアップロード用のテンプレートのリンクをダウンロードするには、ここをクリックしてください"],
    ["buttonUploadFile", "ファイルをアップロードする"],
    ["buttonSpanReturn", "戻る"]
];

agencyErrorArray = {"E2000":"空白にすることはできません",
					"E2001":"代表者名が無効",
					"E2002":"無効な連絡先電話番号",
					"E2003":"無効なFAX番号",
					"E2004":"無効な郵便番号",
					"E2005":"無効な代理店代表者名",
					"E2006":"無効な代理店代表者名 カタカナ",
					"E2007":"無効な代理店連絡先電話番号",
					"E2008":"無効なURL",
					"E2009":"無効な電子メール",
					"E2010":"無効な代理店コード"}


