
function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(CustomerSearch);
    convertContentToLanguage(CustomerDetails);
    convertTitleToLanguageByName(TitleList);
}

TopMenu = [
    ["menuButtonProfile", "プロフィール"],
    ["menuButtonManual",  "マニュアル"],
    ["menuButtonLogout", "ログアウト"]
];

LeftMenu = [
		["pageTitle", "スタッフ一覧"],
		["menuSpanHome", "Home"],
		["menuSubSpanHome", "Home"],
		["menuSpanCustomer", "顧客管理"],
		["menuSpanQuoMan", "見積書管理"],
		["menuSpanInvoiceMan", "請求書管理"],
		["menuSpanMatterMan", "案件管理"],
		["menuSpanAssignment", "アサイン管理"],
		["menuSpanStaff", "スタッフ管理"],
		["menuSpanShifftSchedule", "スタッフシフト予定管理" ],
		["menuSpanAttendance", "勤怠管理"],
		["menuSpanPayrollMan", "給与管理"],
		["menuSpanAnnualPayroll", "Annual Payroll"],
		["menuSpanPaidGrand", "Paid Grant"],
		["menuSpanEmployeeManagement", "社員管理"],
		["menuSpanAgencyManagement", "代理店管理"],
		["menuSpanStaffPageLogin", "スタッフページログイン"],
		["menuSpanMasterAdmin", "マスタ管理"],
		["menuSubSpanCompanyInformationManagement", "会社情報管理"],
		["menuSubSpanConsumptionTaxManagement", "消費税管理"],
		["menuSubSpanDailyIncomeTax", "源泉徴収日額管理"],
		["menuSubSpanMonthlyTaxManagement", "源泉徴収月額管理"],
		["menuSubSpanAllowanceManagement", "残業・休日手当管理"],
		["menuSubSpanPaidTableManagement", "有給テーブル管理"],
		["menuSubSpanContractTerms", "契約書条件"],
		["menuSubSpanEmailTemplateManagement", "メールテンプレート管理"],
		["menuSubSpanQuoteTemplateManagement", "見積りテンプレート管理"],
		["menuSpanAboutCompliance", "コンプライアンスについて"],
		["menuTermsofServices", "利用規約"],
		["menuPrivacyPolicy", "プライバシーポリシー"],
		["menuBasedCommercial", "特定商取引法に基づく表示"]
];

TitleList = [
	["viewDetails", "詳細を見る"],
	["MakeQuotation", "見積もり"],
	["MakeInvoice", "請求書を作成する"],
];

CustomerSearch = [
   	["pageTitleCustomerList","顧客一覧"],
    ["pageSpanHeadingCustomer", "顧客リスト"],
    ["pageSpanSearch", "検索"],
    ["buttonSpanCustomerReg", "顧客登録"],
    ["buttonSpanImportCustomerData","既存顧客データ取込"],
    ["buttonSpanCustomerListCSV", "顧客一覧CSVを出力"],
    ["pageCardDivTotalCustomers", "総顧客数"],
    ["pageCardDivTotalActiveCustomers", "アクティブな顧客の総数"],
    ["pageCardDivTotalAvailableCustomers", "利用可能な顧客の合計"],
    ["pageCardDivTotalPendingCustomers","保留中の顧客の合計"],
    ["pageLabelCompanyName", "会社名"],
    ["companyNames", "会社名を入力してください"],
    ["pageLabelCompanyNameKatakana", "会社名カナ"],
    ["companyNameKatakana", "会社名カタカナを入力してください"],
    ["pageLabelBelonging", "所属"],
    ["companyBelonging","所属を入力してください"],
    ["pageLabelCustomerCode","顧客コード"],
    ["customerCode", "顧客コードを入力してください"],
    ["pageLabelMobilePhone", "連絡先"],
    ["mobilePhone","電話番号を入力してください"],
    ["pageLabelMailAddress", "メールアドレス"],
    ["mailAddress", "メールアドレスを入力してください"],
    ["pageLabelDispatchClassification", "派遣区分"],
    ["selectOptionSelectDispatchClassification", "分類を選択"],
    ["pageSpanGeneralDispatch", "一般派遣"],
    ["pageSpanBusinessContract", "業務請負"],
    ["pageSpanIntroductionDispatching", "紹介予定派遣"],
    ["pageSpanRecruitment", "人材紹介"],
    ["pageSpanPartTime", "アルバイト"],
    ["pageLabelPostalcode", "郵便番号"],
    ["postalCode", "郵便番号を入力してください"],
    ["pageLabelPrefectures", "都道府県"],
    ["selectOptionSelectPrefectures", "県を選択"],
     ["pageOption1Prefecture", "北海道"],
     ["pageOption2Prefecture", "青森県"],
     ["pageOption3Prefecture", "岩手県"],
     ["pageOption4Prefecture", "宮城県"],
     ["pageOption5Prefecture", "秋田県"],
     ["pageOption6Prefecture", "山形県"],
     ["pageOption7Prefecture", "福島県"],
     ["pageOption8Prefecture", "茨城県"],
     ["pageOption9Prefecture", "栃木県"],
     ["pageOption10Prefecture", "群馬県"],
     ["pageOption11Prefecture", "埼玉県"],
     ["pageOption12Prefecture", "千葉県"],
     ["pageOption13Prefecture", "東京都"],
     ["pageOption14Prefecture", "神奈川県"],
     ["pageOption15Prefecture", "新潟県"],
     ["pageOption16Prefecture", "富山県"],
     ["pageOption17Prefecture", "石川県"],
     ["pageOption18Prefecture", "福井県"],
     ["pageOption19Prefecture", "山梨県"],
     ["pageOption20Prefecture", "長野県"], // changed
     ["pageOption21Prefecture", "岐阜県"], // changed
     ["pageOption22Prefecture", "静岡県"],
     ["pageOption23Prefecture", "愛知県"],
     ["pageOption24Prefecture", "三重県"],
     ["pageOption25Prefecture", "滋賀県"],
     ["pageOption26Prefecture", "京都府"],
     ["pageOption27Prefecture", "大阪府"],
     ["pageOption28Prefecture", "兵庫県"],
     ["pageOption29Prefecture", "奈良県"],
     ["pageOption30Prefecture", "和歌山県"],
     ["pageOption31Prefecture", "鳥取県"],
     ["pageOption32Prefecture", "島根県"],
     ["pageOption33Prefecture", "岡山県"],
     ["pageOption34Prefecture", "広島県"],
     ["pageOption35Prefecture", "山口県"],
     ["pageOption36Prefecture", "徳島県"],
     ["pageOption37Prefecture", "香川県"],
     ["pageOption38Prefecture", "愛媛県"],
     ["pageOption39Prefecture", "高知県"],
     ["pageOption40Prefecture", "福岡県"],
     ["pageOption41Prefecture", "佐賀県"],
     ["pageOption42Prefecture", "長崎県"],//changed
     ["pageOption43Prefecture", "熊本県"],
     ["pageOption44Prefecture", "大分県"], // changed
     ["pageOption45Prefecture", "宮崎県"],
     ["pageOption46Prefecture", "鹿児島県"],
     ["pageOption47Prefecture", "沖縄県"],
    ["pageLabelAddress", "住所"],
    ["companyAddress",  "会社の住所を入力してください"],
    ["pageOrganizationName", "組織名"],
    ["companyOrganizationName", "組織名を入力してください"],
    ["pageLabelRepresentativeName", "顧客担当者名"],
    ["companyRepresentativeName", "顧客代表名を入力してください"],
    ["pageLabelRepresentativeNameKatakana", "顧客担当者名カナ"],
    ["companyRepresentativeNameKatakana", "顧客代表名カタカナを入力してください"],
    ["pageLabelManager",  "担当者"],
    ["selectOptionSelectCompanyManager", "担当者を選択"],
    ["selectOptionSelectCompanyManagerA", "会社長A"],
    ["selectOptionSelectCompanyManagerB", "会社長B"],
    ["selectOptionSelectCompanyManagerC", "会社長C"],
    ["selectOptionSelectCompanyManagerD","会社長D"],
    ["selectOptionSelectCompanyManagerE", "会社長E"],
    ["pageLabelCustomerRank","ランク"],
    ["selectOptionSelectRank", "ランクを選択"],
    ["clearAllBtn",  "すべて消去"],
    ["searchBtn",  "検索"],
    ["pageSpanSearchCustomerDetails", "検索結果"],
    ["buttonSpanCheckAll", "全てチェックする"],
    ["buttonSpanUncheckAll",  "全てのチェックを外す"],
    ["buttonSpanBatchDeletion",  "顧客一括削除"],
    ["tableSearchStaffTHNo", "No."],
    ["tableSearchStaffTHChoice", "選択"],
    ["tableSearchCustomerTHCustomerCode", "顧客コード"],
    ["tableSearchCustomerTHTel", "TEL/メールアドレス"],
    ["tableSearchCustomerTHDispatchClassification", "派遣区分"],
    ["tableSearchCustomerTHAddress", "住所"],
    ["tableSearchCustomerTHCompanyName", "お客様の会社名"],
    ["tableSearchCustomerTHCustomerRepresentative", "顧客担当者名"],
    ["tableSearchCustomerTHManager", "担当者"],
    ["tableSearchCustomerTHRank", "ランク"],
    ["exampleModalCenterTitle", "顧客一括削除"],
    ["modalAreYouSure", "本当に実行しますか？"],
    ["modalDoYouWantDelete", "本当にこのレコードを削除しますか？"],
    ["modalProcesCannotBeUndone",  "削除すると元に戻すことはできません。"],
    ["tableSearchStaffTHNo", "記録番号"],
    ["tableSearchCustomerOrganizationName", "組織名"],
    ["tableSearchStaffCustomerRepresentativeName", "顧客担当者名"],
    ["tableSearchCustomerCode", "顧客コード"],
    ["batchDeleteConfirm", "確認"],
    ["batchDeleteClose", "選ぶ"] 
];

CustomerDetails = [
   ["CustomerRegistrationHeader", "顧客登録"],
    ["pageTitleCustomerDetail", "顧客詳細"],
    ["pageSpanHeadingCustomerRegistration", "顧客登録"],
    ["pageSpanHeadingCustomerDetails", "顧客詳細"],
    ["pageSpanSubHeadingCustomerRegistration", "顧客の登録ができます。"],
    ["pageSpanSubHeadingCustomerDetails", "顧客情報を変更して、この顧客の見積もりを作成できます。"],
    ["buttonSpanCreateFromThisCustomer", "この顧客から作成する"],
    ["buttonValueSpanCustomerMakeQuote", "見積書作成"],
    ["buttonValueSpanCustomerProposalCreation", "案件作成"],
    ["buttonValueSpanCustomerInvoiceCreation","請求書作成"],
    ["buttonValueSpanCustomerCopyAndCreateAnotherCustomer", "コピーして別顧客を作成"],
    ["buttonSpanStaffDetailsDelete", "削除"],
    ["buttonValueSpanStaffDetailsDelete", "顧客を削除"],
    ["buttonSpanReturn", "戻る"],
    ["accordionDivCustomerInformation","顧客情報"],
    ["pageSpanCompanyName", "会社名"],
    ["pageSpanCompanyNameKatakana", "会社名カナ"],
    ["pageSpanRepresentativePosition", "代表者役職"],
    ["pageSpanRepresentativeName", "代表者氏名"],
    ["pageLabelMobilePhone", "連絡先"],
    ["pageSpanHelpMobile", "ハイフンなしで入力してください"],
    ["pageSpanFaxNumber",  "FAX番号"],
    ["pageSpanHelpFax", "ハイフンなしで入力してください"],
    ["pageLabelMailAddress", "メールアドレス"],
    ["pageSpanCustomerCode", "顧客コード"],
    ["pageSpanDisClassification",  "派遣区分"],
    ["pageSpanGeneralDispatch", "一般派遣"],
    ["pageSpanBusinessContract", "業務請負"],
    ["pageSpanIntroductionDispatching", "紹介予定派遣"],
    ["pageSpanRecruitment",  "人材紹介"],
    ["pageLabelPostalcode", "郵便番号"],
    ["btnAddressSearch", "住所検索"],
    ["pageSpanHelpZipCode",  "ハイフンなしで入力してください"],
    ["pageSpanPrefecture", "都道府県"],
    ["pageSpanAddress","住所"],
    ["pageSpanHelpAddress","アパート名と建物名を入力してください"],
    ["pageSpanOrganizationName", "組織名"],
    ["pageSpanBillingDeadline", "請求締め日"],
    ["pageSpanCustomerRepresentativeName","顧客担当者名"],
    ["pageSpanCustomerRepresentativeNameKatakana",  "顧客担当者名カナ"],
    ["pageSpanCustomerContact", "顧客担当者連絡先"],
    ["pageSpanManager", "担当者"],
    ["SelectCompanyManager",  "担当者を選択"],
    ["SelectCompanyManager1",  "マネージャーA"],
    ["SelectCompanyManager2",  "マネージャーB"],
    ["SelectCompanyManager3",  "マネージャーC"],
    ["SelectCompanyManager4",  "マネージャーD"],
    ["SelectCompanyManager5", "マネージャーE"],
    ["pageSpanBelongned",  "所属"],
    ["pageSpanWebsiteURL", "URL(自社HPなど)"],
    ["pageSpanConflictDate",  "抵触日(事業所単位)"],
    ["pageSpanRank", "ランク"],
    ["selectRank", "ランクを選択"],
    ["pageSpanRemarks", "備考"],
    ["buttonEditCompanyInformation", "会社情報の更新"],
    ["buttonSaveCompanyInformation", "会社情報を保存する"],
    ["pageSpanHelpContact", "ハイフンなしで入力してください"],
    ["pageHeadingCustomerBatchRegistration", "既存顧客データ取込"],
	["pageSpanHeadingCustomerBatchRegistration", "既存顧客データ取込"],
	["spanDownloadLink", "フォーマットダウンロードはこちら"],
	["buttonUploadFile", "ファイルのアップロード"],
	["exampleModalTitleUploadSummary", "アップロードの概要"],
    ["spanUploadedFileName", "アップロードされたファイル名 :"],
    ["spanTotalRowCount", "合計行数 :  "],
    ["spanValidRowCount", "有効な行数 : "],
    ["spanInvalidRowCount", "無効な行数 : "],
    ["btnDownloadSummaryFilelink", "サマリーファイルのダウンロード"],
    ["batchDeleteClose", "閉じる"],
];


customerErrorArray = {"E1001":"無効なカスタマーコード", "E1002":"無効な携帯電話番号", "E1003":"無効なメール", "E1004":"無効な郵便番号", "E1005":" 必須入力項目です。", "E1006":"無効な会社代表者名", "E1007":" 無効なファックス番号", "E1008":"顧客担当者名を入力してください", "E1009":"無効な顧客担当者名", "E1010":"顧客担当者名 カタカナを入力してください。", "E1011":"無効な顧客担当者名のカタカナ表記", "E1012":"無効なお客様の連絡先", "E1013":" 無効なURL", "E1014":" 無効な会社名", "E1015":"このメールはすでに存在しています"}
 
 

