function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(Employee)
}

TopMenu = [
    ["menuButtonProfile", "プロフィール"],
    ["menuButtonManual",  "マニュアル"],
    ["menuButtonLogout", "ログアウト"]
];

LeftMenu = [
		["pageTitle", "スタッフ一覧"],
		["menuSpanHome", "Home"],
		["menuSubSpanHome", "Home"],
		["menuSpanCustomer", "顧客管理"],
		["menuSpanQuoMan", "見積書管理"],
		["menuSpanInvoiceMan", "請求書管理"],
		["menuSpanMatterMan", "案件管理"],
		["menuSpanAssignment", "アサイン管理"],
		["menuSpanStaff", "スタッフ管理"],
		["menuSpanShifftSchedule", "スタッフシフト予定管理" ],
		["menuSpanAttendance", "勤怠管理"],
		["menuSpanPayrollMan", "給与管理"],
		["menuSpanAnnualPayroll", "Annual Payroll"],
		["menuSpanPaidGrand", "Paid Grant"],
		["menuSpanEmployeeManagement", "社員管理"],
		["menuSpanAgencyManagement", "代理店管理"],
		["menuSpanStaffPageLogin", "スタッフページログイン"],
		["menuSpanMasterAdmin", "マスタ管理"],
		["menuSubSpanCompanyInformationManagement", "会社情報管理"],
		["menuSubSpanConsumptionTaxManagement", "消費税管理"],
		["menuSubSpanDailyIncomeTax", "源泉徴収日額管理"],
		["menuSubSpanMonthlyTaxManagement", "源泉徴収月額管理"],
		["menuSubSpanAllowanceManagement", "残業・休日手当管理"],
		["menuSubSpanPaidTableManagement", "有給テーブル管理"],
		["menuSubSpanContractTerms", "契約書条件"],
		["menuSubSpanEmailTemplateManagement", "メールテンプレート管理"],
		["menuSubSpanQuoteTemplateManagement", "見積りテンプレート管理"],
		["menuSpanAboutCompliance", "コンプライアンスについて"],
		["menuTermsofServices", "利用規約"],
		["menuPrivacyPolicy", "プライバシーポリシー"],
		["menuBasedCommercial", "特定商取引法に基づく表示"]
];


Employee = [
    ["pageTitleEmployeeManagement", "従業員管理"],
    ["pageTitleEmployeeDetails", "従業員の詳細"],
    ["pageTitleEmployeeRegistration", "従業員登録"],
	["pageSpanHeadingEmployeeList", "社員一覧"],
	["buttonSpanEmployeeRegistration", "社員登録"],
	["pageSpanSearch", "検索"],
	["pageLabelName", "名前"],
	["name", "名前の入力"],
	["pageLabelDateofJoiningFrom", "入社年月日（開始）"],
	["pageLabelMailAddress", "メールアドレス"],
	["mailAddress", "メールアドレスの入力"],
	["pageLabelDateofJoiningTo", "入社年月日（終了）"],
	["pageLabelAuthority", "権限"],
	["selectOptionSelectAuthority", "権限ランクを選択"],
	["pageOptionAdministrator", "管理者"],
	["pageOptionInchargeoftheMatter", "案件担当"],
	["pageOptionSales", "営業"],
	["pageOptionAccounting", "経理"],
	["pageOptionStaffCharge", "スタッフ担当"],
	//["pageOptionProfessional", "Professional"],
	//["pageOptionOthers", "Others"],
	["optionClassification", "区分の選択"],
	["pageLabelValidClassification", "有効区分"],
	//["option0ValidClassification", "Select Valid Classification"],
	["option1ValidClassification", "有効"],
	["option2ValidClassification", "無効"],
	["clearAllBtn", "全て消去"],
	["searchBtn", "検索"],
	["pageCardDivTotalStaff", "合計スタッフ数"],
	["pageCardDivTotalActiveStaff", "アクティブな社員数"],
	["pageCardDivTotalAvailableStaff", "スタッフ数"],
	["pageCardDivTotalPendingStaff", "合計保留者数"],
	["pageSpanSearchStaffDetails", "社員情報の検索"],
	["tableSearchEmployeeTHNo", "No."],
	["tableSearchEmployeeTHName", "名前"],
	["tableSearchEmployeeTHEmail", "メールアドレス"],
	["tableSearchEmployeeTHAuthority", "権限"],
	["tableSearchEmployeeTHDateofJoining", "入社年月日"],
	["tableSearchEmployeeTHValidClassification", "有効区分"],
	["search_table_info", "記録はありません"],
	["pageSpanHeadingRegistrationEmployeeRegister", "社員登録"],
	["pageSpanSubHeadingRegistrationStaffDetails", "社員の登録ができます。"],
	["buttonSpanRegistrationReturn", "戻る"],
	["accordionDivRegistrationEmployeeInformation", "社員情報"],
	["pageSpanRegistrationEmployeeName", "名前"],
	["pageSpanregistrationEmailaddress", "メールアドレス"],
	["pageSpanregistrationAuthority", "権限"],
	["optionregistrationAuthoritySelectAuthority", "権限を選択"],
	["optionregistrationAuthorityAdministrator", "管理者"],
	["optionregistrationAuthorityInchargeofthematter", "案件担当"],
	["optionregistrationAuthoritySales", "営業"],
	["optionregistrationAuthorityAccounting", "経理"],
	["optionregistrationAuthorityStaffCharge", "スタッフ担当"],
	["pageSpanregistrationTransferfinancialinstitutionname", "振込金融機関名"],
	["pageSpanregistrationBankCode", "銀行コード"],
	["pageSpanregistrationTransferbranchname", "振込支店名"],
	["pageSpanregistrationBranchCode", "支店コード"],
	["pageSpanregistrationAccounttype", "口座種別"],
	["optionAccountTyperegistrationSelect", "口座種別を選択"],
	["optionAccountTyperegistrationUsually", "普通"],
	["optionAccountTyperegistrationCurrent", "当座"],
	["optionAccountTyperegistrationSavings", "貯蓄"],
	["optionAccountTyperegistrationOthers", "その他"],
	["pageSpanregistrationAccountNumber", "口座番号"],
	["pageSpanregistrationAccountName", "口座名"],
	["pageSpanregistrationDateofjoiningthecompany", "入社年月日"],
	["pageSpanregistrationSuperiorName", "上長名"],
	["pageSpanregistrationPassword", "パスワード"],
	["pageSpanregistrationForPasswordConfirmation", "パスワード(確認)"],
	["pageSpanregistrationRemarks", "備考"],
	["pageSpanregistrationValidclassification", "有効区分"],
	["optionregistrationvalidclassification", "有効"],
	["optionregistrationInValidclassification", "無効"],
	["pageSpanregistrationTerminationDate", "退職年月日"],
	["buttonSaveregistrationEmployeeInformation", "社員を登録"],
	["pageSpanHeadingEmployeeDetails", "社員詳細"],
	["pageSpanSubHeadingEmployeeDetails", "社員情報の修正ができます。"],
	["buttonSpanReturn", "戻る"],
	["accordionDivEmployeeInformation", "社員情報"],
	["pageSpanName", "名前"],
	["pageSpanEmailaddress", "メールアドレス"],
	["pageSpanAuthority", "権限"],
	["pageSpanTransferfinancialinstitutionname", "振込金融機関名"],
	["pageSpanBankCode", "銀行コード"],
	["pageSpanTransferbranchname", "振込支店名"],
	["pageSpanBranchCode", "支店コード"],
	["pageSpanAccounttype", "口座種別"],
	["optionAccountTypeSelectAccountType", "口座種別を選択"],
	["optionAccountTypeUsually", "普通"],
	["optionAccountTypeCurrent", "当座"],
	["optionAccountTypeSavings", "貯蓄"],
	["optionAccountTypeOthers", "その他"],
	["pageSpanAccountNumber", "口座番号"],
	["pageSpanAccountName", "口座名"],
	["pageSpanDateofjoiningthecompany", "入社年月日"],
	["pageSpanSuperiorName", "上長名"],
	["pageSpanNewPassword", "新パスワード(変更する場合に入力)"],
	["pageSpanForNewPasswordConfirmation", "新パスワード確認用"],
	["pageSpanRemarks", "備考"],
	["pageSpanValidclassification", "有効区分"],
	["optionvalidclassification", "有効"],
	["optionInvalidclassification", "無効"],
	["pageSpanTerminationDate", "退職年月日"],
	["buttonUpateEmployeeInformation", "社員を更新"],
	["pageSpanSearchEmployeeDetails", "社員情報の検索"],
	["pageCardDivTotalNumberofStaff", "合計スタッフ数"],
	["pageSpanHeadingEmployeeRegister", "社員登録"],
	["pageSpanSubHeadingStaffDetails", "従業員として登録することができます。"],
	["pageSpanHeadingEmployeeDetails", "従業員の詳細"],
	["pageSpanEmployeeName", "名前"],
	["pageSpanPassword", "パスワード "],
	["pageSpanForPasswordConfirmation", "パスワード(確認) "],
	["optionAccountTypeSelect", "口座種別を選択"],
	["pageSpanRetirementDate", "退職日"],
	["buttonSaveEmployeeInformation", "従業員の登録"],
	["optionPersonInCharge", "担当者の選択"],
	["optionPersonInCharge1", "担当者1"],
	["optionPersonInCharge2", "担当者2"],
	["optionSelectvalidclassification", "有効な分類を選択"],
	["pageLabelDateJoinFrom", "入社日"],
	["optionSuperiorName", "スペリオルネームの選択"],

];

	employeeErrorArray = {"E2180":"空であってはならない","E2184":"無効な名前","E2185":"無効なメール","E2186":"パスワードが一致しない","E2183":"参加日が一致しません", "E2187":"このメールはすでに存在しています"}