function switchLanguage(siteLanguage) {
    convertContentToLanguage(TopMenu);
    convertContentToLanguage(LeftMenu);
    convertContentToLanguage(section1);
  
}

TopMenu = [
 
      ["menuButtonProfile", "プロフィール"],
      ["menuButtonManual", "マニュアル"],
      ["menuButtonLogout", "ログアウト"],
];

LeftMenu = [
		["pageTitle", "スタッフ一覧"],
		["menuSpanHome", "Home"],
		["menuSubSpanHome", "Home"],
		["menuSpanCustomer", "顧客管理"],
		["menuSpanQuoMan", "見積書管理"],
		["menuSpanInvoiceMan", "請求書管理"],
		["menuSpanMatterMan", "案件管理"],
		["menuSpanAssignment", "アサイン管理"],
		["menuSpanStaff", "スタッフ管理"],
		["menuSpanShifftSchedule", "スタッフシフト予定管理" ],
		["menuSpanAttendance", "勤怠管理"],
		["menuSpanPayrollMan", "給与管理"],
		["menuSpanAnnualPayroll", "Annual Payroll"],
		["menuSpanPaidGrand", "Paid Grant"],
		["menuSpanEmployeeManagement", "社員管理"],
		["menuSpanAgencyManagement", "代理店管理"],
		["menuSpanStaffPageLogin", "スタッフページログイン"],
		["menuSpanMasterAdmin", "マスタ管理"],
		["menuSubSpanCompanyInformationManagement", "会社情報管理"],
		["menuSubSpanConsumptionTaxManagement", "消費税管理"],
		["menuSubSpanDailyIncomeTax", "源泉徴収日額管理"],
		["menuSubSpanMonthlyTaxManagement", "源泉徴収月額管理"],
		["menuSubSpanAllowanceManagement", "残業・休日手当管理"],
		["menuSubSpanPaidTableManagement", "有給テーブル管理"],
		["menuSubSpanContractTerms", "契約書条件"],
		["menuSubSpanEmailTemplateManagement", "メールテンプレート管理"],
		["menuSubSpanQuoteTemplateManagement", "見積りテンプレート管理"],
		["menuSpanAboutCompliance", "コンプライアンスについて"],
		["menuTermsofServices", "利用規約"],
		["menuPrivacyPolicy", "プライバシーポリシー"],
		["menuBasedCommercial", "特定商取引法に基づく表示"]
];

section1 = [
	["pageTitlePayrollPayslip", "給与明細書"],
	["pageSpanHeadingPayslip","給与明細"],
	["buttonSpanReturn","  戻る  "],
	["pageSpanSubHeadingPayrollPayslip","給与情報の修正、給与明細メールの送信ができます。"],
	["accordionStaffInformation","スタッフ情報"],
	["pageSpanStaffCode","スタッフコード"],
	["pageSpanStaffName","スタッフ名"],
	["pageSpanStaffMobile","スタッフ携帯"],
	["pageSpanStaffNearestStation","スタッフ最寄駅"],
	["pageSpanSalaryPaymentMethod","給与支払方法"],
	["pageSpanSalaryPaymentForm","給与支払形態"],
	["pageSpanStandardClosingDate","標準締日"],
	["pageSpanTheTargetDate","対象年月"],
	["pageSpanNumberOfSalaries","給与回数"],
	["buttonSaveInformation","Save Information"],
	["accordionSalaryInformation","給与情報"],
	["pageSpanTargetPeriod","対象期間"],
	["pageSpanTitleSupply","支給"],
	["pageSpanSalaryAllowance","(S)給料手当"],
	["payrollSalaryAllowanceHelp","※課税分の手当金額を含む"],
	//["pageSpanOtherPayment","(S) Other Payment"],
	["pageSpanAdvancePayment","(S)立替金"],
	["pageSpanTaxExemptionAllowance","(S)非課税手当"],
	["pageSpanPaidDays","有給日数"],
	["pageSpanPaidAmount","(S)有給金額"],
	["pageSpanSubtotal","小計"],
	["pageSpanSubtotalHelp","給料手当＋立替金＋非課税手当＋有給金額"],
	["pageSpanSubtotalHelpDaily","給与手当＋立替金＋非課税枠＋支給額"],
	["pageSpanTaxable","課税対象"],
	["pageSpanTaxableHelp","給料手当＋有給金額"],
	["pageSpanTaxableHelpDaily","給与手当＋支給額"],
	["pageSpanTitleDeduction","控除"],
	["pageSpanPrepaidAmount","(S)前払金額"],
	["pageSpanOtherDeductions","(S)その他控除"],
	["pageSpanHealthInsurancePremium","(S)健康保険料"],
	["pageSpanWelfarePensionPremium","(S)厚生年金保険料"],
	["pageSpanLongTermCareInsurance","(S)介護保険料"],
	["pageSpanEmploymentInsurance","(S)雇用保険料"],
	["pageSpanIncomeTax","(S)立替金"],
	["pageSpanResidentTax","(S)住民税"],
	["pageSpanAbsenceDays","欠勤日数"],
	["pageSpanAbsenceDeductionAmount","(S)欠勤控除金額"],
	["pageSpanNumberDaysLeaveEarly","早退日数"],
	["pageSpanEarlyDepartureDeductionAmount","(S)早退控除金額"],
	["pageSpanSubtotalDeduction","小計"],
	["pageSpanSubtotalDeductionHelp","前払金額＋その他控除額＋法人税等＋欠勤控除額＋早退控除額"],
	["buttonSaveSalaryInformation","Save Information"],
	["accordionBonusInformation","賞与情報"],
	["pageSpanTitleSupply","支給額"],
	["pageSpanBonusAmount","(S)賞与額"],
	["buttonCalculateBonusSocialInsurance","  社会保険料を計算"],
	["pageSpanTitleDeduction","控除"],
	//["pageSpanHealthInsurancePremium","(S)健康保険料"],
	//["pageSpanWelfarePensionPremium","(S)厚生年金保険料"],
	//["pageSpanLongTermCareInsurance","(S)介護保険料"],
	//["pageSpanEmploymentInsurance","(S)雇用保険料"],
	//["pageSpanIncomeTax","(S)所得税"],
	//["pageSpanSubtotalDeduction","小計"],
	["pageSpanBonusSocialInsuranceHelp","社会保険料"],
	["pageSpanTotalDeductionPayment","差引支払合計"],
	["pageSpanTotalPayment","支払合計"],
	["totalPaymentHelp","支給－控除"],
	["buttonSaveBonusInformation","保存"],
	["accordionWorkInformationList","勤務情報一覧"],
	["tableSearchTHNo","No."],
	["tableWorkInfoTHImplementationDate","実施日"],
	["tableWorkInfoTHCase","案件"],
	["tableWorkInfoTHScheduledActualWork","実働予定時間"],
	["tableWorkInfoTHStart","開始"],
	["tableWorkInfoTHEnd","終了"],
	["tableWorkInfoTHBreakTime","休憩時間"],
	["tableWorkInfoTHInsideMidnightBreak","(内)深夜休憩時間"],
	["tableWorkInfoTHActualWorkingHours","実働時間"],
	["tableWorkInfoTHOvertimeHours","残業時間"],
	["tableWorkInfoTHMidnightWorkingHours","深夜労働時間"],
	["tableWorkInfoTHHolidayWorkingHours","休日労働時間"],
	["tableWorkInfoTHBasicSalary","基本給"],
	["tableWorkInfoTHOvertimeCosts","残業費"],
	["tableWorkInfoTHMidnightLaborCosts","深夜労働費"],
	["tableWorkInfoTHHolidayLaborCosts","休日労働費"],
	["tableWorkInfoTHAllowance","手当"],
	["tableWorkInfoTHTransportationExpenses","交通費"],
	["tableWorkInfoTHPurchaseMoney","買取費"],
	["tableWorkInfoTHTExpenses","経費"],
	["tableWorkInfoTHAccommodationFee","宿泊費"],
	["tableWorkInfoTHOthers","その他"],
	["tableWorkInfoTHTAdvancePayment","前払金"],
	["tableWorkInfoTHOtherDeductions","その他控除"],
	["tableWorkInfoTHDailySalaryMonthlySalaryDeduction","日給月給控除"],
	["tableWorkInfoTHTotal","合計"],
	["tableWorkInfoTHPaid","支払済"],
	["buttonSaveWorkInformation","保存"],
	["accordionMonthlySalaryInformationList","月給情報一覧"],
	["tableSearchTHNo","No."],
	["tableWorkInfoTHImplementationPeriod","実施期間"],
	["tableWorkInfoTHCase","案件"],
	["tableWorkInfoTHProjectSalaryUnit","案件給与単価"],
	["tableWorkInfoTHBasicSalary","	基本給"],
	["pageSpanDontSendPaySlips","給与明細書をスタッフに送信しない"],
	["pageSpanDontSendPaySlipsHelp","スタッフに給与明細書をメール送信しない場合は、チェックボックスを選択してください"],
	["buttonSaveWorkInformation","保存"],
	["accordionApprovalLocationInfo","承認情報"],
	["pageSpanApprovalDateAndTime","承認日時"],
	["pageSpanAuthorizer","承認者"],
	["pageSpanApprovalStatus","承認状態"],
	["optionApprovalStatus","承認ステータスの選択"],
	["option1ApprovalStatus","承認済"],
	["option2ApprovalStatus","未承認"],
	["pageSpanApprovalStatusHelp1","※承認に変更して保存すると給与額が確定します。変更ができなくなるので注意してください。"],
	["pageSpanApprovalStatusHelp2","※承認するとスタッフに給与明細PDFをメールで送信します。"],
	["pageSpanApprovalStatusHelp3","※給与明細書は以下からエクセルでダウンロードすることもできます。"],
	["pageSpanPaySlip","給与明細書"],
	["buttonDownloadPayslips","給与明細書をエクセルでダウンロード"],
	["pageSpanRemarks","備考"],
	["buttonUpdatePaySlip","給与明細を更新する"],
	["pageTitlePayrollManagement","給与管理"],
	["pageSpanHeadingSalaryList","給与一覧"],
	["pageSpanSubHeadingSalaryList","経費報告提出状態別に、スタッフごとの給与情報を確認できます。"],
	["buttonSpanCSVOutputForPayroll","一括処理CSV出力"],// 一覧データはExcelでカスタマイズして資料作成・データ分析にご活用できます
	["buttonSpanBatchProcessingCSVOutput","一括処理CSV入力"],//  給与情報を一括で編集するCSVを出力します    
	["buttonSpanBatchProcessingCSVInput","給与振込用CSV出力"],// 給与情報を一括で編集するCSVを出力します 
	["buttonSpanProcessedListCSV","処理済一覧CSV出力"],// 一覧データはExcelでカスタマイズして資料作成・データ分析にご活用できます 
	["pageSpanSearch","検索"],
	["pageLabelSalaryPaymentForm","給与支払形態"],
	["optionsalaryPaymentForm","給与支払方法の選択"],
	["option1salaryPaymentForm","日払い/週払い"],
	["option2salaryPaymentForm","月払い"],
	["pageLabelTargetYear","対象年"],
	["pageLabelTargetMonth","対象月"],
	["pageOptionTargetMonth","対象月の選択"],
	["pageOptionJanuary","1月"],
	["pageOptionFebruary","2月"],
	["pageOptionMarch","3月"],
	["pageOptionApril","4月"],
	["pageOptionMay","5月"],
	["pageOptionJune","6月"],
	["pageOptionJuly","7月"],
	["pageOptionAugust","8月"],
	["pageOptionSeptember","9月"],
	["pageOptionOctober","10月"],
	["pageOptionNovember","11月"],
	["pageOptionDecember","12月"],
	["pageLabelSalaryClosingDate","給与締日"],
	["OptiontargetDate","選択してください"],
	["OptiontargetDate0","月末"],
	["OptiontargetDate1","1日"],
	["OptiontargetDate2","2日"],
	["OptiontargetDate3","3日"],
	["OptiontargetDate4","4日"],
	["OptiontargetDate5","5日"],
	["OptiontargetDate6","6日"],
	["OptiontargetDate7","7日"],
	["OptiontargetDate8","8日"],
	["OptiontargetDate9","9日"],
	["OptiontargetDate10","10日"],
	["OptiontargetDate11","11日"],
	["OptiontargetDate12","12日"],
	["OptiontargetDate13","13日"],
	["OptiontargetDate14","14日"],
	["OptiontargetDate15","15日"],
	["OptiontargetDate16","16日"],
	["OptiontargetDate17","17日"],
	["OptiontargetDate18","18日"],
	["OptiontargetDate19","19日"],
	["OptiontargetDate20","20日"],
	["OptiontargetDate21","21日"],
	["OptiontargetDate22","22日"],
	["OptiontargetDate23","23日"],
	["OptiontargetDate24","24日"],
	["OptiontargetDate25","25日"],
	["OptiontargetDate26","26日"],
	["OptiontargetDate27","27日"],
	["OptiontargetDate28","28 th"],
	["OptiontargetDate29","29 th"],
	["OptiontargetDate30","30 th"],
	["OptiontargetDate31","31 st"],
	["pageLabelName","名前"],
	["pageLabelNameKatakana","名前カナ"],
	["pageLabelStaffCode","スタッフコード"],
	["pageLabelInChargeStaff","スタッフ担当者"],
	["OptionSelectInChargeStaff","担当者の選択"],
	["OptionSelectInChargeStaff1","担当者 1"],
	["OptionSelectInChargeStaff2","担当者 2"],
	["pageLabelBelonging","所属"],
	["clearAllBtn","全て消去"],
	["searchBtn","検索"],
	["pageCardDivTotalStaff","合計スタッフ数"],
	["pageCardDivDailyWeeklyPayments","日払い/週払い"],
	["pageCardDivMonthlyPayments","月々のお支払い"],
	["home-basic-tab","処理済"],
	["profile-basic-tab","未処理(経費報告提出済)"],
	["contact-basic-tab","未処理(経費報告未提出)"],
	["pageSpanSearchProcessed","処理済"],
	["pageSpanSearchProcessedHelp1","日払い給与額が確定した派遣スタッフが表示されます。 給与額の表示部分で支払い状況(支払済/未払い)を確認することができます。"],
	["pageSpanSearchProcessedHelp2","尚、支払い状況を変更する場合は、詳細⇒勤務情報一覧の対象案件を選択、日払い給与情報の給与支払チェックボックスを選択して下さい。"],
	["tableSearchTHNo","No."],
	["tableSearchTHChoice","選択"],
	["tableSearchTHStaffMobile","スタッフ（携帯）"],
	["tableSearchTHSalaryPaymentMethod","給与支払方法"],
	["tableSearchTHClosingDate","締日"],
	["tableSearchTHApprovalDate","承認日時"],
	["tableSearchTHAuthorizer","承認者"],
	["tableSearchTHSalary","給与額"],
	["tableSearchTHInChargeStaff","スタッフ担当者"],
	["buttonSpanCheckAll","全てをチェックする"],
	["buttonSpanUncheckAll","全てのチェックを外す"],
	["pageSpanSearchUnprocessedExpenseReport","未処理(経費報告提出済)"],
	["pageSpanSearchUnprocessedHelp","日払い給与額が確定していない派遣スタッフが表示されます。給与額の確定はスタッフアサイン詳細から「給与情報を計算」ボタンを押してください。"],
	["tableSearchTHNo","No"],
	["tableSearchTHChoice","選択"],
	["tableSearchTHStaffMobile","スタッフ（携帯）"],
	["tableSearchTHSalaryPaymentMethod","給与支払方法"],
	["tableSearchTHClosingDate","締日"],
	["tableSearchTHImplementationDate","実施日"],
	["tableSearchTHProjectTitle","案件名"],
	["tableSearchTHWorkLocation","勤務地"],
	["tableSearchTHSalary","給与額"],
	["tableSearchTHInChargeStaff","スタッフ担当者"],
	["buttonSpanCheckAll","全てをチェックする"],
	["buttonSpanUncheckAll","全てのチェックを外す"],
	["pageSpanSearchUnprocessedExpenseNotReport","未処理(経費報告未提出)"],
	["pageSpanSearchUnprocessedNotHelp","経費報告を提出していない派遣スタッフが表示されます。"],
	["tableSearchTHNo","No."],
	["tableSearchTHChoice","選択"],
	["tableSearchTHStaffMobile","スタッフ（携帯）"],
	["tableSearchTHSalaryPaymentMethod","給与支払方法"],
	["tableSearchTHClosingDate","締日"],
	["tableSearchTHImplementationDate","実施日"],
	["tableSearchTHProjectTitle","案件名"],
	["tableSearchTHWorkLocation","勤務地"],
	["tableSearchTHSalary","給与額"],
	["tableSearchTHInChargeStaff","スタッフ担当者"],
	["buttonSpanCheckAll","全てをチェックする"],
	["buttonSpanUncheckAll","全てのチェックを外す"],
	["selectSalaryPaymentForm","給与支払方法の選択"],
	["selectSalaryPaymentFormDaily","日払い/週払い"],
	["selectSalaryPaymentFormMonthly","月払い"],
	["targetYear","年次の入力"],
	["salaryListName","名前の入力"],
	["salaryListNameKatakana","名前をカタカナで入力"],
	["staffCode","スタッフコードの入力"],
	["salaryListBelonging","所属を入力"],
	["pageCardDivTotalProceedStaff","総収入スタッフ"],
	["pageCardDivTotalUnprocessedSubmitted","未処理の送信済みの合計"],
	["pageCardDivTotalUnprocessedNotSubmitted","未処理の未提出の合計"],

];


payrollErrorArray ={"E2140":"空っぽではダメなんです!", 
					"E2141":"無効な目標年",	
					"E2142":"無効な名前",	
					"E2143":"無効な名前のカタカナ",
					"E2144":"無効なスタッフコード",	 
					"E2145":"無効なその他の支払い",
					"E2146":"無効なプリペイド金額",
					"E2147":"その他の控除が無効",
					"E2148":"無効な欠席日数",
					"E2149":"無効な欠勤控除額",
					"E2150":"早期退職の日数が無効",
					"E2151":"早期退職者控除額が無効",
					"E2152":"無効なボーナス額",
					"E2153":"健康保険料が無効 ",
					"E2154":"無効な厚生年金保険料",
					"E2155":"介護保険料が無効",
					"E2156":"無効な雇用保険料",
					"E2157":"無効な所得税",
					"E2158":"無効な有給日数",
					"E2159":"無効な支払額", 
 				  	}