function setLanguage(selectedLanguage)
{

    if (selectedLanguage == "English") {
        localStorage.setItem('language', "English");
        switchToEnglish();       
    } else if (selectedLanguage == "Japanese") {
        localStorage.setItem('language', "Japanese");
        switchToJapanese();
    }
}

function getLanguage() {
    if (localStorage.getItem("language") === null){
         localStorage.setItem('language', "Japanese");
         return localStorage.getItem('language');
    }else{
         return localStorage.getItem('language');
    }
}

function ToggleLanguageJapanese() {
    console.log("ToggleLanguageJapanese")
    setLanguage("Japanese");
    switchToJapanese();
}

function ToggleLanguageEnglish() {
    setLanguage("English");
    switchToEnglish();
}


function switchToJapanese() {
    convertContentIntoJapaneseAndEnglish(TopMenu, "Japanese");
    convertContentIntoJapaneseAndEnglish(LeftMenu, "Japanese");
    convertContentIntoJapaneseAndEnglish(StaffManagement, "Japanese");
    convertContentIntoJapaneseAndEnglish(StaffManagement_2, "Japanese");
    convertContentIntoJapaneseAndEnglish(StaffDetails, "Japanese");
    // convertContentIntoJapaneseAndEnglish(ForgotPasswordNewPasswordRegisterForm, "Japanese");
}

function switchToEnglish() {
    convertContentIntoJapaneseAndEnglish(TopMenu, "English");
    convertContentIntoJapaneseAndEnglish(LeftMenu, "English");
    convertContentIntoJapaneseAndEnglish(StaffManagement, "English");
    convertContentIntoJapaneseAndEnglish(StaffManagement_2, "English");
    convertContentIntoJapaneseAndEnglish(StaffDetails, "English");
    // convertContentIntoJapaneseAndEnglish(ForgotPasswordMobileNumberRegisterForm, "English");
 
}



function convertContentIntoJapaneseAndEnglish(contentArray, language) {
    var languageIndex = 0;
    //languageIndex = (language === "English" ? "1" : "2");

    switch (language) {
        case "English":
            languageIndex = 1;
            break;
        case "Japanese":
            languageIndex = 2;
            break;
        default:
        // code block
    }
    for (var i = 0; i < contentArray.length; i++) {
        if (document.getElementById(contentArray[i][0]) == null) {

        } else {
            document.getElementById(contentArray[i][0]).innerHTML = contentArray[i][languageIndex];
            document.getElementById(contentArray[i][0]).placeholder = contentArray[i][languageIndex];
            document.getElementById(contentArray[i][0]).title  = contentArray[i][languageIndex];
            // document.getElementsByName(contentArray[i][0])[0].innerHTML = contentArray[i][languageIndex];
        }
    }
}
let TopMenu = [
 
    ["menuButtonProfile", "Profile", "プロフィール"],
    ["menuButtonManual", "Manual", "マニュアル"],
    ["menuButtonLogout", "Logout", "ログアウト"]
];

let LeftMenu = [
    ["pageTitle", "Staff List", " スタッフリスト"],
    ["menuSpanHome", "Home", "ホーム"],
    ["menuSubSpanHome", "Home", "ホーム"],
    ["menuSpanCustomer", "Customer Management", "顧客管理"],
    ["menuSpanQuoMan", "Quotation Management", "見積書管理"],
    ["menuSpanInvoiceMan", "Invoice Management", "請求書管理"],
    ["menuSpanMatterMan", "Case Management", "案件管理"],
    ["menuSpanAssignment", "Assignment Management", "アサイン管理"],
    ["menuSpanStaff", "Staff Management", "スタッフ管理"],
    ["menuSubSpanStaffMan", "Staff Management", "スタッフ マネジメント"],
    ["menuSubSpanStaffMan2", "Staff Management-2" , "スタッフ マネジメント-2"],
    ["menuSpanShifftSchedule", "Shift Schedule" , "スタッフシフト予定管理"],
    ["menuSpanAttendance", "Attendance", "勤怠管理"],
    ["menuSpanPayrollMan", "Payroll Management", "給与管理"],
    ["menuSpanAnnualPayroll", "Annual Payroll", "年間給与管理"],
    ["menuSpanPaidGrand", "Paid Grant", "有休付与管理"],
    ["menuSpanEmployeeManagement", "Employee Management", "従業員管理"],
    ["menuSpanStaffPageLogin", "Staff Page Login", "スタッフページログイン"],
    ["menuSpanMasterAdmin", "Master Admin", "マスター管理"],
    ["menuSubSpanQuoteTemplateManagement", "Quote Template Management", "見積もりテンプレート管理"],
    ["menuSpanAboutCompliance", "About Compliance", "コンプライアンスについて"]
];

let StaffManagement = [
    ["pageSpanHeading", " Staff List", " スタッフ一覧"],
    ["buttonSpanStaffReg", "Staff Registration", "スタッフ登録"],
    ["buttonSpanBatchReg", "Batch Registration", "スタッフ一括登録"],
    ["buttonSpanStaffListCSV", "Staff List CSV Output", "スタッフ一覧CSVを出力"],
    ["pageSpanSearch", " Search", " 検索"],
    ["pageLabelGivenNames", "Given Names", "名前"],
    ["givenNames", "Enter Given Names", "名前を入力してください"],
    ["pageLabelNameKatakana", "Name Katakana", "名前カナ"],
    ["nameKatakana", "Enter Name Katakana", "フリガナを入力してください"],
    ["pageLabelStaffCode", "Staff Code", "スタッフコード"],
    ["staffCode", "Enter Staff Code", "スタッフコードを入力してください"],
    ["pageLabelPrefectures", "Prefectures", "都道府県"],
    ["selectOptionSelectPrefectures", "Select Prefecture" , "県を選択"],
    ["pageLabelStreetAddress", "Street Address" , "住所 "],
    ["streetAddress", "Enter Street Address", "住所を入力してください"],
    ["pageLabelDOB", "Date of Birth", "生年月日From/To"],
    ["dateOfBirthFrom", "From", "から"],
    ["dateOfBirthTo", "To", "に"],
    ["pageLabelMobilePhone", "Mobile Phone", "携帯"],
    ["mobilePhone", "Enter Mobile Number", "携帯電話番号を入力してください"],
    ["pageLabelStaffStaff", "In Charge Staff", "スタッフ担当者"],
    ["staffInChargeStaff", "Enter In Charge Staff", "担当スタッフを入力してください"],
    ["pageLabelMailAddress", "Mail Address", "メールアドレス"],
    ["mailAddress", "Enter Mail Address", "メールアドレスを入力してください"],
    ["pageLabelExperience", "Experience", "経験"],
    ["experience", "Enter Experience", "職務履歴を入力してください"],
    ["pageLabelRegistrationDivision", "Registration Division", "登録区分"],
    ["selectOptionSelectRegistrationDevision", "Select Registration Division", "登録部門を選択"],
    ["pageLabelDispatchClassification", "Dispatch Classification", "派遣区分"],
    ["selectOptionSelectDispatchClassification", "Select Dispatch Classification", "派遣区分を選択"],
    ["pageLabelOccupationClassification", "Occupation Classification", "職種区分"],
    ["selectOptionSelectOccupationClassification", "Select Occupation Classification", "職業分類を選択します"],
    ["pageLabelAttribute", "Attribute", "属性"],
    ["pageOption0Attribute", "Select Attribute", "属性を選択"],
    ["pageOption1Attribute", "Elderly", "お年寄り"],
    ["pageOption2Attribute", "Foreign Student", "留学生"],
    ["pageOption3Attribute", "Foreign worker", "外国人労働者"],
    ["pageOption4Attribute", "High schooler", "高校生"],
    ["attribute", "Enter Attribute", "属性を入力してください"],
    ["pageLabelValidClassification", "Valid Classification", "*有効区分"],
    ["selectOptionSelectValidClassification", "Select Valid Classification", "有効な分類を選択してください"],
    ["pageLabelCurrentUnitPrice", "Current Unit Price", "現在単価From/To"],
    ["unitPriceFrom", "From", "から"],
    ["unitPriceTo", "To", "に"],
    ["pageLabelBelongs", "Belongs", "所属"],
    ["belongs", "Enter Belongs", "所属する"],
    ["pageLabelGender", "Gender", "性別"],
    ["selectOptionSelectGender", "Select Gender", "性別を選択して下さい"],
    ["selectOptionSelectGenderMale", "Male", "男"],
    ["selectOptionSelectGenderFemale", "Female", "女性"],
    ["selectOptionSelectGender_1", "Select Gender", "性別を選択して下さい"],
    ["selectOptionSelectGenderMale_1", "Male", "男"],
    ["selectOptionSelectGenderFemale_1", "Female", "女性"],
    ["clearAllBtn", "Clear All", "すべてクリア"],
    ["searchBtn", "Search", "検索"],
    ["pageCardDivTotalStaff", "Total Number of Staff", "スタッフの総数"],
    ["pageCardDivTotalActiveStaff", "Total Active Staff", "総有効スタッフ"],
    ["pageCardDivTotalAvailableStaff", "Total Available Staff", "派遣可能なスタッフの総数"],
    ["pageCardDivTotalPendingStaff", "Total Pending Staff", "保留中のスタッフの合計"],
    
    ["pageSpanSearchStaffDetails", " Search Staff Details", " スタッフの詳細を検索"],

    ["tableSearchStaffTHNo", "No", "番号"],
    ["tableSearchStaffTHChoice", "Choice", "選択"],
    ["tableSearchStaffTHName", "Name", "名前"],
    ["tableSearchStaffTHNameKatakana", "Name Katakana", "名前カナ"],
    ["tableSearchStaffTHAttribute", "Attribute", "属性"],
    ["tableSearchStaffTHStaffCode", "Staff Code", "スタッフコード"],
    ["tableSearchStaffTHStaffStaff", "In Charge Staff", "スタッフ担当者"],
    ["tableSearchStaffTHCellPhone", "Cell Phone", "携帯"],
    ["tableSearchStaffTHEmailAddress", "Email Address", "メールアドレス"],
    ["tableSearchStaffTHDispatchClassification", "Dispatch Classification", "派遣区分"],
    ["tableSearchStaffTHPrefecture", "Prefecture", "都道府県"],
    ["tableSearchStaffTHPostalCode", "Postal Code", "郵便番号"],
    ["tableSearchStaffTHExperience", "Experience", "経験"],
    ["tableSearchStaffTHAddress", "Address", "住所"],
    ["tableSearchStaffTHOccupationClassification", "Occupation Classification", "職種区分"],
    ["tableSearchStaffTHDOB", "Date of Birth/Age/Gender", "生年月日/年齢/性別"],
    ["tableSearchStaffTHRegistrationCategory", "Registration Category/Valid Category", "登録済み/有効なカテゴリ"],
    ["tableSearchStaffTHUnitPrice", "Current Unit Price", "現在単価From/To"],

    ["tableButtonDetails", "Details", "詳細"],
    ["tableButtonScheduleShift", "Schedule Shift", "スケジュールシフト"],
    ["tableButtonAssignmentList", "Assignment List", "割り当てリスト"],
    ["tableButtonDetails_2", "Details", "詳細"],
    ["tableButtonScheduleShift_2", "Schedule Shift", "スケジュールシフト"],
    ["tableButtonAssignmentList_2", "Assignment List", "割り当てリスト"],
    ["tableButtonDetails_3", "Details", "詳細"],
    ["tableButtonScheduleShift_3", "Schedule Shift", "スケジュールシフト"],
    ["tableButtonAssignmentList_3", "Assignment List", "割り当てリスト"],
    // ["search_staff_table_previous", "Previous", "前"],
    // ["search_staff_table_next", "Next", "次"],
    ["buttonSpanCheckAll", "Check All", "すべてチェック"],
    ["buttonSpanUncheckAll", "Uncheck All", "すべてチェックを外す"],
    ["buttonSpanBatchDeletion", "Batch Deletion", "一括削除"],
    ["buttonSpanBatchChange", "Change In Charge Staff", "担当スタッフ交代"]
    
];


let StaffManagement_2 = [
    ["pageSpanHeading", " Staff List", " スタッフリスト"],
    ["buttonSpanStaffReg", "Staff Registration", "スタッフ登録"],
    ["buttonSpanBatchReg", "Batch Registration", "一括登録"],
    ["buttonSpanStaffListCSV", "Staff List CSV Output", "スタッフリストCSV出力"],
    ["pageSpanSearch", " Search", " 検索"],
    ["pageLabelGivenNames", "Given Names", "名前"],
    ["givenNames", "Enter Given Names", "名前を入力してください"],
    ["pageLabelNameKatakana", "Name Katakana", "フリガナ"],
    ["nameKatakana", "Enter Name Katakana", "フリガナを入力してください"],
    ["pageLabelStaffCode", "Staff Code", "スタッフコード"],
    ["staffCode", "Enter Staff Code", "スタッフコードを入力してください"],
    ["pageLabelPrefectures", "Prefectures", "都道府県"],
    ["selectOptionSelectPrefectures", "Select Prefecture" , "県を選択"],
    ["pageLabelStreetAddress", "Street Address" , "住所"],
    ["streetAddress", "Enter Street Address", "住所を入力してください"],
    ["pageLabelDOB", "Date of Birth", "生年月日"],
    ["dateOfBirthFrom", "From", "から"],
    ["dateOfBirthTo", "To", "に"],
    ["pageLabelMobilePhone", "Mobile Phone", "携帯電話"],
    ["mobilePhone", "Enter Mobile Number", "携帯電話番号を入力してください"],
    ["pageLabelStaffStaff", "In Charge Staff", "担当スタッフ"],
    ["staffStaff", "Enter Staff", "スタッフを入力してください"],
    ["pageLabelMailAddress", "Mail Address", "メールアドレス"],
    ["mailAddress", "Enter Mail Address", "メールアドレスを入力してください"],
    ["pageLabelExperience", "Experience", "職務履歴"],
    ["experience", "Enter Experience", "職務履歴を入力してください"],
    ["pageLabelRegistrationDivision", "Registration Division", "登録区分"],
    ["selectOptionSelectRegistrationDevision", "Select Registration Division", "登録部門を選択"],
    ["selectOptionSelectRegistrationDevision1", "Main registration", "主な登録"],
    ["selectOptionSelectRegistrationDevision2", "Temporary registration", "仮登録"],
    ["pageLabelDispatchClassification", "Dispatch Classification", "派遣区分"],
    ["selectOptionSelectDispatchClassification", "Select Dispatch Classification", "派遣区分を選択"],
    ["pageLabelOccupationClassification", "Occupation Classification", "職業分類"],
    ["selectOptionSelectOccupationClassification", "Select Occupation Classification", "職業分類を選択します"],
    ["pageLabelAttribute", "Attribute", "属性"],
    ["selectOptionOption0Attribute", "Select Attribute", "属性を選択"],
    ["selectOptionOption1Attribute", "Elderly", "お年寄り"],
    ["selectOptionOption2Attribute", "Foreign Student", "留学生"],
    ["selectOptionOption2Attribute", "Foreign Student", "留学生"],
    ["attribute", "Enter Attribute", "属性を入力してください"],
    ["pageLabelValidClassification", "Valid Classification", "*有効区分"],
    ["selectOptionSelectValidClassification", "Select Valid Classification", "有効な分類を選択してください"],
    ["pageLabelCurrentUnitPrice", "Current Unit Price", "現在の単価"],
    ["unitPriceFrom", "From", "から"],
    ["unitPriceTo", "To", "に"],
    ["pageLabelBelongs", "Belongs", "所属"],
    ["belongs", "Enter Belongs", "所属する"],
    ["pageLabelGender", "Gender", "性別"],
    ["selectOptionSelectGender", "Select Gender", "性別を選択して下さい"],
    ["clearAllBtn", "Clear All", "すべてクリア"],
    ["searchBtn", "Search", "検索"],
    ["pageCardDivTotalStaff", "Total Number of Staff", "スタッフの総数"],
    ["pageCardDivTotalActiveStaff", "Total Active Staff", "総有効スタッフ"],
    ["pageCardDivTotalAvailableStaff", "Total Available Staff", "派遣可能なスタッフの総数"],
    ["pageCardDivTotalPendingStaff", "Total Pending Staff", "保留中のスタッフの合計"],
    
    ["pageSpanSearchStaffDetails", " Search Staff Details", " スタッフの詳細を検索"],

    ["tableSearchStaffTHNo", "No", "番号"],
    ["tableSearchStaffTHChoice", "Choice", "選択"],
    ["tableSearchStaffTHName", "Name", "名前"],
    ["tableSearchStaffTHNameKatakana", "Name Katakana", "フリガナ"],
    ["tableSearchStaffTHAttribute", "Attribute", "属性"],
    ["tableSearchStaffTHStaffCode", "Staff Code", "スタッフコード"],
    ["tableSearchStaffTHStaffStaff", "In Charge Staff", "担当スタッフ"],
    ["tableSearchStaffTHCellPhone", "Cell Phone", "携帯電話"],
    ["tableSearchStaffTHEmailAddress", "Email Address", "メールアドレス"],
    ["tableSearchStaffTHDispatchClassification", "Dispatch Classification", "派遣区分"],
    ["tableSearchStaffTHPrefecture", "Prefecture", "県"],
    ["tableSearchStaffTHPostalCode", "Postal Code", "郵便番号"],
    ["tableSearchStaffTHExperience", "Experience", "職務履歴"],
    ["tableSearchStaffTHAddress", "Address", "住所"],
    ["tableSearchStaffTHOccupationClassification", "Occupation Classification", "職業分類"],
    ["tableSearchStaffTHDOB", "Date of Birth/Age/Gender", "生年月日/年齢/性別"],
    ["tableSearchStaffTHRegistrationCategory", "Registration Category/Valid Category", "登録済み/有効なカテゴリ"],
    ["tableSearchStaffTHUnitPrice", "Current Unit Price", "現在の単価"],

    // ["tableButtonDetails", "Details", "詳細"],
    // ["tableButtonScheduleShift", "Schedule Shift", "スケジュールシフト"],
    // ["tableButtonAssignmentList", "Assignment List", "割り当てリスト"],
    // ["tableButtonDetails_2", "Details", "詳細"],
    // ["tableButtonScheduleShift_2", "Schedule Shift", "スケジュールシフト"],
    // ["tableButtonAssignmentList_2", "Assignment List", "割り当てリスト"],
    // ["tableButtonDetails_3", "Details", "詳細"],
    // ["tableButtonScheduleShift_3", "Schedule Shift", "スケジュールシフト"],
    // ["tableButtonAssignmentList_3", "Assignment List", "割り当てリスト"],
    
    // ["search_staff_table_previous", "Previous", "前"],
    // ["search_staff_table_next", "Next", "次"],
    ["buttonSpanCheckAll", "Check All", "すべてチェック"],
    ["buttonSpanUncheckAll", "Uncheck All", "すべてチェックを外す"],
    ["buttonSpanBatchDeletion", "Batch Deletion", "一括削除"],
    ["buttonSpanBatchChange", "Batch Change", "一括変更"]
    
];


let StaffDetails = [
       ["pageTitleStaffRegistration", " Staff Registration", " スタッフ登録"],
       ["pageTitleStaffDetails", " Staff Details", " スタッフ 詳細"],
       ["pageSpanHeadingStaffDetails", " Staff Details", " スタッフ 詳細"],
       ["pageSpanHeadingStaffRegister", " Staff Registration", " スタッフ登録"],
       ["pageSpanSubHeadingStaffDetails", "You can modify the staff, check the shift schedule of this staff, and check the assignment status.", "スタッフの修正、このスタッフのシフトスケジュールの確認、割り当て状況の確認ができます。"],
       ["buttonSpanStaffDetailsDelete", "Delete", "消去"],
       ["buttonValueSpanStaffDetailsDelete", "Delete Staff", "消去 スタッフ"],
       ["buttonSpanScheduledShifts", " Scheduled Shifts", " 予定 シフト"],
       ["buttonSpanAssinmentList", " Assignment List", " 割り当てリスト"],
       ["buttonSpanReturn", " Return", "戻る"],

       ["accordionDivStaffInformation", " Staff Information", " スタッフ紹介"],
       ["accordionDivTransportationInformation", " Transportation Information", " 交通情報"],
       ["accordionDivResumeInformation", " Resume Information", " レジュメ情報"],
       ["accordionDivPayrollInformation", " Payroll Information", " ペイロール情報"],
       ["accordionDivSocialInsuranceInformation", " Social Insurance / Income Tax / Resident Tax Information", " 社会保険・所得税・住民税情報"],
       ["accordionDivLoginInformation", "Login Information ", " ログイン情報 "],
       ["accordionDivOtherInformation", " Other Information", "その他情報"],
       


    ["pageSpanName", "Name", "名前"],
    ["pageSpanHelpTextName", "Please put a space between the first and last name", "姓と名の間にスペースを入れてください"],
    ["pageSpanNameKatakana", "Name Katakana", "フリガナ"],
    ["pageSpanHelpTextNameKatakana", "Please put a space between the first and last name", "姓と名の間にスペースを入れてください"],
    ["pageSpanZipCode","Zip Code ","郵便番号"],
    ["btnAddressSearch","Address Search","住所検索"],
    ["pageSpanHelpZipCode","Please enter without hyphens","ハイフンなしで入力してください"],
    ["pageSpanPrefecture", "Prefectures", "都道府県"],
    ["pageSpanAddress", "Address", "住所"],
    ["pageSpanHelpAddress", "Please be sure to enter the apartment name and building name", "マンション名、ビル名を必ず入力してください"],
    ["pageSpanAddressKatakana", "Address Katakana", "アドレス カタカナ"],
    ["pageSpanDateofBirth", "Date of Birth", "生年月日"],
    ["pageSpanGender","Gender","性別"],
    ["pageSpanMobile", "Mobile", "携帯電話"],
    ["pageSpanHelpMobile", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageSpanHomeParent", "Home (parent's home)", "家（実家）"],
    ["pageSpanFax", "Fax", "ファックス"],
    ["pageSpanHelpFax", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageSpanAttributeclassification1", "Attribute classification 1", "属性の分類 1"],
    ["pageSpanAttributeclassification2", "Attribute classification 2", "属性の分類 2"],
    ["pageSpanLaborManagementExpirationDate", "Labor-management agreement expiration date", "労使協定の有効期限"],
    ["pageSpanAttribute", "Attribute", "属性"],
    ["pageSpanBelongs", "Belongs", "所属"],
    ["pageSpanDisClassification", "Dispatch classification", "派遣区分"],
    ["pageSpanGeneralDispatch", "General Dispatch", "一般派遣"],
    ["pageSpanBusinessContract", "Out Sourcing", "アウトソーシング"],
    ["pageSpanIntroductionDispatching", "Temp -to- Perm", "温度-に-パーマ"],
    ["pageSpanRecruitment", "Talent Introduction/Recruiting/Placement", "才能の紹介/募集/配置"],
    ["pageSpanOccuClassification", "Occupation Classification", "職業分類"],
    ["pageSpanOfficeSystem", "Office System", "オフィス系"],
    ["pageSpanSalesSystem", "Sales / Sales System", "営業・販売系 "],
    ["pageSpanITCreative", "IT / Creative", "IT・クリエイティブ系"],
    ["pageSpanMedicalWelfareSystem", "Medical/Welfare System", "医療・福祉系 "],
    ["pageSpanManufacturingBusiness", "Manufacturing Business", "製造業務系"],
    ["pageSpanProfessional", "Professional", "専門職系"],
    ["pageSpanOthers", "Others", "その他"],
    ["pageSpanDailySalaryUnitPrice", "Daily salary unit price", "日給単価"],
    ["pageSpanHelpDailySalaryUnitPrice", "This unit price will be referred to when the paid calculation method is set to regular wages.", "この単価は、有給の計算方法が通常の賃金に設定されている場合に参照されます。"],
    ["pageSpanHourlyWageUnitPrice", "Hourly Wage Unit Price", "時給単価"],
    ["pageSpanConflictDate", "Conflict Date (individual unit) list", "競合日（個別単位）リスト"],

    ["tableConflictDateTHNo", "No.", "番号"],
    ["tableConflictDateTHProjectTitle", "Project Title", "プロジェクト名"],
    ["tableConflictDateTHConflictDate", "Conflict date (individual unit)", "競合日（個別単位）"],


    ["pageSpanNearestStation", "Nearest Station", "最寄駅"],
    ["pageSpanTimeRequiredNearestStation", "Time required to reach the nearest station (minutes)", "最寄駅までの所要時間(分)"],
    ["pageSpanTransportationNearestStation", "Transportation to the nearest station", "最寄駅までの交通手段"],
    ["pageSpanBusUseSectionFrom", "Bus use section From", "バス利用区間From"],
    ["pageSpanHelpBusUseSectionFrom", "* Fill in only for bus users to the nearest station", "* 最寄り駅行きのバス利用者のみ記入"],
    ["pageSpanBusUseSectionTo", "Bus use section To", "バス利用区間To"],
    ["pageSpanHelpBusUseSectionTo", "* Fill in only for bus users to the nearest station", "* 最寄り駅行きのバス利用者のみ記入"],
    ["pageSpanRoundTripBusFare", "Round-trip bus fare (yen)", "バス往復料金(円)"],
    ["pageSpanHelpRoundTripBusFare", "* Fill in only for bus users to the nearest station", "* 最寄り駅行きのバス利用者のみ記入"],
    
    ["pageSpanEducationalBackground", "Educational Background", "学歴"],
    ["tableEducationalBackgroundTHYear", "Year", "年"],
    ["tableEducationalBackgroundTHMonth", "Month", "月"],
    ["tableEducationalBackgroundTHContent", "Contents", "コンテンツ"],
    ["pageSpanWorkHistory", "Work History", "職歴"],
    ["pageSpanLicenceQualification", "License Qualification", "ライセンス資格"],
    ["pageSpanHope", "Hope", "望み"],
    ["buttonOutputStaffResume", "Output Staff Resume", "出力スタッフの履歴書"],

    ["pageSpanSalaryPaymentMethod","Salary Payment Method", "給与支払方法"],
    ["selectOption", "Select Salary Payment Method", "給与支払い方法を選択します"],
    ["selectOptionPersonalDelivery", "Personal Delivery", "パーソナルデリバリー"],
    ["selectOptionTransfer", "Transfer", "転送"],
    ["pageSpanSalaryPaymentForm", "Salary Payment Form", "給与支払形態"],
    ["selectOptionSalary", "Select Salary Payment Form", "給与支払いフォームを選択します"],
    ["selectOptionSalaryPaymentFormDailyWeekly", "Daily / Weekly payment", "日払い/週払い"],
    ["selectOptionSalaryPaymentFormMonthly", "Monthly Payment", "月間支払額"],
    ["pageSpanSalaryClosingDate", "Salary Closing Date", "給与締日"],
    ["selectOptionSalaryClosingDate", "Select Salary Closing Date", "給与締切日を選択"],
    ["selectOptionSalaryClosingDateTheEndOfTheMonth", "The end of the month", "月の終わりに"],
    ["selectOptionSalaryClosingDate1Day", "1 day", "1日"],
    ["selectOptionSalaryClosingDate2Day", "2 days", "2日"],
    ["selectOptionSalaryClosingDate3Day", "3 days", "3日"],
    ["selectOptionSalaryClosingDate4Day", "4 days", "4日"],
    ["selectOptionSalaryClosingDate5Day", "5 days", "5日"],
    ["selectOptionSalaryClosingDate6Day", "6 days", "6日"],
    ["selectOptionSalaryClosingDate7Day", "7 days", "7日"],
    ["selectOptionSalaryClosingDate8Day", "8 days", "8日"],
    ["selectOptionSalaryClosingDate9Day", "9 days", "9日"],
    ["selectOptionSalaryClosingDate10Day", "10 days", "10日"],
    ["selectOptionSalaryClosingDate11Day", "11 days", "11日"],
    ["selectOptionSalaryClosingDate12Day", "12 days", "12日"],
    ["selectOptionSalaryClosingDate13Day", "13 days", "13日"],
    ["selectOptionSalaryClosingDate14Day", "14 days", "14日"],
    ["selectOptionSalaryClosingDate15Day", "15 days", "15日"],
    ["selectOptionSalaryClosingDate16Day", "16 days", "16日"],
    ["selectOptionSalaryClosingDate17Day", "17 days", "17日"],
    ["selectOptionSalaryClosingDate18Day", "18 days", "18日"],
    ["selectOptionSalaryClosingDate19Day", "19 days", "19日"],
    ["selectOptionSalaryClosingDate20Day", "20 days", "20日"],
    ["selectOptionSalaryClosingDate21Day", "21 days", "21日"],
    ["selectOptionSalaryClosingDate22Day", "22 days", "22日"],
    ["selectOptionSalaryClosingDate23Day", "23 days", "23日"],
    ["selectOptionSalaryClosingDate24Day", "24 days", "24日"],
    ["selectOptionSalaryClosingDate25Day", "25 days", "25日"],
    ["selectOptionSalaryClosingDate26Day", "26 days", "26日"],
    ["selectOptionSalaryClosingDate27Day", "27 days", "27日"],
    ["selectOptionSalaryClosingDate28Day", "28 days", "28日"],
    
    
    ["pageSpanHelpSalaryPaymentMethod", "If you choose to transfer, please enter your account information", "転送する場合は、アカウント情報を入力してください"],
    ["pageSpanPaidTarget", "Paid Target", "有給対象 "],
    ["selectOptionPaidTargetYes", "Yes", "はい。"],
    ["selectOptionPaidTargetNothing", "Nothing", "無"],
    ["pageSpanPaidStartDate", "Paid Start Date", "有給起算日"],
    ["pageSpanTransferFinancialInstitution", "Transfer Financial Institution Name", "金融機関名の譲渡"],
    ["pageSpanTransferBranchName", "Transfer Branch Name", "支店名の転送"],
    ["pageSpanHelpTransferBranchName", "For Japan Post Bank, enter the store name (example: 1988)", "ゆうちょ銀行の場合は、店舗名を入力してください（例：1988）"],
    ["pageSpanBankCode", "Bank Code", "金融機関コード"],
    ["pageSpanHelpBankCode", "Not entered for Japan Post Bank", "ゆうちょ銀行に入金していません"],
    ["pageSpanBranchCode", "Branch Code", "支店コード"],
    ["pageSpanHelpBranchCode", "For Japan Post Bank, enter the account code (example: 12345)", "ゆうちょ銀行の場合は、口座コードを入力してください（例：12345）"],
    ["pageSpanAccountType", "Account Type", "口座の種類"],
    ["selectOptionAccountTypeUsually", "Usually", "通常"],
    ["selectOptionAccountTypeCurrent", "Current", "現在"],
    ["selectOptionAccountTypeSavings", "Savings", "貯金"],
    ["selectOptionAccountTypeOthers", "Others", "その他"],
    ["pageSpanAccountNumber", "Account Number", "口座番号"],
    ["pageSpanAccountName", "Account Name", "アカウント名"],
    ["", "", ""],
    ["", "", ""],


    ["accordionDivSkillSheetInformation", "Skill Sheet Information", "スキルシート情報"],
    ["pageSpanNameInitials", "Name (initials only)", "名前（イニシャルのみ）"],
    ["pageSpanCurrentAddress", "Current Address", "現住所"],
    ["pageSpanHelpCurrentAddress", "Please enter the information of the address you want to display after the prefecture", "都道府県後に表示したい住所の情報を入力してください"],
    ["pageDivWorkHistory", "Work history (for skill sheet)", "職歴（スキルシート用"],
    ["pageSpanHelpWorkHistory", "Describe the career history since the last academic background. Listed by industry / industry with the company name hidden, such as 'Trading company D', 'Major advertising agency', and 'Service industry'.", "最後の学歴からの経歴を説明してください。 「商号D」、「大手広告代理店」、「サービス業」など、会社名を非表示にして業界・業界別に掲載。"],
    ["tableSkillSheetInformationTHYear", "Year", "年"],
    ["tableSkillSheetInformationTHMonth", "Month", "月"],
    ["tableSkillSheetInformationTHContent", "Contents", "コンテンツ"],
    ["pageSpanRemarks", "Remarks", "備考"],
    ["staffSkillRemark", "If you have any particular requests regarding treatment, occupation, working hours, place of work, etc., enter them.", "治療、職業、勤務時間、勤務地など、特にご要望がございましたら、ご記入ください."],
    ["buttonOutputStaffSkillSheet", "Output Staff Skill Sheet", "出力スタッフスキルシート"],
    ["", "", ""],



    ["pageSpanMyNumber", "My Number", "私の番号"],
    ["pageSocialInsuranceCoverage", "Social Insurance Coverage", "社会保険の適用範囲"],
    ["selectOptionSocialInsuranceCoverage", "Select Social Insurance Coverage", "社会保険の補償範囲を選択"],
    ["selectOptionSocialInsuranceCoverageNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionSocialInsuranceCoverageSubscribed", "Subscribed", "申し込み"],
    ["pageSpanOpensocialinsurance", "Open social insurance / income tax / resident tax information", "オープンな社会保険/所得税/居住者税情報"],
    ["pageSpanHealthInsuranceCoverage", "Health insurance coverage", "健康保険加入状況 "],
    ["selectOptionHealthInsuranceCoverage", "Select Health insurance coverage", "健康保険の適用範囲を選択します"],
    ["selectOptionHealthInsuranceCoverageNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionHealthInsuranceCoverageSubscribed", "Subscribed", "申し込み"],
    ["selectOptionHealthInsuranceGrade", "Select Health insurance grade", "健康保険グレードを選択"],
    ["selectOptionWelfareHealthInsuranceCoverage", "Select Welfare pension insurance participation status", "厚生年金保険加入状況を選択する"],
    ["selectOptionWelfareHealthInsuranceCoverageNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionWelfareHealthInsuranceCoverageSubscribed", "Subscribed", "申し込み"],
    ["selectOptionEmploymentInsuranceCoverageNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionEmploymentInsuranceCoverageSubscribed", "Subscribed", "申し込み"],
    ["pageSpanHealthInsuranceGrade", "Health insurance grade", "健康保険グレード"],
    ["selectOptionHealthInsuranceGrade", "Select Health insurance grade", "健康保険グレードを選択"],
    ["selectOptionHealthInsuranceGradeNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionHealthInsuranceGradeGrade1", "Grade 1 to 63,000", "グレード1～63,000"],
    ["selectOptionHealthInsuranceGradeGrade2", "2nd Grade 63,000 to 73,000", "2年生 63,000～73,000"],
    ["selectOptionHealthInsuranceGradeGrade3", "3rd Grade 73,000 to 83,000", "3年生 73,000～83,000"],
    ["selectOptionHealthInsuranceGradeGrade4", "4th Grade 83,000 to 93,000", "4年生 83,000～93,000"],
    ["selectOptionHealthInsuranceGradeGrade5", "5th Grade 93,000 to 101,000", "5年生 93,000～101,000"],
    ["selectOptionHealthInsuranceGradeGrade6", "6th Grade 101,000 to 107,000", "6年生 101,000～107,000"],
    ["selectOptionHealthInsuranceGradeGrade7", "7th Grade 107,000 to 114,000", "7年生 107,000～114,000"],
    ["selectOptionHealthInsuranceGradeGrade8", "8th Grade 114,000 to 122,000", "8年生 114,000～122,000"],
    ["selectOptionHealthInsuranceGradeGrade9", "9th Grade 122,000 to 130,000", "9年生 122,000～130,000"],
    ["selectOptionHealthInsuranceGradeGrade10", "10th Grade 130,000 to 138,000", "10年生 130,000～138,000"],
    ["selectOptionHealthInsuranceGradeGrade11", "11th Grade 138,000 to 146,000", "11年生 138,000～146,000"],
    ["selectOptionHealthInsuranceGradeGrade12", "12th Grade 146,000 to 155,000", "12年生 146,000～155,000"],
    ["selectOptionHealthInsuranceGradeGrade13", "13th Grade 155,000 to 165,000", "13年生 155,000～165,000"],
    ["selectOptionHealthInsuranceGradeGrade14", "14th Grade 165,000 to 175,000", "14年生 165,000～175,000"],
    ["selectOptionHealthInsuranceGradeGrade15", "15th Grade 175,000 to 185,000", "15年生 175,000～185,000"],
    ["selectOptionHealthInsuranceGradeGrade16", "16th Grade 185,000 to 195,000", "16年生 185,000～195,000"],
    ["selectOptionHealthInsuranceGradeGrade17", "17th Grade 195,000 to 210,000", "17年生 195,000～210,000"],
    ["selectOptionHealthInsuranceGradeGrade18", "18th Grade 210,000 to 230,000", "18年生 210,000～230,000"],
    ["selectOptionHealthInsuranceGradeGrade19", "19th Grade 230,000 to 250,000", "19年生 230,000～250,000"],
    ["selectOptionHealthInsuranceGradeGrade20", "20th Grade 250,000 to 270,000", "20年生 250,000～270,000"],
    ["selectOptionHealthInsuranceGradeGrade21", "21st Grade 270,000 to 290,000", "21年生 270,000～290,000"],
    ["selectOptionHealthInsuranceGradeGrade22", "22nd Grade 290,000 to 310,000", "22年生 290,000～310,000"],
    ["selectOptionHealthInsuranceGradeGrade23", "23rd Grade 310,000 to 330,000", "23年生 310,000～330,000"],
    ["selectOptionHealthInsuranceGradeGrade24", "24th Grade 330,000 to 350,000", "24年生 330,000～350,000"],
    ["selectOptionHealthInsuranceGradeGrade25", "25th Grade 350,000 to 370,000", "25年生 350,000～370,000"],
    ["selectOptionHealthInsuranceGradeGrade26", "26th Grade 370,000 to 395,000", "26年生 370,000～395,000"],
    ["selectOptionHealthInsuranceGradeGrade27", "27th Grade 395,000 to 425,000", "27年生 395,000～425,000"],
    ["selectOptionHealthInsuranceGradeGrade28", "28th Grade 425,000 to 455,000", "28年生 425,000～455,000"],
    ["selectOptionHealthInsuranceGradeGrade29", "29th Grade 455,000 to 485,000", "29年生 455,000～485,000"],
    ["selectOptionHealthInsuranceGradeGrade30", "30th Grade 485,000 to 515,000", "30年生 485,000～515,000"],
    ["selectOptionHealthInsuranceGradeGrade31", "31st Grade 515,000 to 545,000", "31年生 515,000～545,000"],
    ["selectOptionHealthInsuranceGradeGrade32", "32nd Grade 545,000 to 575,000", "32年生 545,000～575,000"],
    ["selectOptionHealthInsuranceGradeGrade33", "33rd Grade 575,000 to 605,000", "33年生 575,000～605,000"],
    ["selectOptionHealthInsuranceGradeGrade34", "34th Grade 605,000 to 635,000", "34年生 605,000～635,000"],
    ["selectOptionHealthInsuranceGradeGrade35", "35th Grade 635,000 to 665,000", "35年生 635,000～665,000"],
    ["selectOptionHealthInsuranceGradeGrade36", "36th Grade 665,000 to 695,000", "36年生 665,000～695,000"],
    ["selectOptionHealthInsuranceGradeGrade37", "37th Grade 695,000 to 730,000", "37年生 695,000～730,000"],
    ["selectOptionHealthInsuranceGradeGrade38", "38th Grade 730,000 to 770,000", "38年生 730,000～770,000"],
    ["selectOptionHealthInsuranceGradeGrade39", "39rd Grade 770,000 to 810,000", "39年生 770,000～83,000"],
    ["selectOptionHealthInsuranceGradeGrade40", "40th Grade 810,000 to 855,000", "40年生 73,000～855,000"],
    ["selectOptionHealthInsuranceGradeGrade41", "41st Grade 855,000 to 905,000", "41年生 855,000～905,000"],
    ["selectOptionHealthInsuranceGradeGrade42", "42nd Grade 905,000 to 965,000", "42年生 905,000～965,000"],
    ["selectOptionHealthInsuranceGradeGrade43", "43rd Grade 965,000 to 1,005,000", "43年生 965,000～1,005,000"],
    ["selectOptionHealthInsuranceGradeGrade44", "44th Grade 1,005,000 to 1,055,000", "44年生 1,005,000～1,055,000"],
    ["selectOptionHealthInsuranceGradeGrade45", "45th Grade 1,055,000 to 1,115,000", "45年生 1,055,000～1,115,000"],
    ["selectOptionHealthInsuranceGradeGrade46", "46th Grade 1,115,000 to 1,175,000", "46年生 1,115,000～1,175,000"],
    ["selectOptionHealthInsuranceGradeGrade47", "47th Grade 1,175,000 to 1,235,000", "47年生 1,175,000～1,235,000"],
    ["selectOptionHealthInsuranceGradeGrade48", "48th Grade 1,235,000 to 1,295,000", "48年生 1,235,000～1,295,000"],
    ["selectOptionHealthInsuranceGradeGrade49", "49th Grade 1,295,000 to 1,355,000", "49年生 1,295,000〜1,355,000"],
    ["selectOptionHealthInsuranceGradeGrade50", "50th Grade 1,355,000 ~ ", "50年生 1,355,000〜"],
    
    ["selectOptionWelfarePensionInsuranceGrade2", "Grade 1 - 93,000", "グレード1-93,000"],
    ["selectOptionWelfarePensionInsuranceGrade3", "2nd Grade 93,000 - 101,000", "2 年生 93,000 - 101,000"],
    ["selectOptionWelfarePensionInsuranceGrade4", "3rd Grade 101,000 - 107,000", "3 年生 101,000 - 107,000"],
    ["selectOptionWelfarePensionInsuranceGrade5", "4th Grade 107,000 - 114,000", "4 年生 107,000 - 114,000"],
    ["selectOptionWelfarePensionInsuranceGrade6", "5th Grade 114,000 - 122,000", "5 年生 114,000 - 122,000"],
    ["selectOptionWelfarePensionInsuranceGrade7", "6th Grade 122,000 - 130,000", "6 年生 122,000 - 130,000"],
    ["selectOptionWelfarePensionInsuranceGrade8", "7th Grade 130,000 - 138,000", "7 年生 130,000 - 138,000"],
    ["selectOptionWelfarePensionInsuranceGrade9", "8th Grade 138,000 - 146,000", "8 年生 138,000 - 146,000"],
    ["selectOptionWelfarePensionInsuranceGrade10", "9th Grade 146,000 - 155,000", "9 年生 146,000 - 155,000"],
    ["selectOptionWelfarePensionInsuranceGrade11", "10th Grade 155,000 - 165,000", "10 年生 155,000 - 165,000"],
    ["selectOptionWelfarePensionInsuranceGrade12", "11th Grade 165,000 - 175,000", "11 年生 165,000 - 175,000"],
    ["selectOptionWelfarePensionInsuranceGrade13", "12th Grade 175,000 - 185,000", "12 年生 175,000 - 185,000"],
    ["selectOptionWelfarePensionInsuranceGrade14", "13th Grade 185,000 - 195,000", "13 年生 185,000 - 195,000"],
    ["selectOptionWelfarePensionInsuranceGrade15", "14th Grade 195,000 - 210,000", "14 年生 195,000 - 210,000"],
    ["selectOptionWelfarePensionInsuranceGrade16", "15th Grade 210,000 - 230,000", "15 年生 210,000 - 230,000"],
    ["selectOptionWelfarePensionInsuranceGrade17", "16th Grade 230,000 - 250,000", "16 年生 230,000 - 250,000"],
    ["selectOptionWelfarePensionInsuranceGrade18", "17th Grade 250,000 - 270,000", "17 年生 250,000 - 270,000"],
    ["selectOptionWelfarePensionInsuranceGrade19", "18th Grade 270,000 - 290,000", "18 年生 270,000 - 290,000"],
    ["selectOptionWelfarePensionInsuranceGrade20", "19th Grade 290,000 - 310,000", "19 年生 290,000 - 310,000"],
    ["selectOptionWelfarePensionInsuranceGrade21", "20th Grade 310,000 - 330,000", "20 年生 310,000 - 330,000"],
    ["selectOptionWelfarePensionInsuranceGrade22", "21st Grade 330,000 - 350,000", "21 年生 330,000 - 350,000"],
    ["selectOptionWelfarePensionInsuranceGrade23", "22nd Grade 350,000 - 370,000", "22 年生 350,000 - 370,000"],
    ["selectOptionWelfarePensionInsuranceGrade24", "23rd Grade 370,000 - 395,000", "23 年生 370,000 - 395,000"],
    ["selectOptionWelfarePensionInsuranceGrade25", "24th Grade 395,000 - 425,000", "24 年生 395,000 - 425,000"],
    ["selectOptionWelfarePensionInsuranceGrade26", "25th Grade 425,000 - 455,000", "25 年生 425,000 - 455,000"],
    ["selectOptionWelfarePensionInsuranceGrade27", "26th Grade 455,000 - 485,000", "26 年生 455,000 - 485,000"],
    ["selectOptionWelfarePensionInsuranceGrade28", "27th Grade 485,000 - 515,000", "27 年生 485,000 - 515,000"],
    ["selectOptionWelfarePensionInsuranceGrade29", "28th Grade 515,000 - 545,000", "28 年生 515,000 - 545,000"],
    ["selectOptionWelfarePensionInsuranceGrade30", "29th Grade 545,000 - 575,000", "29 年生 545,000 - 575,000"],
    ["selectOptionWelfarePensionInsuranceGrade31", "30th Grade 575,000 - 605,000", "30 年生 575,000 - 605,000"],
    ["selectOptionWelfarePensionInsuranceGrade32", "31st Grade 605,000 ~", "31年生605,000〜"],
    
    
    
    
    ["pageSpanWelfarePensionInsurance", "Welfare pension insurance participation status", "厚生年金保険加入状況 "],
    ["pageSpanWelfarePensionInsuranceGrade", "Welfare pension insurance grade", "厚生年金保険等級"],
    ["pageSpanLongTermCareInsuranceParticipation", "Long-term care insurance participation status", "介護保険加入状況"],
    ["pageSpanEmploymentInsuranceCoverage", "Employment insurance coverage", "雇用保険加入状況"],
    ["pageSpanHelpEmploymentInsuranceCoverage1", " Condition (1) Scheduled to work 20 hours or more per week, Condition (2) Scheduled to be employed for 31 days or more", "条件（1）週20時間以上の就業予定、条件（2）31日以上の就業予定"],
    ["pageSpanHelpEmploymentInsuranceCoverage2", " *However, please note that students are not eligible in principle", "条件①1週間の労働時間が20時間以上の予定、条件②31日以上雇用される予定※ただし、学生は原則対象外となりますので、ご注意ください。"],
    ["pageSpanIncomeTaxTaxpayerClassification", "Income tax taxpayer classification", "所得税納税者の分類"],
    ["pageSpanHelpIncomeTaxTaxpayerClassification", " Please select the dispatched staff who have submitted the declaration of dependent deductions for salaried workers \,the dispatched staff who have not submitted the declaration of dependent deductions for salaried workers \,and the dispatched staff who are day laborers or part-time workers." , "サラリーマンの扶養控除申告書を提出した派遣職員、サラリーマンの扶養控除申告書を提出していない派遣職員、日雇い労働者またはパートタイム労働者の派遣職員を選択してください。"],
    ["pageSpanNumberofDependents", "Number of dependents", "扶養親族人数 "],
    ["pageSpanHelpNumberOfDependents", "Please enter the number of dependents directly. Please note that the number of dependent relatives may not match the actual number because the calculation method of the dependent deduction amount differs depending on the disability classification of the dependent relatives.", "扶養親族人数を直接入力してください。"],
    ["pageSpanDependents", "Dependents", "扶養親族"],
    ["tableConflictDateTHFamilyName", "family name", "氏名"],
    ["tableConflictDateTHNameKatakana", "Name katakana", "名前カタカナ"],
    ["tableConflictDateTHBirthday", "Birthday", "たんじょうび"],
    ["tableConflictDateTHGender", "Gender", "性別"],
    ["tableConflictDateTHRelationship", "Relationship", "続柄"],
    ["tableConflictDateTHClassification", "Classification", "区分"],
    ["tableConflictDateTHLivingTogether", "Living Together", "同居状況 "],
    ["tableConflictDateTHHandicapped", "Handicapped", "障害者"],
    ["tableConflictDateTHDuplicate", "Duplicate", "複製"],
    ["btnSpanDuplicateInTheBottomLine1", "Duplicate In The Bottom Line", "結論として重複"],
    ["btnSpanDuplicateInTheBottomLine2", "Duplicate In The Bottom Line", "結論として重複"],
    ["btnSpanDuplicateInTheBottomLine3", "Duplicate In The Bottom Line", "結論として重複"],
    ["btnSpanDuplicateInTheBottomLine4", "Duplicate In The Bottom Line", "結論として重複"],
    ["btnSpanDuplicateInTheBottomLine5", "Duplicate In The Bottom Line", "結論として重複"],
    ["pageSpanResidentTaxClassification", "Resident tax classification", "住民税区分"],
    ["pageSpanNormalCollection", "Normal Collection", "通常のコレクション"],
    ["pageSpanSpecialCollection", "Special Collection", "スペシャルコレクション"],


    ["pageSpanEmail", "Email address", "電子メールアドレス"],
    ["pageSpanHelpEmail1", "* It will be the ID to log in to the system", "*システムにログインするためのIDになります"],
    ["pageSpanHelpEmail2", "* It will be the address to receive the business contact email", "システムにログインするIDになります ※業務連絡メールを受け取るアドレスになります"],
    ["pageSpanNewPassword", "NewPassword", "新しいパスワード"],
    ["pageSpanHelpNewPassword", "* 6 characters or more, half-width alphanumeric characters", "* ※6文字以上、半角英数字"],
    ["pageSpanNewPasswordConfirm", "For new password confirmation", "新しいパスワードの確認用"],
    ["pageSpanEmailAddressConfirm", "Email Address Confirmation", "メールアドレス確認用"],
    ["pageSpanRegistrationDivision", "Registration Division", "登録区分"],
    ["pageSpanMainRegistration", "Main Registration", "主な登録"],
    ["pageSpanTemporaryRegistration", "Temporary  Registration", "仮登録"],
    ["pageSpanLineRegistration", "LINE Registration", "LINE登録"],
    ["pageSpanUnregistered", "Unregistered", "未登録"],

    ["pageSpanStaffCode", "Staff Code", "スタッフコード"],
    ["pageSpanFacePhoto", "Face Photo", "顔写真"],
    ["pageSpanHelpFacePhoto" , "* This is a face photo to be displayed in the list and resume.", "一覧や履歴書に表示する顔写真です"],
    ["pageSpanPreview", "Face Photo Preview", "プレビュー"],
    ["pageSpanEmergencyContactName", "Emergency Contact Name", "緊急連絡先氏名"],
    ["pageSpanHelpEmergencyContactName", "Please put a space between the first and last name", "姓と名の間にスペースを入れてください"],
    ["pageSpanEmergencyContactNameKatakana", "Emergency Contact Name Katakana", "緊急連絡先氏名カナ"],
    ["pageSpanHelpEmergencyContactNameKatakana", "Please put a space between the first and last name", "姓と名の間にスペースを入れてください"],
    ["pageSpanPostalCode", "Postal Code", "郵便番号"],
    ["buttonSpanAddressSearch", "Address Search", "住所検索"],
    ["buttonSpanHelpAddressSearch", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageSpanPrefectures", "Prefectures", "都道府県"],
    
    ["pageOption1Prefecture", "Hokkaido", "北海道"],
    ["pageOption2Prefecture", "Aomori", "青森"],
    ["pageOption3Prefecture", "Iwate", "岩手"],
    ["pageOption4Prefecture", "Miyagi", "宮城"],
    ["pageOption5Prefecture", "Akita", "秋田"],
    ["pageOption6Prefecture", "Yamagata", "山形"],
    ["pageOption7Prefecture", "Fukushima", "福島"],
    ["pageOption8Prefecture", "Ibaraki", "茨城"],
    ["pageOption9Prefecture", "Tochigi", "栃木"],
    ["pageOption10Prefecture", "Gunma", "群馬"],
    ["pageOption11Prefecture", "Saitama", "さいたま"],
    ["pageOption12Prefecture", "Chiba", "千葉"],
    ["pageOption13Prefecture", "Tokyo", "東京"],
    ["pageOption14Prefecture", "Kanagawa", "神奈川"],
    ["pageOption15Prefecture", "Niigata", "新潟"],
    ["pageOption16Prefecture", "Toyama", "富山"],
    ["pageOption17Prefecture", "Ishikawa", "石川"],
    ["pageOption18Prefecture", "Fukui", "福井"],
    ["pageOption19Prefecture", "Yamanashi", "山梨"],
    ["pageOption20Prefecture", "Nagano", "長野"], // changed
    ["pageOption21Prefecture", "Gifu", "岐阜"], // changed
    ["pageOption22Prefecture", "Shizuoka", "静岡"],
    ["pageOption23Prefecture", "Aichi", "愛知"],
    ["pageOption24Prefecture", "Mie", "私の"],
    ["pageOption25Prefecture", "Shiga", "滋賀"],
    ["pageOption26Prefecture", "Kyoto", "京都"],
    ["pageOption27Prefecture", "Osaka", "大阪"],
    ["pageOption28Prefecture", "Hyogo", "兵庫"],
    ["pageOption29Prefecture", "Nara", "奈良"],
    ["pageOption30Prefecture", "Wakayama", "和歌山"],
    ["pageOption31Prefecture", "Tottori", "鳥取"],
    ["pageOption32Prefecture", "Shimane", "島根"],
    ["pageOption33Prefecture", "Okayama", "岡山"],
    ["pageOption34Prefecture", "Hiroshima", "広島"],
    ["pageOption35Prefecture", "Yamaguchi", "山口"],
    ["pageOption36Prefecture", "Tokushima", "徳島"],
    ["pageOption37Prefecture", "Kagawa", "香川"],
    ["pageOption38Prefecture", "Ehime", "愛媛"],
    ["pageOption39Prefecture", "Kochi", "高知"],
    ["pageOption40Prefecture", "Fukuoka", "福岡"],
    ["pageOption41Prefecture", "Saga", "佐賀"],
    ["pageOption42Prefecture", "Nagasaki", "長崎"],//changed
    ["pageOption43Prefecture", "Kumamoto", "熊本"],
    ["pageOption44Prefecture", "Oita", "大分"], // changed
    ["pageOption45Prefecture", "Miyazaki", "宮崎"],
    ["pageOption46Prefecture", "Kagoshima", "鹿児島"],
    ["pageOption47Prefecture", "Okinawa", "沖縄"],
   
   //edit imali 
   //STAFF INFO 
    ["staffGender0", "Select Gender", "性別を選択"],
    ["staffGender1", "Male", "男性"],
    ["staffGender2", "Female", "女性"],
    ["pageSpanHelpMobile", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageSpanHelpHome", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageOption0AttributeClassification1", "Select Attribute classification 1", "属性分類を選択します 1"],
    ["pageOption1AttributeClassification1", "In house Company Affiliated Staff", "社内カンパニー関連スタッフ"],
    ["pageOption2AttributeClassification1", "Out Sourcing", "アウトソーシング"],
    ["pageOption0AttributeClassification2", "Select Attribute classification 2", "属性分類を選択します 2"],
    ["pageOption1AttributeClassification2", "Fixed-term employment worker", "有期雇用労働者"],
    ["pageOption2AttributeClassification2", "Fixed-term employment workers(Dispatched Workers Subject to the agreement", "有期雇用労働者（派遣労働者 協定対象者"],
    ["pageOption3AttributeClassification2", "Permanent Worker", "正社員"],
    ["pageOption4AttributeClassification2", "Permanent Employment Workers(Dispatched Workers Subject to the agreement)", "常用雇用労働者（派遣労働者 協定対象者)"],
    ["pageOption0Attribute", "Select Attribute", "アトリビュートの選択"],
    
    //RESUME INFO
    ["tableEducationalBackgroundTHDateFrom", "Date From", "からの日付"],
    ["tableEducationalBackgroundTHDateTo", "Date To", "に日付を入れます。"],
    ["tableEducationalBackgroundTHInstitute", "Institute / School", "研究所・学校"],
    ["tableEducationalBackgroundTHQualificationType", "Qualification Type", "資格の種類"],
    ["tableWorkHistoryTHYear", "Date From", "からの日付"],
    ["tableWorkHistoryTHMonth", "Date To", "に日付を入れます。"],
    ["tableWorkHistoryTHDesignation", "Designation", "呼称"],
    ["tableWorkHistoryTHCompany", "Company", "会社概要"],
    ["tableWorkHistoryTHContent", "Experience", "エクスペリエンス"],
    ["tableLicenseTHDateFrom", "Date From", "からの日付"],
    ["tableLicenseTHDateTo", "Date To", "に日付を入れます。"],
    ["tableLicenseTHLicenseQualification", "License Qualification", "ライセンス資格"],
    ["tableLicenseTHLicenseNumber", "License Number", "ライセンス番号"],
    ["tableLicenseTHLiContents", "License Operating Item", "ライセンス運用項目"],
    ["staffHope", "If you have any particular requests regarding treatment, occupation, working hours, place of work, etc., enter them.", "治療、職業、勤務時間、勤務地など、特にご要望がございましたら、ご記入ください。"],
    
    //PAYROLL INFO
    ["selectOptionSalaryPaymentMethod0", "Select Salary Payment Method", "給与支払方法の選択"],
    ["selectOptionSalaryPaymentForm0", "Select Salary Payment Form", "給与支払方法の選択"],
    ["selectOptionSalaryClosingDate0", "Select Salary Closing Date", "選択してください 給与 締め日"],
    ["selectOptionPaidTarget", "Select Paid Target", "選択した有料ターゲット"],
    ["selectOptionAccountType", "Select Account Type", "アカウントタイプの選択"],
    
    //Social Info
    ["insuranceTaxinformation", "insurance / income tax / resident tax information", "保険・所得税・住民税について"],
    ["selectOptionLongTermInsuranceStatus", "Select Long-term care insurance participation status", "介護保険加入状況を選択する"],
    ["selectOptionLongTermInsuranceStatus2", "Subscribed", "申し込み"],
    ["selectOptionLongTermInsuranceStatus1", "Not Subscribed", "未加入"],
    ["selectOptionLongTermInsuranceStatus2", "Subscribed", "申し込み"],
    ["selectIncomeTaxTaxpayer", "Select Income tax taxpayer classification", "所得税納税者分類を選択します"],
    ["selectOptionInstep", "Instep", "甲"],
    ["selectOptionB", "B", "て"],
    ["selectOptionHinoe", "Hinoe", "柄"],
    ["selectOptionWelfarePensionInsuranceGrade", "Select Welfare pension insurance grade", "厚生年金保険等級を選択する"],
    ["selectOptionWelfarePensionInsuranceGradeNotSubscribed", "Not Subscribed", "未加入"],
    ["selectOptionEmploymentInsuranceCoverage", "Select Employment insurance coverage", "雇用保険の補償範囲を選択します"],
    ["SelectStaffResidentTaxClassification", "Select Resident tax classification", "居住者税分類を選択します"],
    ["addLicenseRow", "Add Row", "行を追加する"],
    ["addEducationalRow", "Add Row", "行を追加する"],
    ["addWorkRow", "Add Row", "行を追加する"],
    ["addSkillSheetRow", "Add Row", "行を追加する"],
    ["addDependentRow", "Add Row", "行を追加する"],
    ["addDependentRow", "Add Row", "行を追加する"],
    ["dependentGenderMale", "Male", "男"],
    ["dependentGenderFemale", "Female", "女性"],
    ["dependentRelationshipWife", "Wife", "妻"],
    ["dependentRelationshipChild", "Child", "子供"],
    ["dependentRelationshipFather", "Father", "父親"],
    ["dependentRelationshipMother", "Mother", "母親"],
    ["dependentRelationshipOlderBrother", "Older Brother", "兄さん"],
    ["dependentRelationshipYoungerBrother", "Younger Brother", "弟"],
    ["dependentRelationshipSister", "Sister", "妹"],
    ["dependentClassificationGeneralDependents", "General Dependents", "一般的な扶養家族"],
    ["dependentClassificationSpecificDependents", "Specific Dependents", "特定の扶養家族"],
    ["dependentClassificationDependentsOfElderly", "Dependents Of Elderly", "高齢者の扶養家族"],
    ["dependentLivingTogether", "Living Together", "同居"],
    ["dependentSeparated", "Separated", "分離"],
    ["dependentSeparatedOverseas", "Separated overseas", "海外に分離"],
    ["dependentGeneralDisabled", "General disabled", "一般障害者"],
    ["dependentSpeciallyDisabled", "Specially disabled", "特別障害者"],
    ["dependentHealthy", "Healthy", "元気"],
    
    ["pageSpanConflictDateList", "Conflict date individual unit) list", "紛争発生日（個別ユニット）リスト"],
 	["accordionDivCredentialsInformation", " Credentials Information", "クレデンシャル情報"],
 	["pageSpanLicenceQualifi", "License Qualification", "ライセンス資格"],
 	["#tableWorkHistoryTHYear", "Date From", "からの日付"],
    ["#tableWorkHistoryTHMonth", "Date To", "に日付を入れます。"],
    ["#tableWorkHistoryTHDesignation", "Designation", "呼称"],
    ["#tableWorkHistoryTHCompany", "Company", "会社概要"],
    ["#tableWorkHistoryTHContent", "Experience", "エクスペリエンス"],
    
        
    ["#pageOption1Prefecture", "Hokkaido", "北海道"],
    ["#pageOption2Prefecture", "Aomori", "青森"],
    ["#pageOption3Prefecture", "Iwate", "岩手"],
    ["#pageOption4Prefecture", "Miyagi", "宮城"],
    ["#pageOption5Prefecture", "Akita", "秋田"],
    ["#pageOption6Prefecture", "Yamagata", "山形"],
    ["#pageOption7Prefecture", "Fukushima", "福島"],
    ["#pageOption8Prefecture", "Ibaraki", "茨城"],
    ["#pageOption9Prefecture", "Tochigi", "栃木"],
    ["#pageOption10Prefecture", "Gunma", "群馬"],
    ["#pageOption11Prefecture", "Saitama", "さいたま"],
    ["#pageOption12Prefecture", "Chiba", "千葉"],
    ["#pageOption13Prefecture", "Tokyo", "東京"],
    ["#pageOption14Prefecture", "Kanagawa", "神奈川"],
    ["#pageOption15Prefecture", "Niigata", "新潟"],
    ["#pageOption16Prefecture", "Toyama", "富山"],
    ["#pageOption17Prefecture", "Ishikawa", "石川"],
    ["#pageOption18Prefecture", "Fukui", "福井"],
    ["#pageOption19Prefecture", "Yamanashi", "山梨"],
    ["#pageOption20Prefecture", "Nagano", "長野"], // changed
    ["#pageOption21Prefecture", "Gifu", "岐阜"], // changed
    ["#pageOption22Prefecture", "Shizuoka", "静岡"],
    ["#pageOption23Prefecture", "Aichi", "愛知"],
    ["#pageOption24Prefecture", "Mie", "私の"],
    ["#pageOption25Prefecture", "Shiga", "滋賀"],
    ["#pageOption26Prefecture", "Kyoto", "京都"],
    ["#pageOption27Prefecture", "Osaka", "大阪"],
    ["#pageOption28Prefecture", "Hyogo", "兵庫"],
    ["#pageOption29Prefecture", "Nara", "奈良"],
    ["#pageOption30Prefecture", "Wakayama", "和歌山"],
    ["#pageOption31Prefecture", "Tottori", "鳥取"],
    ["#pageOption32Prefecture", "Shimane", "島根"],
    ["#pageOption33Prefecture", "Okayama", "岡山"],
    ["#pageOption34Prefecture", "Hiroshima", "広島"],
    ["#pageOption35Prefecture", "Yamaguchi", "山口"],
    ["#pageOption36Prefecture", "Tokushima", "徳島"],
    ["#pageOption37Prefecture", "Kagawa", "香川"],
    ["#pageOption38Prefecture", "Ehime", "愛媛"],
    ["#pageOption39Prefecture", "Kochi", "高知"],
    ["#pageOption40Prefecture", "Fukuoka", "福岡"],
    ["#pageOption41Prefecture", "Saga", "佐賀"],
    ["#pageOption42Prefecture", "Nagasaki", "長崎"],//changed
    ["#pageOption43Prefecture", "Kumamoto", "熊本"],
    ["#pageOption44Prefecture", "Oita", "大分"], // changed
    ["#pageOption45Prefecture", "Miyazaki", "宮崎"],
    ["#pageOption46Prefecture", "Kagoshima", "鹿児島"],
    ["#pageOption47Prefecture", "Okinawa", "沖縄"],
    ["pageOption0Prefecture", "Select Prefecture", "県を選択"],
    ["#pageOption0Prefecture", "Select Prefecture", "県を選択"],
    
    ["pageSpanOtheAddress", "Address", "住所"],
    ["staffEmergencyAddress", "Example: 1-11-11 Shibuya, Shibuya-ku ○○○○ Building 1F","例 : 1-11-11 渋谷区渋谷 ○○○○ ビル1F"],
    ["pageSpanOtherHelpAddress", "Please be sure to enter the apartment name and building name", "必ずアパート名や建物名は入力してください"],
    ["pageSpanEmergencyContactPhoneNumber", "Emergency Contact Phone Number", "緊急連絡先電話番号"],
    ["pageSpanHelpEmergencyContactPhoneNumber", "Please enter without hyphens", "ハイフンなしで入力してください"],
    ["pageSpanRelationship", "Relationship", "続柄"], 
    ["pageSpanDateofJoiningTheCompany", "Date of Joining The Company", "入社日"],
    ["pageSpanStaffStaff", "In Charge Staff", "担当スタッフ"],
    ["pageSpanExperience", "Experience", "職務履歴"],
    ["staffExperience", "Example: Have sales experience.  Experienced as a leader in restaurants.  * You can search for input contents by free word from the search item 'Experience' in the staff list.", "例：営業経験がある。レストランのリーダーとしての経験。 ※スタッフ一覧の検索項目「経験」からフリーワードで入力内容を検索できます。"],
    ["pageSpanStaffMemo", "Staff Memo", "スタッフメモ"],
    ["StaffMemo", "Example: On February 1, a complaint occurred without following the business instructions of the dispatched company.  Be careful about the next assignment.", "例：2月1日、派遣会社の業務指示に従わずに苦情が発生した。次の割り当てに注意してください。"],
    ["staffMemo", "Example: On February 1, a complaint occurred without following the business instructions of the dispatched company.  Be careful about the next assignment.", "例：2月1日、派遣会社の業務指示に従わずに苦情が発生した。次の割り当てに注意してください。"],
    ["pageSpanStaffInformationUpdateHistory", "Staff Information Update History", "スタッフ情報更新履歴"],
    ["staffInformationUpdate", "The update date / update staff is automatically registered, but it can also be used as an internal memo.", "更新日・更新スタッフは自動登録されますが、内部メモとしても使用できます。"],
    ["pageSpanValidClassification", "Valid Classification", "*有効区分"],
    ["option0ValidClassification","Select Valid classification", "有効な分類を選択します"],
    ["option1ValidClassification","Valid", "有効"],
    ["option2ValidClassification", "Invalid", "無効"],
    ["pageSpanDateofleavingthecompany", "Date of leaving the company", "退社年月日"],
    ["buttonUpdateStaff", "Update Staff", "スタッフの更新"],
    ["buttonAddStaff", "Add Staff", "スタッフを追加"],
    ["staffEmergencyContactName", "Example: Taro Yamada", "例：山田太郎"],
    ["staffEmergencyContactNameKatakana", "Example: Taro Yamada", "例：山田太郎"], 
    ["staffEmergencyPostalCode", "Example: 1234567", "例：1234567"],
    ["staffEmergencyContactPhoneNumber", "Example: 09012345678", "例：09012345678"],
    ["staffRelationship", "Example: father", "例：父親"],
    ["buttonEditOtherInformation", "Update Other Information", "その他の情報を編集する"],
    ["buttonEditLoginInformation", "Update Login Information", "ログイン情報の編集"],
    ["buttonEditSocialInformation", "Update Social Information", "社会情報の編集"],
    ["buttonEditSkillSheet", "Update Skill Sheet", "スキルシートの編集"],
    ["buttonEditPayrollInformation","Update Payroll Information", "給与情報の編集"],
    ["buttonEditStaffResume", "Update Staff Resume", "スタッフレジュメの編集"],
    ["buttonEditCredentialInformation", "Update Credential Information", "クレデンシャル情報の編集"],
    ["buttonEditTransportationInformation", "Update Transportation Information", "交通情報の編集"],
    ["buttonEditStaffInformation", "Update Staff Information", "スタッフ情報の編集"],
    ["buttonSaveStaffInformation", "Save Staff Information", "スタッフ情報の保存"],
    ["buttonSaveTransportationInformation", "Save Transportation Information", "交通情報の保存"],
    ["buttonSaveResumeInformation", "Save Resume Information", "履歴書情報の保存"],
    ["buttonSavePayrollInformation", "Save Payroll Information", "保存 ペイロール情報"],
    ["buttonSaveSocialInformation", "Save Social Information", "ソーシャル情報の保存"],
    ["buttonSaveLoginInformation", "Save Login Information", "ログイン情報の保存"],
    ["buttonSaveOtherInformation", "Save Other Information","その他の情報の保存"],
    ["pageSpanTemporary", "Temporary","一時的"],
    ["pageSpanGrievanceStatusFromStaff", "Grievance status from staff","スタッフからの苦情状況"],
    ["pageSpanHelpGrievanceStatusFromStaff", "* The input contents will be reflected in the dispatch source management ledger that is output in association with this staff.","*入力内容は、このスタッフに関連して出力されるディスパッチソース管理元帳に反映されます。"],
    ["pageSpanContentOfEducationAndTraining", "Date and time and content of education and training","教育訓練の日時と内容"],
    ["pageSpanHelpContentOfEducationAndTraining", "* The input contents will be reflected in the dispatch source management ledger that is output in association with this staff.","*入力内容は、このスタッフに関連して出力されるディスパッチソース管理元帳に反映されます。"],
    ["pageSpanContentOfCareerConsulting", "Date and content of career consulting","キャリアコンサルティングの日時と内容"],
    ["pageSpanHelpContentOfCareerConsulting", "* The input contents will be reflected in the dispatch source management ledger that is output in association with this staff.","*入力内容は、このスタッフに関連して出力されるディスパッチソース管理元帳に反映されます。"],
    ["pageSpanDetailsOfEmploymentStabilizationMeasures", "Details of employment stabilization measures","雇用安定化対策の詳細"],
    ["pageSpanHelpDetailsOfEmploymentStabilizationMeasures", "* The input contents will be reflected in the dispatch source management ledger that is output in association with this staff.","*入力内容は、このスタッフに関連して出力されるディスパッチソース管理元帳に反映されます。"]
    
    
    
];
